/*
 *  gen_kw_index.c -- build-time keyword index for the lazy builtin-token
 *  interner in tccpp.c.
 *
 *  tccpp.c recognises a builtin token (keyword, __builtin_*, asm directive,
 *  ...) on a dynamic-hash miss through a small hash index over the
 *  tcc_keywords blob.  It used to build that index at startup into 8 KB of
 *  .bss, which every compiler process paid for in RAM.  The index depends
 *  only on tcctok.h and the target defines, so it is computed here once and
 *  emitted as const tables (pointer-free, so they stay in flash on YasOS).
 *
 *  Like gen_predef_table.c, this is a HOST program compiled with the
 *  TARGET's -D flags: tcctok.h has target conditionals, so "which builtins
 *  exist" is only known once the host preprocessor has run with them.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "tcc.h"

static const char tcc_keywords[] =
#define DEF(id, str) str "\0"
#include "source/frontend/tcctok.h"
#undef DEF
    ;

static unsigned short kw_off[NB_BUILTIN_TOKS];
static unsigned char kw_len[NB_BUILTIN_TOKS];
static unsigned short kw_hash_head[KW_HASH_SIZE];
static unsigned short kw_hash_next[NB_BUILTIN_TOKS];

static void emit(FILE *f, const char *type, const char *name, const void *tab, int n, int elt)
{
  int i;
  fprintf(f, "static const %s %s[%d] = {", type, name, n);
  for (i = 0; i < n; i++)
  {
    unsigned v = elt == 1 ? ((const unsigned char *)tab)[i] : ((const unsigned short *)tab)[i];
    fprintf(f, "%s%u,", i % 16 ? "" : "\n  ", v);
  }
  fprintf(f, "\n};\n");
}

int main(int argc, char **argv)
{
  const char *out = argc > 1 ? argv[1] : "tcckw_index_.h";
  const char *p = tcc_keywords;
  int idx = 0, i;
  unsigned int h;
  FILE *f;

  while (*p)
  {
    int len = (int)strlen(p);
    if (idx >= NB_BUILTIN_TOKS || len > 255 || p - tcc_keywords > 65535)
    {
      fprintf(stderr, "gen_kw_index: keyword table does not fit (idx %d len %d)\n", idx, len);
      return 1;
    }
    kw_off[idx] = (unsigned short)(p - tcc_keywords);
    kw_len[idx] = (unsigned char)len;
    h = TOK_HASH_INIT;
    for (i = 0; i < len; i++)
      h = TOK_HASH_FUNC(h, ((unsigned char *)p)[i]);
    h &= (KW_HASH_SIZE - 1);
    /* Same chain order the runtime builder produced: newest first. */
    kw_hash_next[idx] = kw_hash_head[h];
    kw_hash_head[h] = (unsigned short)(idx + 1);
    idx++;
    p += len + 1;
  }
  if (idx != NB_BUILTIN_TOKS)
  {
    fprintf(stderr, "gen_kw_index: %d keywords, NB_BUILTIN_TOKS is %d\n", idx, NB_BUILTIN_TOKS);
    return 1;
  }

  f = fopen(out, "w");
  if (!f)
  {
    perror(out);
    return 1;
  }
  fprintf(f, "/* generated by gen_kw_index.c from tcctok.h -- do not edit */\n");
  fprintf(f, "#define KW_GEN_COUNT %d\n", idx);
  emit(f, "unsigned short", "kw_off", kw_off, idx, 2);
  emit(f, "unsigned char", "kw_len", kw_len, idx, 1);
  emit(f, "unsigned short", "kw_hash_head", kw_hash_head, KW_HASH_SIZE, 2);
  emit(f, "unsigned short", "kw_hash_next", kw_hash_next, idx, 2);
  return fclose(f) ? 1 : 0;
}
