/*********************************************************************/
/* keywords */
DEF(TOK_IF, "if")
DEF(TOK_ELSE, "else")
DEF(TOK_WHILE, "while")
DEF(TOK_FOR, "for")
DEF(TOK_DO, "do")
DEF(TOK_CONTINUE, "continue")
DEF(TOK_BREAK, "break")
DEF(TOK_RETURN, "return")
DEF(TOK_GOTO, "goto")
DEF(TOK_SWITCH, "switch")
DEF(TOK_CASE, "case")
DEF(TOK_DEFAULT, "default")
DEF(TOK_ASM1, "asm")
DEF(TOK_ASM2, "__asm")
DEF(TOK_ASM3, "__asm__")

DEF(TOK_EXTERN, "extern")
DEF(TOK_STATIC, "static")
DEF(TOK_UNSIGNED, "unsigned")
DEF(TOK__Atomic, "_Atomic")
DEF(TOK_CONST1, "const")
DEF(TOK_CONST2, "__const")   /* gcc keyword */
DEF(TOK_CONST3, "__const__") /* gcc keyword */
DEF(TOK_VOLATILE1, "volatile")
DEF(TOK_VOLATILE2, "__volatile")   /* gcc keyword */
DEF(TOK_VOLATILE3, "__volatile__") /* gcc keyword */
DEF(TOK_REGISTER, "register")
DEF(TOK_SIGNED1, "signed")
DEF(TOK_SIGNED2, "__signed")   /* gcc keyword */
DEF(TOK_SIGNED3, "__signed__") /* gcc keyword */
DEF(TOK_AUTO, "auto")
DEF(TOK_INLINE1, "inline")
DEF(TOK_INLINE2, "__inline")   /* gcc keyword */
DEF(TOK_INLINE3, "__inline__") /* gcc keyword */
DEF(TOK_RESTRICT1, "restrict")
DEF(TOK_RESTRICT2, "__restrict")
DEF(TOK_RESTRICT3, "__restrict__")
DEF(TOK_EXTENSION, "__extension__")    /* gcc keyword */
DEF(TOK_THREAD_LOCAL, "_Thread_local") /* C11 thread-local storage */

DEF(TOK_GENERIC, "_Generic")
DEF(TOK_STATIC_ASSERT, "_Static_assert")

DEF(TOK_VOID, "void")
DEF(TOK_CHAR, "char")
DEF(TOK_INT, "int")
DEF(TOK_FLOAT, "float")
DEF(TOK_DOUBLE, "double")
DEF(TOK_BOOL, "_Bool")
DEF(TOK_COMPLEX, "_Complex")        /* DONE: Phase 1 */
DEF(TOK_COMPLEX_GCC, "__complex__") /* DONE: Phase 1 - GCC extension */
DEF(TOK_COMPLEX_GCC2, "__complex")  /* GCC extension alternate form */
DEF(TOK_DECIMAL32, "_Decimal32")    /* C2x decimal FP (mapped to float) */
DEF(TOK_DECIMAL64, "_Decimal64")    /* C2x decimal FP (mapped to double) */
DEF(TOK_DECIMAL128, "_Decimal128")  /* C2x decimal FP (mapped to long double) */
DEF(TOK_SHORT, "short")
DEF(TOK_LONG, "long")
DEF(TOK_STRUCT, "struct")
DEF(TOK_UNION, "union")
DEF(TOK_TYPEDEF, "typedef")
DEF(TOK_ENUM, "enum")
DEF(TOK_SIZEOF, "sizeof")
DEF(TOK_ATTRIBUTE1, "__attribute")
DEF(TOK_ATTRIBUTE2, "__attribute__")
DEF(TOK_ALIGNOF1, "__alignof")
DEF(TOK_ALIGNOF2, "__alignof__")
DEF(TOK_ALIGNOF3, "_Alignof")
DEF(TOK_ALIGNAS, "_Alignas")
DEF(TOK_TYPEOF1, "typeof")
DEF(TOK_TYPEOF2, "__typeof")
DEF(TOK_TYPEOF3, "__typeof__")
DEF(TOK_LABEL, "__label__")
DEF(TOK_REAL, "__real__")   /* PARTIAL: Phase 4 - parser recognizes, full impl pending */
DEF(TOK_REAL_GCC, "__real") /* GCC extension alternate form */
DEF(TOK_IMAG, "__imag__")   /* PARTIAL: Phase 4 - parser recognizes, full impl pending */
DEF(TOK_IMAG_GCC, "__imag") /* GCC extension alternate form */

#ifdef TCC_TARGET_ARM64
DEF(TOK_UINT128, "__uint128_t")
#endif

/*********************************************************************/
/* the following are not keywords. They are included to ease parsing */
/* preprocessor only */
DEF(TOK_DEFINE, "define")
DEF(TOK_INCLUDE, "include")
DEF(TOK_INCLUDE_NEXT, "include_next")
DEF(TOK_IFDEF, "ifdef")
DEF(TOK_IFNDEF, "ifndef")
DEF(TOK_ELIF, "elif")
DEF(TOK_ENDIF, "endif")
DEF(TOK_DEFINED, "defined")
DEF(TOK_UNDEF, "undef")
DEF(TOK_ERROR, "error")
DEF(TOK_WARNING, "warning")
DEF(TOK_LINE, "line")
DEF(TOK_PRAGMA, "pragma")
DEF(TOK___LINE__, "__LINE__")
DEF(TOK___FILE__, "__FILE__")
DEF(TOK___DATE__, "__DATE__")
DEF(TOK___TIME__, "__TIME__")
DEF(TOK___FUNCTION__, "__FUNCTION__")
DEF(TOK___VA_ARGS__, "__VA_ARGS__")
DEF(TOK___COUNTER__, "__COUNTER__")
DEF(TOK___HAS_INCLUDE, "__has_include")
DEF(TOK___HAS_INCLUDE_NEXT, "__has_include_next")

/* special identifiers */
DEF(TOK___FUNC__, "__func__")

/* special floating point values */
DEF(TOK___NAN__, "__nan__")
DEF(TOK___SNAN__, "__snan__")
DEF(TOK___INF__, "__inf__")
#if defined TCC_TARGET_X86_64
DEF(TOK___mzerosf, "__mzerosf") /* -0.0 */
DEF(TOK___mzerodf, "__mzerodf") /* -0.0 */
#endif

/* attribute identifiers */
/* XXX: handle all tokens generically since speed is not critical */
DEF(TOK_SECTION1, "section")
DEF(TOK_SECTION2, "__section__")
DEF(TOK_ALIGNED1, "aligned")
DEF(TOK_ALIGNED2, "__aligned__")
DEF(TOK_PACKED1, "packed")
DEF(TOK_PACKED2, "__packed__")
DEF(TOK_WEAK1, "weak")
DEF(TOK_WEAK2, "__weak__")
DEF(TOK_ALIAS1, "alias")
DEF(TOK_ALIAS2, "__alias__")
DEF(TOK_UNUSED1, "unused")
DEF(TOK_UNUSED2, "__unused__")
DEF(TOK_NODEBUG1, "nodebug")
DEF(TOK_NODEBUG2, "__nodebug__")
DEF(TOK_CDECL1, "cdecl")
DEF(TOK_CDECL2, "__cdecl")
DEF(TOK_CDECL3, "__cdecl__")
DEF(TOK_STDCALL1, "stdcall")
DEF(TOK_STDCALL2, "__stdcall")
DEF(TOK_STDCALL3, "__stdcall__")
DEF(TOK_FASTCALL1, "fastcall")
DEF(TOK_FASTCALL2, "__fastcall")
DEF(TOK_FASTCALL3, "__fastcall__")
DEF(TOK_THISCALL1, "thiscall")
DEF(TOK_THISCALL2, "__thiscall")
DEF(TOK_THISCALL3, "__thiscall__")
DEF(TOK_REGPARM1, "regparm")
DEF(TOK_REGPARM2, "__regparm__")
DEF(TOK_CLEANUP1, "cleanup")
DEF(TOK_CLEANUP2, "__cleanup__")
DEF(TOK_CONSTRUCTOR1, "constructor")
DEF(TOK_CONSTRUCTOR2, "__constructor__")
DEF(TOK_DESTRUCTOR1, "destructor")
DEF(TOK_DESTRUCTOR2, "__destructor__")
DEF(TOK_ALWAYS_INLINE1, "always_inline")
DEF(TOK_ALWAYS_INLINE2, "__always_inline__")
DEF(TOK_NAKED1, "naked")

DEF(TOK_VECTOR_SIZE1, "vector_size")
DEF(TOK_VECTOR_SIZE2, "__vector_size__")

DEF(TOK_MODE1, "mode")
DEF(TOK_MODE2, "__mode__")
DEF(TOK_MODE_QI1, "QI")
DEF(TOK_MODE_QI2, "__QI__")
DEF(TOK_MODE_DI1, "DI")
DEF(TOK_MODE_DI2, "__DI__")
DEF(TOK_MODE_HI1, "HI")
DEF(TOK_MODE_HI2, "__HI__")
DEF(TOK_MODE_SI1, "SI")
DEF(TOK_MODE_SI2, "__SI__")
DEF(TOK_MODE_word1, "word")
DEF(TOK_MODE_word2, "__word__")

DEF(TOK_DLLEXPORT, "dllexport")
DEF(TOK_DLLIMPORT, "dllimport")
DEF(TOK_NODECORATE, "nodecorate")
DEF(TOK_NORETURN1, "noreturn")
DEF(TOK_NORETURN2, "__noreturn__")
DEF(TOK_NOINLINE1, "noinline")
DEF(TOK_NOINLINE2, "__noinline__")
DEF(TOK_NOIPA1, "noipa")
DEF(TOK_NOIPA2, "__noipa__")
DEF(TOK_NORETURN3, "_Noreturn")
DEF(TOK_PURE1, "pure")
DEF(TOK_PURE2, "__pure__")
/* Note: TOK_CONST1/2/3 already defined for const keyword */
DEF(TOK_VISIBILITY1, "visibility")
DEF(TOK_VISIBILITY2, "__visibility__")
DEF(TOK_SCALAR_STORAGE_ORDER1, "scalar_storage_order")
DEF(TOK_SCALAR_STORAGE_ORDER2, "__scalar_storage_order__")

DEF(TOK_builtin_types_compatible_p, "__builtin_types_compatible_p")
DEF(TOK_builtin_choose_expr, "__builtin_choose_expr")
DEF(TOK_builtin_constant_p, "__builtin_constant_p")
DEF(TOK_builtin_va_arg_pack, "__builtin_va_arg_pack")
DEF(TOK_builtin_va_arg_pack_len, "__builtin_va_arg_pack_len")
DEF(TOK_builtin_frame_address, "__builtin_frame_address")
DEF(TOK_builtin_return_address, "__builtin_return_address")
DEF(TOK_builtin_expect, "__builtin_expect")
DEF(TOK_builtin_abs, "__builtin_abs")
DEF(TOK_builtin_labs, "__builtin_labs")
DEF(TOK_builtin_llabs, "__builtin_llabs")
DEF(TOK_builtin_imaxabs, "__builtin_imaxabs")
DEF(TOK_builtin_uabs, "__builtin_uabs")
DEF(TOK_builtin_ulabs, "__builtin_ulabs")
DEF(TOK_builtin_ullabs, "__builtin_ullabs")
DEF(TOK_builtin_umaxabs, "__builtin_umaxabs")
DEF(TOK_builtin_unreachable, "__builtin_unreachable")
DEF(TOK_builtin_printf, "__builtin_printf")
DEF(TOK_builtin_sprintf, "__builtin_sprintf")
DEF(TOK_builtin_snprintf, "__builtin_snprintf")
DEF(TOK_builtin_trap, "__builtin_trap")
DEF(TOK_builtin_strlen, "__builtin_strlen")
DEF(TOK_builtin_strcpy, "__builtin_strcpy")
DEF(TOK_builtin_strncpy, "__builtin_strncpy")
DEF(TOK_builtin_strcat, "__builtin_strcat")
DEF(TOK_builtin_strncat, "__builtin_strncat")
DEF(TOK_builtin_strcmp, "__builtin_strcmp")
DEF(TOK_builtin_strncmp, "__builtin_strncmp")
DEF(TOK_builtin_memcpy, "__builtin_memcpy")
DEF(TOK_builtin_memmove, "__builtin_memmove")
DEF(TOK_builtin_memset, "__builtin_memset")
DEF(TOK_builtin_bzero, "__builtin_bzero")
DEF(TOK_builtin_clear_padding, "__builtin_clear_padding")
DEF(TOK_builtin_memcmp, "__builtin_memcmp")
DEF(TOK_builtin_memcmp_eq, "__builtin_memcmp_eq")
DEF(TOK_builtin_memchr, "__builtin_memchr")
DEF(TOK_builtin_strchr, "__builtin_strchr")
DEF(TOK_builtin_strrchr, "__builtin_strrchr")
DEF(TOK_builtin_strstr, "__builtin_strstr")
DEF(TOK_builtin_strpbrk, "__builtin_strpbrk")
DEF(TOK_builtin_strspn, "__builtin_strspn")
DEF(TOK_builtin_strcspn, "__builtin_strcspn")
DEF(TOK_builtin_strnlen, "__builtin_strnlen")
DEF(TOK_builtin_mempcpy, "__builtin_mempcpy")
DEF(TOK_builtin_stpcpy, "__builtin_stpcpy")
DEF(TOK_builtin_stpncpy, "__builtin_stpncpy")
DEF(TOK_builtin_fputs, "__builtin_fputs")
DEF(TOK_builtin_fprintf, "__builtin_fprintf")
DEF(TOK_builtin_ilogb, "__builtin_ilogb")
DEF(TOK_builtin_shufflevector, "__builtin_shufflevector")
DEF(TOK_builtin_convertvector, "__builtin_convertvector")
/* Fortified/chk variants */
DEF(TOK_builtin___memcpy_chk, "__builtin___memcpy_chk")
DEF(TOK_builtin___memmove_chk, "__builtin___memmove_chk")
DEF(TOK_builtin___memset_chk, "__builtin___memset_chk")
DEF(TOK_builtin___mempcpy_chk, "__builtin___mempcpy_chk")
DEF(TOK_builtin___strcpy_chk, "__builtin___strcpy_chk")
DEF(TOK_builtin___stpcpy_chk, "__builtin___stpcpy_chk")
DEF(TOK_builtin___strcat_chk, "__builtin___strcat_chk")
DEF(TOK_builtin___strncpy_chk, "__builtin___strncpy_chk")
DEF(TOK_builtin___stpncpy_chk, "__builtin___stpncpy_chk")
DEF(TOK_builtin___strncat_chk, "__builtin___strncat_chk")
DEF(TOK_builtin___sprintf_chk, "__builtin___sprintf_chk")
DEF(TOK_builtin___snprintf_chk, "__builtin___snprintf_chk")
DEF(TOK_builtin___vsprintf_chk, "__builtin___vsprintf_chk")
DEF(TOK_builtin___vsnprintf_chk, "__builtin___vsnprintf_chk")
DEF(TOK_builtin_object_size, "__builtin_object_size")
DEF(TOK_builtin_abort, "__builtin_abort")
DEF(TOK_builtin_malloc, "__builtin_malloc")
DEF(TOK_builtin_free, "__builtin_free")
DEF(TOK_builtin_calloc, "__builtin_calloc")
DEF(TOK_builtin_realloc, "__builtin_realloc")
DEF(TOK_builtin_ffs, "__builtin_ffs")
DEF(TOK_builtin_ffsl, "__builtin_ffsl")
DEF(TOK_builtin_ffsll, "__builtin_ffsll")
DEF(TOK_builtin_clz, "__builtin_clz")
DEF(TOK_builtin_clzl, "__builtin_clzl")
DEF(TOK_builtin_clzll, "__builtin_clzll")
DEF(TOK_builtin_ctz, "__builtin_ctz")
DEF(TOK_builtin_ctzl, "__builtin_ctzl")
DEF(TOK_builtin_ctzll, "__builtin_ctzll")
DEF(TOK_builtin_popcount, "__builtin_popcount")
DEF(TOK_builtin_popcountl, "__builtin_popcountl")
DEF(TOK_builtin_popcountll, "__builtin_popcountll")
DEF(TOK_builtin_parity, "__builtin_parity")
DEF(TOK_builtin_parityl, "__builtin_parityl")
DEF(TOK_builtin_parityll, "__builtin_parityll")

DEF(TOK_builtin_classify_type, "__builtin_classify_type")
DEF(TOK_builtin_signbit, "__builtin_signbit")
DEF(TOK_builtin_signbitf, "__builtin_signbitf")
DEF(TOK_builtin_isinf, "__builtin_isinf")
DEF(TOK_builtin_isinff, "__builtin_isinff")
DEF(TOK_builtin_isinfl, "__builtin_isinfl")
DEF(TOK_builtin_copysign, "__builtin_copysign")
DEF(TOK_builtin_copysignf, "__builtin_copysignf")
DEF(TOK_builtin_isnan, "__builtin_isnan")
DEF(TOK_builtin_isnanf, "__builtin_isnanf")
DEF(TOK_builtin_isnanl, "__builtin_isnanl")
DEF(TOK_builtin_inf, "__builtin_inf")
DEF(TOK_builtin_inff, "__builtin_inff")
DEF(TOK_builtin_infl, "__builtin_infl")
DEF(TOK_builtin_nan, "__builtin_nan")
DEF(TOK_builtin_nanf, "__builtin_nanf")
DEF(TOK_builtin_nanl, "__builtin_nanl")
DEF(TOK_builtin_huge_val, "__builtin_huge_val")
DEF(TOK_builtin_huge_valf, "__builtin_huge_valf")
DEF(TOK_builtin_huge_vall, "__builtin_huge_vall")
DEF(TOK_builtin_isunordered, "__builtin_isunordered")
DEF(TOK_builtin_isless, "__builtin_isless")
DEF(TOK_builtin_isgreater, "__builtin_isgreater")
DEF(TOK_builtin_islessequal, "__builtin_islessequal")
DEF(TOK_builtin_isgreaterequal, "__builtin_isgreaterequal")
DEF(TOK_builtin_islessgreater, "__builtin_islessgreater")
DEF(TOK_builtin_fabs, "__builtin_fabs")
DEF(TOK_builtin_fabsf, "__builtin_fabsf")
DEF(TOK_builtin_fabsl, "__builtin_fabsl")
DEF(TOK_builtin_copysignl, "__builtin_copysignl")
DEF(TOK_builtin_modff, "__builtin_modff")
DEF(TOK_builtin_modf, "__builtin_modf")
DEF(TOK_builtin_modfl, "__builtin_modfl")
DEF(TOK_builtin_isfinite, "__builtin_isfinite")
DEF(TOK_builtin_isfinitef, "__builtin_isfinitef")
DEF(TOK_builtin_isinf_sign, "__builtin_isinf_sign")
DEF(TOK_builtin_fmax, "__builtin_fmax")
DEF(TOK_builtin_fmaxf, "__builtin_fmaxf")
DEF(TOK_builtin_fmaxl, "__builtin_fmaxl")
DEF(TOK_builtin_fmin, "__builtin_fmin")
DEF(TOK_builtin_fminf, "__builtin_fminf")
DEF(TOK_builtin_fminl, "__builtin_fminl")
DEF(TOK_builtin_isnormal, "__builtin_isnormal")
DEF(TOK_builtin_fpclassify, "__builtin_fpclassify")
DEF(TOK___isnan, "isnan")
DEF(TOK___isnanf, "isnanf")
DEF(TOK___fabs, "fabs")
DEF(TOK___fabsf, "fabsf")
DEF(TOK___isinf, "isinf")
DEF(TOK___isinff, "isinff")
DEF(TOK___finite, "finite")
DEF(TOK___finitef, "finitef")
DEF(TOK___fmax, "fmax")
DEF(TOK___fmaxf, "fmaxf")
DEF(TOK___fmaxl, "fmaxl")
DEF(TOK___fmin, "fmin")
DEF(TOK___fminf, "fminf")
DEF(TOK___fminl, "fminl")
DEF(TOK_builtin_bswap16, "__builtin_bswap16")
DEF(TOK_builtin_bswap32, "__builtin_bswap32")
DEF(TOK_builtin_bswap64, "__builtin_bswap64")
DEF(TOK_builtin_prefetch, "__builtin_prefetch")
DEF(TOK_builtin_setjmp, "__builtin_setjmp")
DEF(TOK_builtin_longjmp, "__builtin_longjmp")
DEF(TOK_builtin_alloca, "__builtin_alloca")
DEF(TOK_builtin_apply_args, "__builtin_apply_args")
DEF(TOK_builtin_apply, "__builtin_apply")
DEF(TOK_builtin_return, "__builtin_return")
DEF(TOK_builtin_add_overflow, "__builtin_add_overflow")
DEF(TOK_builtin_sub_overflow, "__builtin_sub_overflow")
DEF(TOK_builtin_mul_overflow, "__builtin_mul_overflow")
DEF(TOK_builtin_sadd_overflow, "__builtin_sadd_overflow")
DEF(TOK_builtin_uadd_overflow, "__builtin_uadd_overflow")
DEF(TOK_builtin_ssub_overflow, "__builtin_ssub_overflow")
DEF(TOK_builtin_usub_overflow, "__builtin_usub_overflow")
DEF(TOK_builtin_smul_overflow, "__builtin_smul_overflow")
DEF(TOK_builtin_umul_overflow, "__builtin_umul_overflow")
DEF(TOK_builtin_add_overflow_p, "__builtin_add_overflow_p")
DEF(TOK_builtin_sub_overflow_p, "__builtin_sub_overflow_p")
DEF(TOK_builtin_mul_overflow_p, "__builtin_mul_overflow_p")
DEF(TOK_builtin_shuffle, "__builtin_shuffle")
DEF(TOK_builtin_conjf, "__builtin_conjf")
DEF(TOK_builtin_conj, "__builtin_conj")
DEF(TOK_builtin_conjl, "__builtin_conjl")
DEF(TOK_builtin_crealf, "__builtin_crealf")
DEF(TOK_builtin_creal, "__builtin_creal")
DEF(TOK_builtin_creall, "__builtin_creall")
DEF(TOK_builtin_cimagf, "__builtin_cimagf")
DEF(TOK_builtin_cimag, "__builtin_cimag")
DEF(TOK_builtin_cimagl, "__builtin_cimagl")
DEF(TOK___copysign, "copysign")
DEF(TOK___copysignf, "copysignf")
/*DEF(TOK_builtin_va_list, "__builtin_va_list")*/
#if defined TCC_TARGET_PE && defined TCC_TARGET_X86_64
DEF(TOK_builtin_va_start, "__builtin_va_start")
#elif defined TCC_TARGET_X86_64
DEF(TOK_builtin_va_arg_types, "__builtin_va_arg_types")
#elif defined TCC_TARGET_ARM
DEF(TOK_builtin_va_arg, "__builtin_va_arg")
DEF(TOK___tcc_va_arg, "__tcc_va_arg")
DEF(TOK_NOINSTRUMENT1, "no_instrument_function")
DEF(TOK_NOINSTRUMENT2, "__no_instrument_function__")
#elif defined TCC_TARGET_ARM64
DEF(TOK_builtin_va_start, "__builtin_va_start")
DEF(TOK_builtin_va_arg, "__builtin_va_arg")
#elif defined TCC_TARGET_RISCV64
DEF(TOK_builtin_va_start, "__builtin_va_start")
#endif

/* atomic operations */
#define DEF_ATOMIC(ID) DEF(TOK_##__##ID, "__" #ID)
DEF_ATOMIC(atomic_store)
DEF_ATOMIC(atomic_load)
DEF_ATOMIC(atomic_exchange)
DEF_ATOMIC(atomic_compare_exchange)
DEF_ATOMIC(atomic_fetch_add)
DEF_ATOMIC(atomic_fetch_sub)
DEF_ATOMIC(atomic_fetch_or)
DEF_ATOMIC(atomic_fetch_xor)
DEF_ATOMIC(atomic_fetch_and)
DEF_ATOMIC(atomic_fetch_nand)
DEF_ATOMIC(atomic_add_fetch)
DEF_ATOMIC(atomic_sub_fetch)
DEF_ATOMIC(atomic_or_fetch)
DEF_ATOMIC(atomic_xor_fetch)
DEF_ATOMIC(atomic_and_fetch)
DEF_ATOMIC(atomic_nand_fetch)

/* pragma */
DEF(TOK_pack, "pack")
#if !defined(TCC_TARGET_I386) && !defined(TCC_TARGET_X86_64) && !defined(TCC_TARGET_ARM) &&                            \
    !defined(TCC_TARGET_ARM64) && !defined(TCC_TARGET_RISCV64)
/* already defined for assembler */
DEF(TOK_ASM_push, "push")
DEF(TOK_ASM_pop, "pop")
#endif
DEF(TOK_comment, "comment")
DEF(TOK_lib, "lib")
DEF(TOK_push_macro, "push_macro")
DEF(TOK_pop_macro, "pop_macro")
DEF(TOK_once, "once")
DEF(TOK_option, "option")

/* builtin functions or variables */
#ifndef TCC_ARM_EABI
DEF(TOK_memcpy, "memcpy")
DEF(TOK_memmove, "memmove")
DEF(TOK_memset, "memset")
DEF(TOK___divdi3, "__divdi3")
DEF(TOK___moddi3, "__moddi3")
DEF(TOK___udivdi3, "__udivdi3")
DEF(TOK___umoddi3, "__umoddi3")
DEF(TOK___ashrdi3, "__ashrdi3")
DEF(TOK___lshrdi3, "__lshrdi3")
DEF(TOK___ashldi3, "__ashldi3")
DEF(TOK___floatundisf, "__floatundisf")
DEF(TOK___floatundidf, "__floatundidf")
#ifndef TCC_ARM_VFP
DEF(TOK___floatundixf, "__floatundixf")
DEF(TOK___fixunsxfdi, "__fixunsxfdi")
#endif
DEF(TOK___fixunssfdi, "__fixunssfdi")
DEF(TOK___fixunsdfdi, "__fixunsdfdi")
#endif
DEF(TOK___bswapdi3, "__bswapdi3")
DEF(TOK___bswapsi2, "__bswapsi2")

#if defined TCC_TARGET_ARM
#ifdef TCC_ARM_EABI
DEF(TOK_memcpy, "__aeabi_memcpy")
DEF(TOK_memmove, "__aeabi_memmove")
DEF(TOK_memmove4, "__aeabi_memmove4")
DEF(TOK_memmove8, "__aeabi_memmove8")
DEF(TOK_memset, "__aeabi_memset")
DEF(TOK___aeabi_ldivmod, "__aeabi_ldivmod")
DEF(TOK___aeabi_uldivmod, "__aeabi_uldivmod")
DEF(TOK___aeabi_lmod, "__aeabi_lmod")
DEF(TOK___aeabi_ulmod, "__aeabi_ulmod")
DEF(TOK___aeabi_idivmod, "__aeabi_idivmod")
DEF(TOK___aeabi_uidivmod, "__aeabi_uidivmod")
DEF(TOK___aeabi_lcmp, "__aeabi_lcmp")
DEF(TOK___aeabi_ulcmp, "__aeabi_ulcmp")
DEF(TOK___divsi3, "__aeabi_idiv")
DEF(TOK___udivsi3, "__aeabi_uidiv")
DEF(TOK___floatdisf, "__aeabi_l2f")
DEF(TOK___floatdidf, "__aeabi_l2d")
DEF(TOK___fixsfdi, "__aeabi_f2lz")
DEF(TOK___fixdfdi, "__aeabi_d2lz")
DEF(TOK___ashrdi3, "__aeabi_lasr")
DEF(TOK___lshrdi3, "__aeabi_llsr")
DEF(TOK___ashldi3, "__aeabi_llsl")
DEF(TOK___floatundisf, "__aeabi_ul2f")
DEF(TOK___floatundidf, "__aeabi_ul2d")
DEF(TOK___fixunssfdi, "__aeabi_f2ulz")
DEF(TOK___fixunsdfdi, "__aeabi_d2ulz")
#else
DEF(TOK___modsi3, "__modsi3")
DEF(TOK___umodsi3, "__umodsi3")
DEF(TOK___divsi3, "__divsi3")
DEF(TOK___udivsi3, "__udivsi3")
DEF(TOK___floatdisf, "__floatdisf")
DEF(TOK___floatdidf, "__floatdidf")
#ifndef TCC_ARM_VFP
DEF(TOK___floatdixf, "__floatdixf")
DEF(TOK___fixunssfsi, "__fixunssfsi")
DEF(TOK___fixunsdfsi, "__fixunsdfsi")
DEF(TOK___fixunsxfsi, "__fixunsxfsi")
DEF(TOK___fixxfdi, "__fixxfdi")
#endif
DEF(TOK___fixsfdi, "__fixsfdi")
DEF(TOK___fixdfdi, "__fixdfdi")
#endif
#endif

#if defined TCC_TARGET_C67
DEF(TOK__divi, "_divi")
DEF(TOK__divu, "_divu")
DEF(TOK__divf, "_divf")
DEF(TOK__divd, "_divd")
DEF(TOK__remi, "_remi")
DEF(TOK__remu, "_remu")
#endif

#if defined TCC_TARGET_I386
DEF(TOK___fixsfdi, "__fixsfdi")
DEF(TOK___fixdfdi, "__fixdfdi")
DEF(TOK___fixxfdi, "__fixxfdi")
#endif

#if defined TCC_TARGET_I386 || defined TCC_TARGET_X86_64 || defined TCC_TARGET_ARM
DEF(TOK_alloca, "alloca")
#endif

#if defined TCC_TARGET_PE
DEF(TOK___chkstk, "__chkstk")
#endif
#if defined TCC_TARGET_ARM64 || defined TCC_TARGET_RISCV64
DEF(TOK___arm64_clear_cache, "__arm64_clear_cache")
DEF(TOK___addtf3, "__addtf3")
DEF(TOK___subtf3, "__subtf3")
DEF(TOK___multf3, "__multf3")
DEF(TOK___divtf3, "__divtf3")
DEF(TOK___extendsftf2, "__extendsftf2")
DEF(TOK___extenddftf2, "__extenddftf2")
DEF(TOK___trunctfsf2, "__trunctfsf2")
DEF(TOK___trunctfdf2, "__trunctfdf2")
DEF(TOK___fixtfsi, "__fixtfsi")
DEF(TOK___fixtfdi, "__fixtfdi")
DEF(TOK___fixunstfsi, "__fixunstfsi")
DEF(TOK___fixunstfdi, "__fixunstfdi")
DEF(TOK___floatsitf, "__floatsitf")
DEF(TOK___floatditf, "__floatditf")
DEF(TOK___floatunsitf, "__floatunsitf")
DEF(TOK___floatunditf, "__floatunditf")
DEF(TOK___eqtf2, "__eqtf2")
DEF(TOK___netf2, "__netf2")
DEF(TOK___lttf2, "__lttf2")
DEF(TOK___letf2, "__letf2")
DEF(TOK___gttf2, "__gttf2")
DEF(TOK___getf2, "__getf2")
#endif

/* bound checking symbols */
#ifdef CONFIG_TCC_BCHECK
DEF(TOK___bound_ptr_add, "__bound_ptr_add")
DEF(TOK___bound_ptr_indir1, "__bound_ptr_indir1")
DEF(TOK___bound_ptr_indir2, "__bound_ptr_indir2")
DEF(TOK___bound_ptr_indir4, "__bound_ptr_indir4")
DEF(TOK___bound_ptr_indir8, "__bound_ptr_indir8")
DEF(TOK___bound_ptr_indir12, "__bound_ptr_indir12")
DEF(TOK___bound_ptr_indir16, "__bound_ptr_indir16")
DEF(TOK___bound_main_arg, "__bound_main_arg")
DEF(TOK___bound_local_new, "__bound_local_new")
DEF(TOK___bound_local_delete, "__bound_local_delete")
DEF(TOK___bound_setjmp, "__bound_setjmp")
DEF(TOK___bound_longjmp, "__bound_longjmp")
DEF(TOK___bound_new_region, "__bound_new_region")
#ifdef TCC_TARGET_PE
#ifdef TCC_TARGET_X86_64
DEF(TOK___bound_alloca_nr, "__bound_alloca_nr")
#endif
#else
DEF(TOK_sigsetjmp, "sigsetjmp")
DEF(TOK___sigsetjmp, "__sigsetjmp")
DEF(TOK_siglongjmp, "siglongjmp")
#endif
DEF(TOK_setjmp, "setjmp")
DEF(TOK__setjmp, "_setjmp")
DEF(TOK_longjmp, "longjmp")
#endif

/*********************************************************************/
/* Tiny Assembler */
#define DEF_ASM(x) DEF(TOK_ASM_##x, #x)
#define DEF_ASMDIR(x) DEF(TOK_ASMDIR_##x, "." #x)
#define TOK_ASM_int TOK_INT

#define TOK_ASMDIR_FIRST TOK_ASMDIR_byte
#define TOK_ASMDIR_LAST TOK_ASMDIR_section

DEF_ASMDIR(byte) /* must be first directive */
DEF_ASMDIR(word)
DEF_ASMDIR(align)
DEF_ASMDIR(balign)
DEF_ASMDIR(p2align)
DEF_ASMDIR(set)
DEF_ASMDIR(skip)
DEF_ASMDIR(space)
DEF_ASMDIR(string)
DEF_ASMDIR(asciz)
DEF_ASMDIR(ascii)
DEF_ASMDIR(file)
DEF_ASMDIR(globl)
DEF_ASMDIR(global)
DEF_ASMDIR(weak)
DEF_ASMDIR(hidden)
DEF_ASMDIR(ident)
DEF_ASMDIR(size)
DEF_ASMDIR(type)
DEF_ASMDIR(text)
DEF_ASMDIR(data)
DEF_ASMDIR(bss)
DEF_ASMDIR(previous)
DEF_ASMDIR(pushsection)
DEF_ASMDIR(popsection)
DEF_ASMDIR(fill)
DEF_ASMDIR(rept)
DEF_ASMDIR(endr)
DEF_ASMDIR(org)
DEF_ASMDIR(quad)
DEF_ASMDIR(macro)
DEF_ASMDIR(endm)
#if defined(TCC_TARGET_I386)
DEF_ASMDIR(code16)
DEF_ASMDIR(code32)
#elif defined(TCC_TARGET_X86_64)
DEF_ASMDIR(code64)
#elif defined(TCC_TARGET_RISCV64)
DEF_ASMDIR(option)
#endif
DEF_ASMDIR(short)
DEF_ASMDIR(long)
DEF_ASMDIR(int)
DEF_ASMDIR(symver)
DEF_ASMDIR(syntax)
DEF_ASMDIR(arch)
DEF_ASMDIR(thumb)
DEF_ASMDIR(thumb_func)
DEF_ASMDIR(section) /* must be last directive */

#if defined TCC_TARGET_I386 || defined TCC_TARGET_X86_64
#include "i386-tok.h"
#endif

#if defined TCC_TARGET_ARM || defined TCC_TARGET_ARM64
#if defined TCC_TARGET_ARM_ARCHV8M
#include "thumb-tok.h"
#else
#include "arm-tok.h"
#endif
#endif

#if defined TCC_TARGET_RISCV64
#include "riscv64-tok.h"
#endif
