services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      GF_INSTALL_PLUGINS: frser-sqlite-datasource
      GF_AUTH_ANONYMOUS_ENABLED: "false"
    volumes:
      - /var/lib/tcc-metrics/metrics.db:/data/metrics.db:ro
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/etc/grafana/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana-data:
