/* Regression test (verbatim differential-fuzz repro, gen_c.py seed=2966).
 * At -O1/-O2 tcc ABORTED the compile ("compiler_error: mach_get_dest_reg:
 * unexpected kind 3"): the codegen MUL+ADD fusion peephole (ir/codegen.c) fed
 * the ADD's destination into tcc_gen_machine_mul_const_add_fused_mop without
 * checking its operand kind; once const-prop folded the ADD's result to a
 * constant the dest decoded as MACH_OP_IMM, which mach_get_dest_reg rejects.
 * Fix: only fuse into a register-class destination, else lower the ADD normally.
 * tcc -O0 was always correct; the crash appeared at -O1/-O2.  Expected checksum
 * is gcc -m32 -funsigned-char (ARM ABI: unsigned char, 32-bit long).
 */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=2966
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)((~((unsigned)(pa) | 0u))) - (unsigned)(((unsigned)(pb) << ((unsigned)(1240598626u) & 31u)))));
  lr = (unsigned)(((unsigned)(((unsigned)(lr) + (unsigned)(((unsigned)(1755264488u) ^ (unsigned)(1100593355u))))) << ((unsigned)(((unsigned)(((unsigned)(4259135177u) >> ((unsigned)(lr) & 31u))) * (unsigned)(pa))) & 31u)));
  return (unsigned)(((unsigned)(pa) / ((unsigned)(pb) | 1u))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(((unsigned)((-((unsigned)(206002882u) | 0u))) >> ((unsigned)(15119886u) & 31u))) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(lr) % ((unsigned)(pb) | 1u))) * (unsigned)(((unsigned)(pa) >> ((unsigned)(lr) & 31u)))));
  lr = (unsigned)(pb);
  return (unsigned)(((unsigned)(lr) % ((unsigned)(helper1(3956276271u, ((unsigned)(lr) | (unsigned)(pb)))) | 1u))) ^ lr;
}

static unsigned helper3(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(lr);
  lr = (unsigned)(2605645829u);
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(604283925u) | (unsigned)(2453199477u))) / ((unsigned)(((unsigned)(pb) << ((unsigned)(pa) & 31u))) | 1u))) - (unsigned)(3839556812u)));
  lr = (unsigned)(pb);
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(pa) ^ (unsigned)(1886196974u))) % ((unsigned)(((unsigned)(pb) ^ (unsigned)(1402154852u))) | 1u))) + (unsigned)(978701915u)));
  return (unsigned)(((unsigned)(4259960404u) >= ((unsigned)(((unsigned)(((unsigned)(2409263462u) < ((unsigned)(2258746215u) ^ lr))) % ((unsigned)((-((unsigned)(320694343u) | 0u))) | 1u))) ^ lr))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s4 = (short)(282778107u & 0xffff);
  long s5 = (long)(843667288u & 0xffffffff);
  unsigned u6 = 1882792554u;
  unsigned u7 = 43206133u;
  unsigned u8 = 3854297553u;
  unsigned u9 = 3241937218u;
  struct S st10 = { 2026612359u, 1314202172u, 1539968272u };

  { unsigned g12 = 0u;
    while (g12 < 5u) {
      unsigned i11 = g12;
      cs = csmix(cs, i11);
      u8 = (unsigned)((((unsigned)(((unsigned)(u8) + (unsigned)(u6))) & 1u) ? (unsigned)(((unsigned)(1958886944u) / ((unsigned)(((unsigned)(((unsigned)(u8) * (unsigned)(((unsigned)(u8) ^ cs)))) + (unsigned)(((unsigned)((unsigned)(s4)) / ((unsigned)(446134781u) | 1u))))) | 1u))) : (unsigned)(((unsigned)(((unsigned)((-((unsigned)(u8) | 0u))) << ((unsigned)(1249617381u) & 31u))) >> ((unsigned)(((unsigned)(st10.f0) % ((unsigned)(3981905663u) | 1u))) & 31u))))) & 0xffffffffu;
      g12++;
    }
  }
  st10.f1 = (unsigned)(((unsigned)((unsigned)(s4)) != ((unsigned)(3163444052u) ^ cs)));
  cs = csmix(cs, (unsigned)((unsigned)(s5)));

  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, u9);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, helper3(38177487u, cs));
  cs = csmix(cs, (unsigned)s4);
  cs = csmix(cs, (unsigned)s5);
  cs = csmix(cs, st10.f0);
  cs = csmix(cs, st10.f1);
  cs = csmix(cs, st10.f2);
  printf("checksum=%08x\n", cs);
  return 0;
}
