/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=2857
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

int main(void)
{
  unsigned cs = 0x12345678u;
  char s1 = (char)(308079981u & 0xff);
  int s2 = (int)(442182420u & 0xffffffff);
  unsigned u3 = 1166267719u;
  unsigned u4 = 3164083343u;
  unsigned u5 = 773209241u;
  unsigned u6 = 236078812u;
  unsigned u7 = 3160594536u;
  unsigned arr8[8] = { 4097646247u, 671874294u, 54265665u, 3589994347u, 496905032u, 4164336495u, 3555230628u, 2590610025u };

  arr8[((unsigned)(u3) & 7u)] = (unsigned)(u6);
  if ((unsigned)(((unsigned)(((unsigned)(u4) << ((unsigned)(arr8[((unsigned)(u6) & 7u)]) & 31u))) >> ((unsigned)(((unsigned)((((unsigned)((~((unsigned)((unsigned)(s1)) | 0u))) & 1u) ? (unsigned)(u7) : (unsigned)((~((unsigned)(815529490u) | 0u))))) / ((unsigned)(u7) | 1u))) & 31u))) & 1u) {
    for (unsigned g10 = 0u; g10 < 11u; g10++) {
      unsigned i9 = g10;
      cs = csmix(cs, i9);
      cs = csmix(cs, (unsigned)(2383914027u));
      u3 = (unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) % ((unsigned)(((unsigned)(((unsigned)(u4) <= ((unsigned)(arr8[((unsigned)(u6) & 7u)]) ^ cs))) - (unsigned)(arr8[((unsigned)(2120697025u) & 7u)]))) | 1u))) - (unsigned)(1710440371u))) & 0xffffffffu;
      u6 = (unsigned)((-((unsigned)(((unsigned)(((unsigned)((~((unsigned)(u3) | 0u))) & (unsigned)(((unsigned)(4046658167u) % ((unsigned)(arr8[((unsigned)(u5) & 7u)]) | 1u))))) / ((unsigned)(((unsigned)(2038287800u) * (unsigned)(2222280558u))) | 1u))) | 0u))) & 0xffffffffu;
      u6 = (unsigned)(((unsigned)((-((unsigned)(2618098665u) | 0u))) * (unsigned)((-((unsigned)(((unsigned)((~((unsigned)((unsigned)(s1)) | 0u))) << ((unsigned)(((unsigned)((unsigned)(s1)) | (unsigned)(u5))) & 31u))) | 0u))))) & 0xffffffffu;
      u4 = (unsigned)(i9) & 0xffffffffu;
    }
    for (unsigned g12 = 0u; g12 < 4u; g12++) {
      unsigned i11 = g12;
      cs = csmix(cs, i11);
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(arr8[((unsigned)(u4) & 7u)]) - (unsigned)(u6))) % ((unsigned)(u5) | 1u))) >> ((unsigned)((-((unsigned)(((unsigned)(2493610373u) >> ((unsigned)((unsigned)(s1)) & 31u))) | 0u))) & 31u))) & (unsigned)(((unsigned)(((unsigned)((-((unsigned)((unsigned)(s2)) | 0u))) >> ((unsigned)(((unsigned)(2350233176u) == ((unsigned)(u4) ^ cs))) & 31u))) / ((unsigned)(((unsigned)(((unsigned)(arr8[((unsigned)(u4) & 7u)]) | (unsigned)(arr8[((unsigned)(u5) & 7u)]))) >= ((unsigned)(((unsigned)(350773042u) << ((unsigned)(4113070857u) & 31u))) ^ cs))) | 1u))))));
    }
    if ((unsigned)((((unsigned)(arr8[((unsigned)(u3) & 7u)]) & 1u) ? (unsigned)(((unsigned)(((unsigned)(((unsigned)(u7) != ((unsigned)(u5) ^ cs))) ^ (unsigned)(2203534202u))) << ((unsigned)(arr8[((unsigned)(u6) & 7u)]) & 31u))) : (unsigned)(((unsigned)((~((unsigned)(269333988u) | 0u))) >> ((unsigned)(((unsigned)(arr8[((unsigned)(4277643738u) & 7u)]) / ((unsigned)(4043128440u) | 1u))) & 31u))))) & 1u) {
      u4 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(2252171485u) / ((unsigned)((-((unsigned)(u3) | 0u))) | 1u))) | (unsigned)(arr8[((unsigned)(u4) & 7u)]))) - (unsigned)(((unsigned)(((unsigned)(((unsigned)(2337400565u) | (unsigned)((unsigned)(s1)))) & (unsigned)(((unsigned)(arr8[((unsigned)(u4) & 7u)]) + (unsigned)(656604247u))))) ^ (unsigned)(((unsigned)(((unsigned)(185637250u) >> ((unsigned)(arr8[((unsigned)(u7) & 7u)]) & 31u))) & (unsigned)((~((unsigned)(2952601481u) | 0u))))))))) & 0xffffffffu;
      u3 = (unsigned)((((unsigned)(arr8[((unsigned)(1457693141u) & 7u)]) & 1u) ? (unsigned)(((unsigned)((((unsigned)((-((unsigned)(u7) | 0u))) & 1u) ? (unsigned)(((unsigned)((unsigned)(s2)) - (unsigned)(u4))) : (unsigned)((unsigned)(s2)))) <= ((unsigned)(((unsigned)(((unsigned)(u7) & (unsigned)((unsigned)(s2)))) != ((unsigned)(((unsigned)((unsigned)(s2)) << ((unsigned)(328311196u) & 31u))) ^ cs))) ^ cs))) : (unsigned)(119014110u))) & 0xffffffffu;
      cs = csmix(cs, (unsigned)(arr8[((unsigned)(u3) & 7u)]));
    }
    arr8[((unsigned)(2368771170u) & 7u)] = (unsigned)(((unsigned)(u4) / ((unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) << ((unsigned)(407559884u) & 31u))) >> ((unsigned)((((unsigned)(arr8[((unsigned)(1994854751u) & 7u)]) & 1u) ? (unsigned)(u6) : (unsigned)(2845045954u))) & 31u))) >> ((unsigned)(u3) & 31u))) | 1u)));
    for (unsigned g14 = 0u; g14 < 2u; g14++) {
      unsigned i13 = g14;
      cs = csmix(cs, i13);
      u7 = (unsigned)(((unsigned)(((unsigned)(u7) / ((unsigned)((-((unsigned)(404019814u) | 0u))) | 1u))) - (unsigned)((unsigned)(s1)))) & 0xffffffffu;
    }
  } else {
    { unsigned g16 = 0u;
      while (g16 < 11u) {
        unsigned i15 = g16;
        cs = csmix(cs, i15);
        u3 = (unsigned)(arr8[((unsigned)(2072078412u) & 7u)]) & 0xffffffffu;
        arr8[((unsigned)(2825036772u) & 7u)] = (unsigned)(3634830448u);
        cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)(arr8[((unsigned)(i15) & 7u)]) & 1u) ? (unsigned)(((unsigned)(((unsigned)(u3) ^ (unsigned)(2191112580u))) < ((unsigned)((unsigned)(s1)) ^ cs))) : (unsigned)(arr8[((unsigned)(u3) & 7u)]))) >> ((unsigned)(((unsigned)(((unsigned)(((unsigned)(1242085312u) + (unsigned)(u6))) | (unsigned)((unsigned)(s1)))) - (unsigned)(((unsigned)((((unsigned)((unsigned)(s2)) & 1u) ? (unsigned)(2944883307u) : (unsigned)(23961650u))) << ((unsigned)((((unsigned)(2575391008u) & 1u) ? (unsigned)(1656695014u) : (unsigned)((unsigned)(s1)))) & 31u))))) & 31u))));
        u4 = (unsigned)((-((unsigned)(((unsigned)(((unsigned)(((unsigned)(2077070236u) | (unsigned)(3686986111u))) - (unsigned)(((unsigned)(u4) >> ((unsigned)(u5) & 31u))))) == ((unsigned)(((unsigned)(((unsigned)(3083973439u) >> ((unsigned)(arr8[((unsigned)(u6) & 7u)]) & 31u))) | (unsigned)(1489778230u))) ^ cs))) | 0u))) & 0xffffffffu;
        cs = csmix(cs, (unsigned)((unsigned)(s2)));
        arr8[((unsigned)(i15) & 7u)] = (unsigned)(((unsigned)(1649825945u) + (unsigned)(2859829182u)));
        g16++;
      }
    }
    { unsigned g18 = 0u;
      while (g18 < 10u) {
        unsigned i17 = g18;
        cs = csmix(cs, i17);
        u6 = (unsigned)(((unsigned)((((unsigned)(1891336054u) & 1u) ? (unsigned)(((unsigned)(arr8[((unsigned)(47684923u) & 7u)]) >> ((unsigned)((~((unsigned)(821324487u) | 0u))) & 31u))) : (unsigned)(((unsigned)(u6) >> ((unsigned)(((unsigned)(arr8[((unsigned)(3353570366u) & 7u)]) << ((unsigned)(4083875310u) & 31u))) & 31u))))) / ((unsigned)((unsigned)(s1)) | 1u))) & 0xffffffffu;
        cs = csmix(cs, (unsigned)(((unsigned)(3169120779u) << ((unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) - (unsigned)(2881380115u))) & (unsigned)(((unsigned)(u3) / ((unsigned)(arr8[((unsigned)(1801925744u) & 7u)]) | 1u))))) * (unsigned)(((unsigned)(((unsigned)(1778852590u) / ((unsigned)(arr8[((unsigned)(990303124u) & 7u)]) | 1u))) / ((unsigned)((~((unsigned)((unsigned)(s1)) | 0u))) | 1u))))) & 31u))));
        u5 = (unsigned)(u6) & 0xffffffffu;
        i17 = (unsigned)(((unsigned)(1037679387u) * (unsigned)((((unsigned)(((unsigned)(((unsigned)(186643867u) + (unsigned)(arr8[((unsigned)(3996975577u) & 7u)]))) % ((unsigned)(3176836852u) | 1u))) & 1u) ? (unsigned)(((unsigned)(((unsigned)(arr8[((unsigned)(u3) & 7u)]) | (unsigned)(u5))) <= ((unsigned)((unsigned)(s2)) ^ cs))) : (unsigned)(((unsigned)((~((unsigned)((unsigned)(s1)) | 0u))) >> ((unsigned)(((unsigned)(3568229890u) ^ (unsigned)((unsigned)(s1)))) & 31u))))))) & 0xffffffffu;
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(u3) - (unsigned)(((unsigned)(2229708948u) * (unsigned)((-((unsigned)(u5) | 0u))))))) % ((unsigned)(arr8[((unsigned)(u3) & 7u)]) | 1u))));
        g18++;
      }
    }
    if ((unsigned)((((unsigned)((unsigned)(s1)) & 1u) ? (unsigned)((((unsigned)((((unsigned)(((unsigned)(2443594112u) <= ((unsigned)(u6) ^ cs))) & 1u) ? (unsigned)(((unsigned)(u4) >= ((unsigned)(u3) ^ cs))) : (unsigned)(u3))) & 1u) ? (unsigned)(u4) : (unsigned)(((unsigned)(((unsigned)(u5) & (unsigned)(u3))) % ((unsigned)(((unsigned)(2848214917u) * (unsigned)(u3))) | 1u))))) : (unsigned)(u3))) & 1u) {
      u3 = (unsigned)(3823606695u) & 0xffffffffu;
      cs = csmix(cs, (unsigned)(((unsigned)(arr8[((unsigned)(u6) & 7u)]) / ((unsigned)(1364943214u) | 1u))));
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)((-((unsigned)(u6) | 0u))) ^ (unsigned)(u5))) << ((unsigned)(3185629047u) & 31u))));
    }
    arr8[((unsigned)(u5) & 7u)] = (unsigned)(arr8[((unsigned)(1696422390u) & 7u)]);
  }

  cs = csmix(cs, u3);
  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, (unsigned)s1);
  cs = csmix(cs, (unsigned)s2);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr8[k]);
  printf("checksum=%08x\n", cs);
  return 0;
}
