/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=1205
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(pa) & 1u) lr += (unsigned)(2861389414u);
  lr = (unsigned)(645616987u);
  if ((unsigned)(pa) & 1u) lr += (unsigned)(3290564147u);
  lr = (unsigned)(((unsigned)(((unsigned)((~((unsigned)(1888973223u) | 0u))) * (unsigned)(pa))) | (unsigned)(2844219535u)));
  lr = (unsigned)(((unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(lr) : (unsigned)(((unsigned)(pb) - (unsigned)(2765089491u))))) >> ((unsigned)(((unsigned)(994031161u) * (unsigned)(((unsigned)(pb) % ((unsigned)(lr) | 1u))))) & 31u)));
  return (unsigned)(((unsigned)((((unsigned)((-((unsigned)(1701318760u) | 0u))) & 1u) ? (unsigned)(((unsigned)(2911029406u) | (unsigned)(2911952391u))) : (unsigned)(4169893792u))) - (unsigned)(((unsigned)((((unsigned)(572552970u) & 1u) ? (unsigned)(lr) : (unsigned)(2872579212u))) + (unsigned)(((unsigned)(pa) >> ((unsigned)(3824121944u) & 31u))))))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(pa);
  lr = (unsigned)(((unsigned)(pb) ^ (unsigned)(((unsigned)((((unsigned)(220645197u) & 1u) ? (unsigned)(pb) : (unsigned)(((unsigned)(pb) ^ lr)))) ^ (unsigned)(3887530713u)))));
  if ((unsigned)((-((unsigned)(helper1(2107671320u, 3857857025u)) | 0u))) & 1u) lr += (unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(((unsigned)(3078397228u) | (unsigned)(pb))) : (unsigned)((((unsigned)(2271006202u) & 1u) ? (unsigned)(3150987874u) : (unsigned)(lr)))));
  if ((unsigned)(((unsigned)(lr) << ((unsigned)(((unsigned)(lr) * (unsigned)(3672016692u))) & 31u))) & 1u) lr += (unsigned)(3846489335u);
  lr = (unsigned)(3956149062u);
  return (unsigned)(((unsigned)(lr) >> ((unsigned)(3958009278u) & 31u))) ^ lr;
}

static unsigned helper3(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(pa) & 1u) lr += (unsigned)(pa);
  lr = (unsigned)(247852281u);
  return (unsigned)(((unsigned)(((unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(1061421726u) : (unsigned)(pa))) * (unsigned)(helper1(502083490u, 1294003599u)))) >> ((unsigned)(((unsigned)(helper1(2996908752u, 3923221072u)) % ((unsigned)(helper2(1860605364u, 3906569774u)) | 1u))) & 31u))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  long s4 = (long)(2050475600u & 0xffffffff);
  char s5 = (char)(1751934144u & 0xff);
  unsigned u6 = 3463025026u;
  unsigned u7 = 4037443301u;
  unsigned u8 = 1130699635u;
  unsigned u9 = 2913311712u;
  struct S st10 = { 54162909u, 2435673546u, 570340605u };

  cs = csmix(cs, (unsigned)(st10.f1));
  st10.f1 = (unsigned)(516683239u);
  u6 = (unsigned)(3292932635u) & 0xffffffffu;
  for (unsigned g12 = 0u; g12 < 9u; g12++) {
    unsigned i11 = g12;
    cs = csmix(cs, i11);
    st10.f0 = (unsigned)((-((unsigned)(1146839978u) | 0u)));
    cs = csmix(cs, (unsigned)(helper3(((unsigned)(helper3(u6, ((unsigned)(i11) ^ (unsigned)(1445886625u)))) ^ (unsigned)(((unsigned)(u9) - (unsigned)(((unsigned)(u6) / ((unsigned)((unsigned)(s4)) | 1u)))))), 2137004210u)));
    cs = csmix(cs, (unsigned)(((unsigned)(921984402u) ^ (unsigned)(u8))));
    cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(helper3(1636091664u, (unsigned)(s4))) - (unsigned)(((unsigned)(((unsigned)(u7) == ((unsigned)(i11) ^ cs))) + (unsigned)(((unsigned)((unsigned)(s4)) - (unsigned)(st10.f2))))))) % ((unsigned)(((unsigned)((((unsigned)(((unsigned)(1998204614u) % ((unsigned)(3031375423u) | 1u))) & 1u) ? (unsigned)(u9) : (unsigned)(1299054176u))) / ((unsigned)(u9) | 1u))) | 1u))));
  }
  u9 = (unsigned)(st10.f0) & 0xffffffffu;

  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, u9);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, helper3(38177487u, cs));
  cs = csmix(cs, (unsigned)s4);
  cs = csmix(cs, (unsigned)s5);
  cs = csmix(cs, st10.f0);
  cs = csmix(cs, st10.f1);
  cs = csmix(cs, st10.f2);
  printf("checksum=%08x\n", cs);
  return 0;
}
