/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=765
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s1 = (short)(1809932946u & 0xffff);
  char s2 = (char)(762735910u & 0xff);
  unsigned u3 = 3922212363u;
  unsigned u4 = 1088128810u;
  unsigned u5 = 4145086001u;
  unsigned arr6[8] = { 553784252u, 2867029281u, 815602914u, 2067464914u, 3544552023u, 3085176268u, 394342147u, 432661742u };
  unsigned arr7[8] = { 1080430535u, 1357370002u, 1432028209u, 2093137200u, 3064362331u, 843036253u, 961150269u, 575853722u };

  u5 = (unsigned)(((unsigned)((((unsigned)((~((unsigned)(((unsigned)(u4) << ((unsigned)(((unsigned)(u4) ^ cs)) & 31u))) | 0u))) & 1u) ? (unsigned)(((unsigned)(((unsigned)(u4) & (unsigned)(arr6[((unsigned)(u5) & 7u)]))) * (unsigned)(u5))) : (unsigned)((((unsigned)(((unsigned)(u5) != ((unsigned)(arr6[((unsigned)(u5) & 7u)]) ^ cs))) & 1u) ? (unsigned)(u3) : (unsigned)(u4))))) ^ (unsigned)(u4))) & 0xffffffffu;
  cs = csmix(cs, (unsigned)(arr7[((unsigned)(u4) & 7u)]));
  cs = csmix(cs, (unsigned)((unsigned)(s2)));
  cs = csmix(cs, (unsigned)((unsigned)(s1)));
  cs = csmix(cs, (unsigned)(4237028227u));
  arr6[((unsigned)(957377377u) & 7u)] = (unsigned)((unsigned)(s2));

  cs = csmix(cs, u3);
  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, (unsigned)s1);
  cs = csmix(cs, (unsigned)s2);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr6[k]);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr7[k]);
  printf("checksum=%08x\n", cs);
  return 0;
}
