/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=860
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(lr) & 1u) lr += (unsigned)(((unsigned)(2585990281u) % ((unsigned)(((unsigned)(3825183115u) / ((unsigned)(468168426u) | 1u))) | 1u)));
  if ((unsigned)(((unsigned)(pb) >> ((unsigned)(((unsigned)(2720631731u) & (unsigned)(lr))) & 31u))) & 1u) lr += (unsigned)(((unsigned)((~((unsigned)(pa) | 0u))) ^ (unsigned)(((unsigned)(1634103511u) >> ((unsigned)(pa) & 31u)))));
  lr = (unsigned)(((unsigned)(((unsigned)((~((unsigned)(1504196471u) | 0u))) <= ((unsigned)(((unsigned)(3250366864u) | (unsigned)(pb))) ^ lr))) % ((unsigned)(((unsigned)(3141444613u) << ((unsigned)(((unsigned)(pa) * (unsigned)(1514057190u))) & 31u))) | 1u)));
  return (unsigned)(((unsigned)(lr) - (unsigned)(pa))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  int s2 = (int)(1129231739u & 0xffffffff);
  short s3 = (short)(1168551692u & 0xffff);
  unsigned u4 = 2895625484u;
  unsigned u5 = 3351242172u;
  unsigned arr6[8] = { 937241612u, 2853345641u, 3478668612u, 2482095374u, 13965844u, 4293084162u, 2695667916u, 4110383898u };
  unsigned arr7[8] = { 3171226633u, 3981883684u, 1325182059u, 2748153749u, 3887114220u, 3203672835u, 2635803551u, 4196430537u };

  { unsigned g9 = 0u;
    while (g9 < 3u) {
      unsigned i8 = g9;
      cs = csmix(cs, i8);
      { unsigned g11 = 0u;
        while (g11 < 4u) {
          unsigned i10 = g11;
          cs = csmix(cs, i10);
          u5 = (unsigned)(u4) & 0xffffffffu;
          u5 = (unsigned)(((unsigned)(((unsigned)((((unsigned)((~((unsigned)(u4) | 0u))) & 1u) ? (unsigned)(helper1(i10, 3344314600u)) : (unsigned)(arr7[((unsigned)(i10) & 7u)]))) < ((unsigned)(((unsigned)(((unsigned)(2695476054u) & (unsigned)(1573083668u))) + (unsigned)((-((unsigned)(3999406574u) | 0u))))) ^ cs))) | (unsigned)(arr7[((unsigned)(2071925997u) & 7u)]))) & 0xffffffffu;
          cs = csmix(cs, (unsigned)((~((unsigned)(((unsigned)((((unsigned)(arr6[((unsigned)(u4) & 7u)]) & 1u) ? (unsigned)(((unsigned)((unsigned)(s3)) ^ (unsigned)(((unsigned)((unsigned)(s3)) ^ cs)))) : (unsigned)((-((unsigned)(u5) | 0u))))) + (unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) % ((unsigned)(3377921981u) | 1u))) + (unsigned)((((unsigned)(912398817u) & 1u) ? (unsigned)(arr6[((unsigned)(i8) & 7u)]) : (unsigned)(u4))))))) | 0u))));
          cs = csmix(cs, (unsigned)(helper1(((unsigned)(((unsigned)(i10) & (unsigned)(((unsigned)(1599823919u) ^ (unsigned)(i8))))) - (unsigned)(((unsigned)((-((unsigned)(i8) | 0u))) % ((unsigned)(((unsigned)(i8) + (unsigned)(((unsigned)(i8) ^ cs)))) | 1u)))), ((unsigned)((~((unsigned)(3455876826u) | 0u))) << ((unsigned)(((unsigned)((unsigned)(s2)) % ((unsigned)(i10) | 1u))) & 31u)))));
          u4 = (unsigned)(((unsigned)(((unsigned)(i10) >> ((unsigned)(((unsigned)(3934741555u) + (unsigned)(((unsigned)((unsigned)(s2)) / ((unsigned)(((unsigned)((unsigned)(s2)) ^ cs)) | 1u))))) & 31u))) * (unsigned)(((unsigned)(u5) % ((unsigned)(((unsigned)(arr7[((unsigned)(i8) & 7u)]) ^ (unsigned)(((unsigned)(arr7[((unsigned)(645053011u) & 7u)]) >> ((unsigned)(3615135899u) & 31u))))) | 1u))))) & 0xffffffffu;
          g11++;
        }
      }
      if ((unsigned)(((unsigned)(((unsigned)(arr6[((unsigned)(u5) & 7u)]) * (unsigned)(1483707201u))) + (unsigned)((unsigned)(s3)))) & 1u) {
        u5 = (unsigned)(((unsigned)(((unsigned)(1530615833u) << ((unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) % ((unsigned)(510348357u) | 1u))) > ((unsigned)(((unsigned)(1722303419u) ^ (unsigned)(1273842082u))) ^ cs))) & 31u))) * (unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(((unsigned)(((unsigned)(u5) - (unsigned)(3558131701u))) - (unsigned)(((unsigned)(1269624758u) | (unsigned)(2358024504u))))))))) & 0xffffffffu;
        cs = csmix(cs, (unsigned)((-((unsigned)(((unsigned)(((unsigned)(((unsigned)(i8) - (unsigned)(u5))) ^ (unsigned)((((unsigned)(i8) & 1u) ? (unsigned)(u5) : (unsigned)(((unsigned)(u5) ^ cs)))))) + (unsigned)(u4))) | 0u))));
      } else {
        u4 = (unsigned)((((unsigned)((-((unsigned)(i8) | 0u))) & 1u) ? (unsigned)((-((unsigned)((unsigned)(s2)) | 0u))) : (unsigned)((unsigned)(s3)))) & 0xffffffffu;
        i8 = (unsigned)(3066422920u) & 0xffffffffu;
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(763548328u) & (unsigned)((~((unsigned)(i8) | 0u))))) % ((unsigned)(((unsigned)(u4) * (unsigned)(((unsigned)(((unsigned)(arr6[((unsigned)(u4) & 7u)]) >> ((unsigned)(3306560826u) & 31u))) | (unsigned)(((unsigned)(i8) / ((unsigned)(1690438748u) | 1u))))))) | 1u))));
        u5 = (unsigned)((-((unsigned)(3952782326u) | 0u))) & 0xffffffffu;
      }
      g9++;
    }
  }
  u4 = (unsigned)((-((unsigned)(((unsigned)(((unsigned)(((unsigned)(arr7[((unsigned)(u5) & 7u)]) + (unsigned)(3335529279u))) | (unsigned)((((unsigned)(u4) & 1u) ? (unsigned)(2670134353u) : (unsigned)(u5))))) - (unsigned)(u5))) | 0u))) & 0xffffffffu;
  u5 = (unsigned)(((unsigned)(2443557505u) / ((unsigned)((~((unsigned)(arr7[((unsigned)(3414804725u) & 7u)]) | 0u))) | 1u))) & 0xffffffffu;

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr6[k]);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr7[k]);
  printf("checksum=%08x\n", cs);
  return 0;
}
