/* Regression: -O2 compiler crash "STORE operand produced MACH_OP_NONE".
 *
 * Verbatim differential-fuzz repro (gen_c.py seed=8078).  Crashed only at -O2;
 * -O0/-O1/-Os were fine.  Correct checksum is the tcc -O0 oracle = e39fd06b
 * (also stable across -O1/-Os).
 *
 * Root cause: the codegen two-pass loop caches each instruction's decoded
 * MachineOperands in mop_cache during the dry-run and replays them in the
 * real-run.  The STRD-spill-immediate peephole (ir/codegen.c) fuses two
 * adjacent immediate stores to spill slots into one STRD and SKIPS the second
 * store (i = next_i; break).  Its feasibility test runs the offset through
 * fp_adjust_local_offset(), whose allocated_stack_size term is 0 during the
 * dry-run (the prologue that sets it is emitted only before the real pass) but
 * final during the real-run.  This function has a large frame (>1KB), so the
 * struct-init store pair's SP-relative offset is small in the dry-run (fuse +
 * skip the 2nd store) but exceeds STRD's 1020 range in the real-run (no fuse).
 * The skipped store's mop_cache slot was thus never written; the real-run read
 * it back as all-MACH_OP_NONE and the codegen sanity assert fired.
 *
 * Fix: zero-init mop_cache and re-decode in the real-run when a cached slot is
 * the all-NONE "never populated" sentinel (ir_decode_cached).
 */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=8078
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(lr) ^ (unsigned)(1571160703u)));
  if ((unsigned)(((unsigned)(((unsigned)(pa) | (unsigned)(((unsigned)(pa) ^ lr)))) << ((unsigned)((-((unsigned)(pa) | 0u))) & 31u))) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(3865426650u) << ((unsigned)(158956380u) & 31u))) * (unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(pa) : (unsigned)(pb)))));
  return (unsigned)(lr) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s2 = (char)(1877207308u & 0xff);
  long s3 = (long)(1787470118u & 0xffffffff);
  long s4 = (long)(1336703947u & 0xffffffff);
  unsigned u5 = 2106659728u;
  unsigned u6 = 2961952771u;
  unsigned u7 = 3926142820u;
  unsigned u8 = 93006076u;
  struct S st9 = { 1333479120u, 69536405u, 2976117760u };
  struct S st10 = { 2326952477u, 1840421695u, 2363459926u };

  if ((unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) - (unsigned)(3276265280u))) << ((unsigned)(((unsigned)((~((unsigned)(helper1((unsigned)(s2), 2110529709u)) | 0u))) >> ((unsigned)(((unsigned)(((unsigned)(u7) * (unsigned)(49692009u))) + (unsigned)((unsigned)(s3)))) & 31u))) & 31u))) & 1u) {
    u5 = (unsigned)((((unsigned)(((unsigned)(343254383u) % ((unsigned)(1041126768u) | 1u))) & 1u) ? (unsigned)(st10.f2) : (unsigned)(helper1(st10.f1, ((unsigned)(((unsigned)(u7) & (unsigned)(186700438u))) - (unsigned)((((unsigned)(2417924842u) & 1u) ? (unsigned)((unsigned)(s2)) : (unsigned)(u7)))))))) & 0xffffffffu;
    st10.f1 = (unsigned)(((unsigned)(((unsigned)(1657473693u) & (unsigned)(1683016312u))) << ((unsigned)(((unsigned)(u8) * (unsigned)(st10.f2))) & 31u)));
    for (unsigned g12 = 0u; g12 < 9u; g12++) {
      unsigned i11 = g12;
      cs = csmix(cs, i11);
      cs = csmix(cs, (unsigned)((unsigned)(s4)));
      st10.f1 = (unsigned)(637026925u);
      st10.f1 = (unsigned)(((unsigned)(st10.f1) ^ (unsigned)(((unsigned)(((unsigned)(((unsigned)(3096369740u) >> ((unsigned)(u5) & 31u))) * (unsigned)((-((unsigned)(2461350983u) | 0u))))) + (unsigned)(helper1(((unsigned)(u8) != ((unsigned)(u5) ^ cs)), ((unsigned)(u5) + (unsigned)(4230761660u))))))));
      st10.f2 = (unsigned)(((unsigned)((~((unsigned)(((unsigned)((unsigned)(s3)) > ((unsigned)(((unsigned)(1886051329u) - (unsigned)(u6))) ^ cs))) | 0u))) & (unsigned)(((unsigned)(u7) < ((unsigned)(((unsigned)(((unsigned)(st9.f2) * (unsigned)(u7))) * (unsigned)(((unsigned)(st9.f2) ^ (unsigned)((unsigned)(s2)))))) ^ cs)))));
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(1423377806u) - (unsigned)((((unsigned)(helper1(2957027809u, u6)) & 1u) ? (unsigned)(3907315714u) : (unsigned)(u8))))) >> ((unsigned)(((unsigned)(((unsigned)(u7) | (unsigned)((~((unsigned)((unsigned)(s3)) | 0u))))) + (unsigned)(((unsigned)(helper1(i11, u8)) > ((unsigned)(st9.f2) ^ cs))))) & 31u))));
    }
    for (unsigned g14 = 0u; g14 < 7u; g14++) {
      unsigned i13 = g14;
      cs = csmix(cs, i13);
      st9.f1 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(2678805726u) | (unsigned)((unsigned)(s4)))) + (unsigned)(((unsigned)(u5) >> ((unsigned)(u7) & 31u))))) >> ((unsigned)((unsigned)(s4)) & 31u))) <= ((unsigned)(((unsigned)(u8) * (unsigned)(((unsigned)(helper1(st10.f2, 4114272963u)) * (unsigned)(u5))))) ^ cs)));
      cs = csmix(cs, (unsigned)(3740845202u));
      cs = csmix(cs, (unsigned)((((unsigned)((unsigned)(s2)) & 1u) ? (unsigned)((-((unsigned)(((unsigned)((unsigned)(s4)) / ((unsigned)(st10.f1) | 1u))) | 0u))) : (unsigned)(helper1(((unsigned)(918707958u) >= ((unsigned)(((unsigned)(st9.f1) ^ (unsigned)((unsigned)(s2)))) ^ cs)), ((unsigned)(((unsigned)((unsigned)(s3)) - (unsigned)(u6))) >> ((unsigned)(((unsigned)(u6) + (unsigned)(u7))) & 31u)))))));
      cs = csmix(cs, (unsigned)(3985817295u));
    }
    u5 = (unsigned)((-((unsigned)(1138929989u) | 0u))) & 0xffffffffu;
    if ((unsigned)((~((unsigned)(((unsigned)(((unsigned)(3836337221u) % ((unsigned)(((unsigned)(st9.f2) | (unsigned)(513961344u))) | 1u))) >> ((unsigned)(helper1(u5, 3666106397u)) & 31u))) | 0u))) & 1u) {
      st10.f0 = (unsigned)(u6);
      st10.f1 = (unsigned)(((unsigned)(((unsigned)(1491902531u) >> ((unsigned)(st9.f1) & 31u))) * (unsigned)(((unsigned)((((unsigned)(((unsigned)(105982048u) >> ((unsigned)(u5) & 31u))) & 1u) ? (unsigned)(((unsigned)(4141353371u) << ((unsigned)(u8) & 31u))) : (unsigned)(helper1(st9.f2, (unsigned)(s4))))) >> ((unsigned)(u7) & 31u)))));
      st9.f0 = (unsigned)(((unsigned)(u7) ^ (unsigned)(u6)));
    } else {
      u5 = (unsigned)(st10.f0) & 0xffffffffu;
      u6 = (unsigned)(1725060077u) & 0xffffffffu;
      st9.f0 = (unsigned)((~((unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(((unsigned)((unsigned)(s3)) ^ cs)))) << ((unsigned)((((unsigned)(st9.f2) & 1u) ? (unsigned)(3042011337u) : (unsigned)(2422441910u))) & 31u))) & (unsigned)((~((unsigned)(((unsigned)(u7) | (unsigned)(u8))) | 0u))))) | 0u)));
    }
  } else {
    { unsigned g16 = 0u;
      while (g16 < 5u) {
        unsigned i15 = g16;
        cs = csmix(cs, i15);
        st10.f2 = (unsigned)(((unsigned)((-((unsigned)(((unsigned)(((unsigned)((unsigned)(s4)) ^ (unsigned)(u5))) * (unsigned)((unsigned)(s4)))) | 0u))) >> ((unsigned)(((unsigned)((~((unsigned)((~((unsigned)(i15) | 0u))) | 0u))) ^ (unsigned)((~((unsigned)(3142248761u) | 0u))))) & 31u)));
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)((((unsigned)(((unsigned)(3184371445u) / ((unsigned)((unsigned)(s2)) | 1u))) & 1u) ? (unsigned)((-((unsigned)((unsigned)(s4)) | 0u))) : (unsigned)((((unsigned)(st9.f0) & 1u) ? (unsigned)(1025334368u) : (unsigned)(1658886774u))))) - (unsigned)(((unsigned)(((unsigned)(u7) ^ (unsigned)(u8))) / ((unsigned)((~((unsigned)(3724965401u) | 0u))) | 1u))))) ^ (unsigned)((-((unsigned)(2117749501u) | 0u))))));
        st9.f0 = (unsigned)(((unsigned)(u7) | (unsigned)(((unsigned)((unsigned)(s3)) / ((unsigned)(u7) | 1u)))));
        g16++;
      }
    }
    u7 = (unsigned)(((unsigned)(((unsigned)(1157216688u) % ((unsigned)(953820585u) | 1u))) >> ((unsigned)(((unsigned)((unsigned)(s3)) - (unsigned)(((unsigned)(((unsigned)(st10.f0) - (unsigned)(u7))) << ((unsigned)(((unsigned)(u8) << ((unsigned)(u5) & 31u))) & 31u))))) & 31u))) & 0xffffffffu;
    for (unsigned g18 = 0u; g18 < 8u; g18++) {
      unsigned i17 = g18;
      cs = csmix(cs, i17);
      cs = csmix(cs, (unsigned)((-((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) | (unsigned)((((unsigned)(u5) & 1u) ? (unsigned)(2110210275u) : (unsigned)(u6))))) % ((unsigned)(((unsigned)(st10.f0) >= ((unsigned)(helper1(u6, u8)) ^ cs))) | 1u))) | 0u))));
      cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)(1741644647u) & 1u) ? (unsigned)(helper1(((unsigned)(2962727122u) ^ (unsigned)((unsigned)(s3))), ((unsigned)(i17) >> ((unsigned)(u8) & 31u)))) : (unsigned)(3744588576u))) ^ (unsigned)(st9.f0))));
      cs = csmix(cs, (unsigned)(helper1((unsigned)(s4), u8)));
      u5 = (unsigned)((((unsigned)(u7) & 1u) ? (unsigned)(1691185571u) : (unsigned)(((unsigned)(((unsigned)((-((unsigned)((unsigned)(s2)) | 0u))) / ((unsigned)(142214933u) | 1u))) >> ((unsigned)(((unsigned)(2183432343u) % ((unsigned)((-((unsigned)(2447413498u) | 0u))) | 1u))) & 31u))))) & 0xffffffffu;
    }
    for (unsigned g20 = 0u; g20 < 8u; g20++) {
      unsigned i19 = g20;
      cs = csmix(cs, i19);
      u7 = (unsigned)(((unsigned)((-((unsigned)(((unsigned)((~((unsigned)(832366289u) | 0u))) & (unsigned)(st10.f1))) | 0u))) - (unsigned)((~((unsigned)(((unsigned)(((unsigned)(st9.f1) ^ (unsigned)((unsigned)(s2)))) ^ (unsigned)(((unsigned)(801073753u) % ((unsigned)(u8) | 1u))))) | 0u))))) & 0xffffffffu;
      u5 = (unsigned)(((unsigned)(u8) ^ (unsigned)((unsigned)(s2)))) & 0xffffffffu;
      u6 = (unsigned)(2642559285u) & 0xffffffffu;
      cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)(((unsigned)(4210608249u) << ((unsigned)(((unsigned)(1340767248u) >= ((unsigned)((unsigned)(s2)) ^ cs))) & 31u))) & 1u) ? (unsigned)(helper1(((unsigned)(u6) + (unsigned)(u5)), i19)) : (unsigned)(((unsigned)(((unsigned)((unsigned)(s4)) >> ((unsigned)((unsigned)(s3)) & 31u))) * (unsigned)(3931608155u))))) | (unsigned)(((unsigned)((-((unsigned)(((unsigned)(st10.f2) / ((unsigned)(96988668u) | 1u))) | 0u))) + (unsigned)(((unsigned)(2198896221u) % ((unsigned)((-((unsigned)(u8) | 0u))) | 1u))))))));
    }
    u8 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) ^ (unsigned)(st10.f1))) & (unsigned)((~((unsigned)(st9.f1) | 0u))))) >> ((unsigned)(((unsigned)((((unsigned)(st10.f2) & 1u) ? (unsigned)(3532660082u) : (unsigned)((unsigned)(s4)))) < ((unsigned)((((unsigned)((unsigned)(s4)) & 1u) ? (unsigned)(st10.f1) : (unsigned)(((unsigned)(st10.f1) ^ cs)))) ^ cs))) & 31u))) - (unsigned)((((unsigned)(((unsigned)(u6) | (unsigned)(((unsigned)(st9.f2) >= ((unsigned)(st9.f0) ^ cs))))) & 1u) ? (unsigned)((-((unsigned)((-((unsigned)(u7) | 0u))) | 0u))) : (unsigned)(((unsigned)((~((unsigned)(3005406595u) | 0u))) % ((unsigned)(u7) | 1u))))))) & 0xffffffffu;
    { unsigned g22 = 0u;
      while (g22 < 5u) {
        unsigned i21 = g22;
        cs = csmix(cs, i21);
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(842856057u) >> ((unsigned)(((unsigned)(u7) * (unsigned)(st10.f2))) & 31u))) ^ (unsigned)((((unsigned)(((unsigned)(((unsigned)(u5) >> ((unsigned)(i21) & 31u))) + (unsigned)(((unsigned)(1995131611u) & (unsigned)(st9.f0))))) & 1u) ? (unsigned)(((unsigned)(((unsigned)(158155209u) - (unsigned)(u5))) - (unsigned)((-((unsigned)(u5) | 0u))))) : (unsigned)(((unsigned)(((unsigned)(u8) ^ (unsigned)(st9.f2))) >> ((unsigned)(u8) & 31u))))))));
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(1050441051u) + (unsigned)(1894747611u))) - (unsigned)(((unsigned)(3831850584u) + (unsigned)(u5))))) % ((unsigned)((((unsigned)(((unsigned)(u5) / ((unsigned)(2161117266u) | 1u))) & 1u) ? (unsigned)(4221308568u) : (unsigned)(((unsigned)(2446870697u) >> ((unsigned)((unsigned)(s3)) & 31u))))) | 1u))) << ((unsigned)(i21) & 31u))));
        g22++;
      }
    }
  }
  { unsigned g24 = 0u;
    while (g24 < 12u) {
      unsigned i23 = g24;
      cs = csmix(cs, i23);
      if ((unsigned)(((unsigned)(3593612181u) + (unsigned)(((unsigned)(st9.f1) | (unsigned)(((unsigned)(((unsigned)(st9.f0) < ((unsigned)(st10.f2) ^ cs))) % ((unsigned)(2927104608u) | 1u))))))) & 1u) {
        i23 = (unsigned)(((unsigned)(u8) % ((unsigned)(((unsigned)(4232993144u) & (unsigned)(((unsigned)(((unsigned)(u8) / ((unsigned)(i23) | 1u))) % ((unsigned)(((unsigned)(3222233735u) | (unsigned)(i23))) | 1u))))) | 1u))) & 0xffffffffu;
        cs = csmix(cs, (unsigned)(helper1(((unsigned)((-((unsigned)(u7) | 0u))) + (unsigned)(297452457u)), (((unsigned)(((unsigned)(helper1(i23, 1652990793u)) * (unsigned)(((unsigned)((unsigned)(s3)) << ((unsigned)(u5) & 31u))))) & 1u) ? (unsigned)(((unsigned)((unsigned)(s2)) << ((unsigned)((((unsigned)(2845849098u) & 1u) ? (unsigned)(4235973759u) : (unsigned)((unsigned)(s3)))) & 31u))) : (unsigned)(st10.f1)))));
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) | (unsigned)(((unsigned)(((unsigned)(u7) == ((unsigned)(st10.f2) ^ cs))) + (unsigned)(((unsigned)(3137714690u) > ((unsigned)(u7) ^ cs))))))) >> ((unsigned)(u8) & 31u))));
        u6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(3212071788u) - (unsigned)((((unsigned)(u7) & 1u) ? (unsigned)(765329601u) : (unsigned)(st9.f0))))) % ((unsigned)((-((unsigned)(u8) | 0u))) | 1u))) | (unsigned)((~((unsigned)((unsigned)(s2)) | 0u))))) & 0xffffffffu;
        u6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(helper1(u6, u8)))) - (unsigned)(helper1((-((unsigned)((unsigned)(s4)) | 0u)), helper1(2618461788u, 572506283u))))) ^ (unsigned)(u7))) & 0xffffffffu;
        u6 = (unsigned)(((unsigned)((~((unsigned)(((unsigned)((-((unsigned)(u6) | 0u))) == ((unsigned)((-((unsigned)(i23) | 0u))) ^ cs))) | 0u))) * (unsigned)(u6))) & 0xffffffffu;
      }
      g24++;
    }
  }
  for (unsigned g26 = 0u; g26 < 6u; g26++) {
    unsigned i25 = g26;
    cs = csmix(cs, i25);
    cs = csmix(cs, (unsigned)(u6));
    u7 = (unsigned)(((unsigned)(((unsigned)(3699879226u) << ((unsigned)(u6) & 31u))) % ((unsigned)(((unsigned)((unsigned)(s3)) / ((unsigned)(((unsigned)(2550041386u) > ((unsigned)(((unsigned)(2526174922u) << ((unsigned)(i25) & 31u))) ^ cs))) | 1u))) | 1u))) & 0xffffffffu;
    for (unsigned g28 = 0u; g28 < 3u; g28++) {
      unsigned i27 = g28;
      cs = csmix(cs, i27);
      cs = csmix(cs, (unsigned)(((unsigned)(u5) < ((unsigned)(((unsigned)((-((unsigned)(((unsigned)((unsigned)(s3)) >> ((unsigned)(st9.f0) & 31u))) | 0u))) % ((unsigned)(((unsigned)(((unsigned)(u8) << ((unsigned)(st10.f2) & 31u))) % ((unsigned)(u6) | 1u))) | 1u))) ^ cs))));
      st9.f2 = (unsigned)((~((unsigned)(((unsigned)((-((unsigned)(3423252437u) | 0u))) >> ((unsigned)(((unsigned)(u8) * (unsigned)(i25))) & 31u))) | 0u)));
      cs = csmix(cs, (unsigned)(((unsigned)(u6) >> ((unsigned)(helper1(((unsigned)((~((unsigned)((unsigned)(s2)) | 0u))) / ((unsigned)(((unsigned)(218632179u) / ((unsigned)(st9.f1) | 1u))) | 1u)), ((unsigned)(st9.f2) + (unsigned)(st9.f1)))) & 31u))));
      cs = csmix(cs, (unsigned)((-((unsigned)(u8) | 0u))));
      st9.f0 = (unsigned)(st9.f0);
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)((-((unsigned)(st10.f0) | 0u))) * (unsigned)(((unsigned)(2548115161u) * (unsigned)(u5))))) - (unsigned)(i27))) >= ((unsigned)(i27) ^ cs))));
    }
    for (unsigned g30 = 0u; g30 < 3u; g30++) {
      unsigned i29 = g30;
      cs = csmix(cs, i29);
      cs = csmix(cs, (unsigned)((unsigned)(s4)));
      st9.f0 = (unsigned)(2671475491u);
      cs = csmix(cs, (unsigned)(((unsigned)((-((unsigned)(u5) | 0u))) + (unsigned)(st10.f1))));
      i29 = (unsigned)(((unsigned)(3067154580u) << ((unsigned)(((unsigned)((~((unsigned)(((unsigned)(st10.f1) % ((unsigned)(st9.f2) | 1u))) | 0u))) ^ (unsigned)(((unsigned)(st9.f1) >> ((unsigned)(((unsigned)(i25) + (unsigned)(256960255u))) & 31u))))) & 31u))) & 0xffffffffu;
    }
  }
  if ((unsigned)(((unsigned)((-((unsigned)(((unsigned)(((unsigned)(4179248097u) << ((unsigned)(st10.f0) & 31u))) + (unsigned)(4252766948u))) | 0u))) * (unsigned)(((unsigned)(u8) * (unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) << ((unsigned)(((unsigned)((unsigned)(s3)) ^ cs)) & 31u))) + (unsigned)(((unsigned)(u7) ^ (unsigned)(1897770496u))))))))) & 1u) {
    u8 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(2718246163u) / ((unsigned)(st10.f0) | 1u))) + (unsigned)(((unsigned)((unsigned)(s2)) - (unsigned)(3688564534u))))) % ((unsigned)(92420357u) | 1u))) & (unsigned)(((unsigned)(((unsigned)(u6) + (unsigned)(((unsigned)(st10.f2) >> ((unsigned)(1656541192u) & 31u))))) + (unsigned)((unsigned)(s3)))))) & 0xffffffffu;
  } else {
    u5 = (unsigned)((-((unsigned)(u5) | 0u))) & 0xffffffffu;
    st9.f1 = (unsigned)(((unsigned)(2390291286u) / ((unsigned)((-((unsigned)(st9.f0) | 0u))) | 1u)));
    if ((unsigned)(((unsigned)(((unsigned)((((unsigned)(u7) & 1u) ? (unsigned)(((unsigned)(u6) | (unsigned)((unsigned)(s4)))) : (unsigned)(1387872990u))) * (unsigned)(3369428302u))) == ((unsigned)(((unsigned)((unsigned)(s2)) >> ((unsigned)(((unsigned)((unsigned)(s2)) << ((unsigned)(((unsigned)(2042184973u) + (unsigned)(st10.f0))) & 31u))) & 31u))) ^ cs))) & 1u) {
      cs = csmix(cs, (unsigned)(u8));
      st9.f2 = (unsigned)(306564368u);
      cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)(u5) & 1u) ? (unsigned)(((unsigned)(((unsigned)(177701563u) << ((unsigned)(u6) & 31u))) & (unsigned)((-((unsigned)(st9.f1) | 0u))))) : (unsigned)(((unsigned)(((unsigned)((unsigned)(s4)) - (unsigned)(u6))) + (unsigned)((unsigned)(s4)))))) & (unsigned)(((unsigned)(helper1(((unsigned)(u5) % ((unsigned)(st10.f2) | 1u)), 250878150u)) / ((unsigned)(((unsigned)(1323164807u) * (unsigned)((unsigned)(s2)))) | 1u))))));
    } else {
      st10.f1 = (unsigned)(((unsigned)(st9.f2) / ((unsigned)(u8) | 1u)));
    }
  }

  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  cs = csmix(cs, (unsigned)s4);
  cs = csmix(cs, st9.f0);
  cs = csmix(cs, st9.f1);
  cs = csmix(cs, st9.f2);
  cs = csmix(cs, st10.f0);
  cs = csmix(cs, st10.f1);
  cs = csmix(cs, st10.f2);
  printf("checksum=%08x\n", cs);
  return 0;
}
