/* Regression: STRD-immediate-spill wrote an array/struct initializer to the
 * wrong stack offset when FP was omitted and the scratch register was PUSHed.
 *
 * Verbatim differential-fuzz repro (gen_c.py seed=12057).  -O2 wrong, -O0/-O1/-Os
 * correct (tcc -O0 oracle = 7b181946).
 *
 * Pass:  tcc_gen_machine_try_strd_imm_spill (arm-thumb-gen.c), the codegen
 *        peephole that fuses two adjacent immediate stores to spill slots into
 *        one STRD.  Reached here for the `arr7[8] = {...}` initializer; the
 *        register pressure that exposes it is shaped by ssa:dce, so the bug is
 *        gated by several -fno-* knobs (dce/const-prop/loop-unroll/...).
 * Bug:   to materialize the two constants the helper acquires scratch registers
 *        via get_scratch_reg_with_save().  With FP omitted and no reserved
 *        scratch-save area, that PUSHes a register, lowering SP by 4.  The STRD
 *        destination is SP-relative, but the offset was computed against the
 *        un-pushed SP, so the pair landed 4 bytes below the intended slot.  The
 *        array was thus stored at the wrong offset and the later
 *        `for (k) cs = csmix(cs, arr7[k])` loop read stale data → wrong checksum.
 * Fix:   measure the SP-lowering pushes done while acquiring the scratch
 *        registers and fold that shift into the STRD offset (or fall back to
 *        per-element stores when it can't be encoded).
 *
 * Correct checksum is gcc -m32 -funsigned-char = 7b181946.
 */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=12057
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s1 = (char)(13566863u & 0xff);
  long s2 = (long)(906643207u & 0xffffffff);
  unsigned u3 = 4193856213u;
  unsigned u4 = 4073166841u;
  unsigned u5 = 1505477474u;
  unsigned u6 = 2530473448u;
  unsigned arr7[8] = { 599753291u, 1322141238u, 3370649982u, 2479163354u, 2725667982u, 3503452757u, 2239817443u, 1767309648u };

  cs = csmix(cs, (unsigned)(u5));
  u5 = (unsigned)((~((unsigned)(u6) | 0u))) & 0xffffffffu;
  u3 = (unsigned)(3891581434u) & 0xffffffffu;

  cs = csmix(cs, u3);
  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, (unsigned)s1);
  cs = csmix(cs, (unsigned)s2);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr7[k]);
  printf("checksum=%08x\n", cs);
  return 0;
}
