/* ptr fuzz seed 80958 (O2): tcc_ir_opt_ptr_store_load_fwd (Phase 6b) dropped a
 * live store as "redundant" because an intervening runtime-index LOAD_INDEXED
 * that could read it was not registered as a read of the pending store.
 *
 * Two stores hit arr[1] (`arr[u9&7]`, u9&7==1) in the loop body, straddling a
 * read `arr[i18&7]`.  After const_prop_tmp folded both store offsets to the
 * literal `+4`, local_alu_cse coalesced the two store addresses into one addr
 * vreg.  ptr_store_load_fwd caches a pending store keyed by that addr vreg and
 * NOPs the first store when a second store to the same vreg arrives with
 * !was_loaded.  The LOAD_INDEXED between them has an address-rvalue base (not
 * the cached addr vreg), so the src1.is_lval forwarding never marked the store
 * as read — yet when i18&7==1 that load reads arr[1], so the first store is
 * live and feeds the second store's value.  Dropping it corrupted the sum.
 *
 * Fixed by marking every pending store as loaded on a LOAD_INDEXED (same class
 * as the RSE runtime-base fix, agg_deep seed 36641).  tcc -O0 (== gcc
 * -m32 -funsigned-char) gives checksum=746444e0; -O2 gave 444296f3 pre-fix.
 */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=80958
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(pa);
  if ((unsigned)(((unsigned)(((unsigned)(1058801820u) + (unsigned)(831608210u))) + (unsigned)(110535600u))) & 1u) lr += (unsigned)(pb);
  if ((unsigned)(pb) & 1u) lr += (unsigned)((-((unsigned)((((unsigned)(3941540674u) & 1u) ? (unsigned)(pa) : (unsigned)(4270822565u))) | 0u)));
  lr = (unsigned)(pb);
  if ((unsigned)(((unsigned)(((unsigned)(pb) / ((unsigned)(1904303261u) | 1u))) << ((unsigned)((~((unsigned)(pa) | 0u))) & 31u))) & 1u) lr += (unsigned)(((unsigned)(pa) + (unsigned)(2855790761u)));
  return (unsigned)(((unsigned)(2504571269u) + (unsigned)(((unsigned)(((unsigned)(1785916099u) << ((unsigned)(pa) & 31u))) ^ (unsigned)(((unsigned)(4204121747u) & (unsigned)(2647665901u))))))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(((unsigned)((((unsigned)(pb) & 1u) ? (unsigned)(lr) : (unsigned)(3690203427u))) << ((unsigned)(helper1(1179695621u, 514892098u)) & 31u))) & 1u) lr += (unsigned)(((unsigned)(3031682109u) << ((unsigned)(((unsigned)(1974002793u) << ((unsigned)(1445902149u) & 31u))) & 31u)));
  lr = (unsigned)(lr);
  return (unsigned)(((unsigned)((((unsigned)(2876848677u) & 1u) ? (unsigned)(pb) : (unsigned)(3467661727u))) * (unsigned)(((unsigned)(pb) % ((unsigned)(3585077416u) | 1u))))) ^ lr;
}

static unsigned helper3(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(pb);
  lr = (unsigned)((~((unsigned)(((unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(pb) : (unsigned)(1319897413u))) ^ (unsigned)(((unsigned)(3414921882u) << ((unsigned)(lr) & 31u))))) | 0u)));
  return (unsigned)(((unsigned)(pb) <= ((unsigned)(2380486746u) ^ lr))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s4 = (char)(281027733u & 0xff);
  short s5 = (short)(1422005162u & 0xffff);
  unsigned u6 = 2423304120u;
  unsigned u7 = 1763042954u;
  unsigned u8 = 3196179133u;
  unsigned u9 = 316398353u;
  unsigned u10 = 447564453u;
  unsigned u11 = 3609427474u;
  unsigned arr12[8] = { 402144940u, 2456575713u, 2442771597u, 227793398u, 3504597421u, 862365724u, 3915675990u, 3429600946u };
  unsigned *p13 = &u6;
  unsigned *p14 = &arr12[((unsigned)(u6) & 7u)];
  unsigned *p15 = &u11;
  unsigned *p16 = &u6;
  struct S st17 = { 209770309u, 860792912u, 4231107367u };

  { unsigned g19 = 0u;
    while (g19 < 12u) {
      unsigned i18 = g19;
      cs = csmix(cs, i18);
      *p13 = (unsigned)(247392243u);
      cs = csmix(cs, *p16);
      *p16 = (unsigned)(((unsigned)(((unsigned)((unsigned)(s4)) >> ((unsigned)((((unsigned)(((unsigned)((*p14)) / ((unsigned)(arr12[((unsigned)(u9) & 7u)]) | 1u))) & 1u) ? (unsigned)((-((unsigned)(467759402u) | 0u))) : (unsigned)((unsigned)(s4)))) & 31u))) ^ (unsigned)(((unsigned)(((unsigned)((unsigned)(s5)) << ((unsigned)(((unsigned)(arr12[((unsigned)(u8) & 7u)]) << ((unsigned)((unsigned)(s4)) & 31u))) & 31u))) | (unsigned)(arr12[((unsigned)(u9) & 7u)])))));
      cs = csmix(cs, *p13);
      cs = csmix(cs, (unsigned)((~((unsigned)(((unsigned)(((unsigned)((-((unsigned)(2994108816u) | 0u))) <= ((unsigned)((-((unsigned)((unsigned)(s4)) | 0u))) ^ cs))) - (unsigned)(((unsigned)(((unsigned)((*p14)) % ((unsigned)(u8) | 1u))) / ((unsigned)(((unsigned)(3012602842u) == ((unsigned)((unsigned)(s5)) ^ cs))) | 1u))))) | 0u))));
      arr12[((unsigned)(u9) & 7u)] = (unsigned)(((unsigned)(u7) | (unsigned)((~((unsigned)(((unsigned)(((unsigned)(u8) / ((unsigned)(3501358136u) | 1u))) == ((unsigned)(((unsigned)(arr12[((unsigned)(2249608812u) & 7u)]) >> ((unsigned)(3561796348u) & 31u))) ^ cs))) | 0u)))));
      arr12[((unsigned)(u9) & 7u)] = (unsigned)(((unsigned)(st17.f1) % ((unsigned)(arr12[((unsigned)(i18) & 7u)]) | 1u)));
      *p13 = (unsigned)(helper1((-((unsigned)(u8) | 0u)), 2086846524u));
      cs = csmix(cs, *p16);
      *p16 = (unsigned)(3149779988u);
      cs = csmix(cs, *p13);
      g19++;
    }
  }
  { unsigned g21 = 0u;
    while (g21 < 1u) {
      unsigned i20 = g21;
      cs = csmix(cs, i20);
      u8 = (unsigned)(((unsigned)(((unsigned)((~((unsigned)(u6) | 0u))) >> ((unsigned)(arr12[((unsigned)(u9) & 7u)]) & 31u))) >> ((unsigned)(((unsigned)(((unsigned)(((unsigned)(4203654943u) % ((unsigned)(arr12[((unsigned)(2442129987u) & 7u)]) | 1u))) | (unsigned)(((unsigned)(i20) >= ((unsigned)(((unsigned)(i20) ^ cs)) ^ cs))))) % ((unsigned)(((unsigned)(arr12[((unsigned)(u7) & 7u)]) / ((unsigned)(helper3(st17.f1, (*p14))) | 1u))) | 1u))) & 31u))) & 0xffffffffu;
      g21++;
    }
  }

  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, u9);
  cs = csmix(cs, u10);
  cs = csmix(cs, u11);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, helper3(38177487u, cs));
  cs = csmix(cs, (unsigned)s4);
  cs = csmix(cs, (unsigned)s5);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr12[k]);
  cs = csmix(cs, st17.f0);
  cs = csmix(cs, st17.f1);
  cs = csmix(cs, st17.f2);
  cs = csmix(cs, *p13);
  cs = csmix(cs, *p14);
  cs = csmix(cs, *p15);
  cs = csmix(cs, *p16);
  printf("checksum=%08x\n", cs);
  return 0;
}
