/* ptr fuzz seed 85636 (O1): tcc_ir_opt_add_reassoc forwarded an address-taken
 * local's arithmetic def across an aliasing pointer store that redefined it.
 *
 * `u4` is address-taken (p6==p7==p8==&u4).  The body computes
 *   u4 = u3 + C;          // V4 = V3 + C1
 *   *p7 = ...;            // stores through &u4 -> redefines u4
 *   u3 = (C2 + u4) % ...; // reads the *post-store* u4
 * add_reassoc rewrote `u4 + C2` into `u3 + (C1+C2)` by forwarding the stale
 * `u4 = u3 + C1` def — its linear def lookup is blind to the pointer store that
 * overwrote u4's slot in between, so u3 was computed from u4's pre-store value.
 *
 * Fixed by bailing when the forwarded base (or the inner var it resolves to) is
 * an address-taken VAR and a memory-clobbering STORE/CALL sits in the gap.
 * tcc -O0 (== gcc -m32 -funsigned-char) gives checksum=73ca047b; -O1 gave
 * f5e6fe18 pre-fix.
 */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=85636
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s1 = (char)(653951121u & 0xff);
  int s2 = (int)(2039493324u & 0xffffffff);
  unsigned u3 = 1787031149u;
  unsigned u4 = 512231545u;
  unsigned *p5 = &u3;
  unsigned *p6 = &u4;
  unsigned *p7 = &u4;
  unsigned *p8 = &u4;

  if ((unsigned)(((unsigned)(((unsigned)(4242757300u) ^ (unsigned)((*p8)))) - (unsigned)(((unsigned)(((unsigned)(2899914199u) & (unsigned)(((unsigned)(2373459294u) | (unsigned)((unsigned)(s2)))))) - (unsigned)(((unsigned)(2614589965u) / ((unsigned)(((unsigned)(u4) & (unsigned)(((unsigned)(u4) ^ cs)))) | 1u))))))) & 1u) {
    cs = csmix(cs, (unsigned)((*p7)));
    *p5 = (unsigned)(u3);
    cs = csmix(cs, *p6);
    *p6 = (unsigned)(((unsigned)((((unsigned)(((unsigned)(((unsigned)(3734037608u) - (unsigned)(u3))) >> ((unsigned)(u4) & 31u))) & 1u) ? (unsigned)((-((unsigned)(1454003157u) | 0u))) : (unsigned)(u3))) ^ (unsigned)(u4)));
    cs = csmix(cs, *p5);
    if ((unsigned)(((unsigned)(((unsigned)(((unsigned)(2060466403u) - (unsigned)(((unsigned)(2104831021u) >> ((unsigned)((unsigned)(s2)) & 31u))))) >> ((unsigned)(((unsigned)(u4) / ((unsigned)((unsigned)(s2)) | 1u))) & 31u))) << ((unsigned)(u3) & 31u))) & 1u) {
      cs = csmix(cs, (unsigned)(((unsigned)((unsigned)(s2)) << ((unsigned)(((unsigned)((unsigned)(s2)) / ((unsigned)((~((unsigned)(((unsigned)(2936688656u) / ((unsigned)((*p8)) | 1u))) | 0u))) | 1u))) & 31u))));
      *p5 = (unsigned)(1760155976u);
      cs = csmix(cs, *p5);
    } else {
      u3 = (unsigned)(((unsigned)((((unsigned)((unsigned)(s2)) & 1u) ? (unsigned)(u3) : (unsigned)(((unsigned)(u3) ^ cs)))) << ((unsigned)((~((unsigned)(((unsigned)(u3) >> ((unsigned)(((unsigned)((unsigned)(s2)) ^ (unsigned)((*p5)))) & 31u))) | 0u))) & 31u))) & 0xffffffffu;
      *p6 = (unsigned)(2908155779u);
      cs = csmix(cs, *p8);
      *p8 = (unsigned)(((unsigned)(u4) << ((unsigned)(((unsigned)(((unsigned)(((unsigned)((*p7)) + (unsigned)((*p6)))) + (unsigned)(((unsigned)(u3) | (unsigned)(2864517283u))))) << ((unsigned)(((unsigned)(((unsigned)(u4) * (unsigned)(101340459u))) + (unsigned)(((unsigned)((unsigned)(s2)) >> ((unsigned)((*p8)) & 31u))))) & 31u))) & 31u)));
      cs = csmix(cs, *p6);
      cs = csmix(cs, (unsigned)((-((unsigned)(2700823131u) | 0u))));
      *p7 = (unsigned)(((unsigned)(((unsigned)(u4) != ((unsigned)((unsigned)(s1)) ^ cs))) >> ((unsigned)(((unsigned)(((unsigned)(((unsigned)(u4) << ((unsigned)(3963207383u) & 31u))) % ((unsigned)((~((unsigned)(1653886673u) | 0u))) | 1u))) * (unsigned)((*p7)))) & 31u)));
      cs = csmix(cs, *p7);
      *p6 = (unsigned)((*p7));
      cs = csmix(cs, *p5);
      *p5 = (unsigned)(u3);
      cs = csmix(cs, *p6);
    }
    if ((unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u3) + (unsigned)(2846969372u))) ^ (unsigned)((unsigned)(s2)))) - (unsigned)(((unsigned)(u3) >= ((unsigned)(1278085743u) ^ cs))))) << ((unsigned)((*p7)) & 31u))) & 1u) {
      cs = csmix(cs, (unsigned)(((unsigned)((~((unsigned)(((unsigned)(((unsigned)(u4) * (unsigned)(u3))) & (unsigned)(((unsigned)(2356367794u) - (unsigned)((unsigned)(s2)))))) | 0u))) >> ((unsigned)(((unsigned)(((unsigned)((((unsigned)(1877026690u) & 1u) ? (unsigned)((*p8)) : (unsigned)((unsigned)(s1)))) * (unsigned)(((unsigned)(3293422451u) % ((unsigned)(u3) | 1u))))) * (unsigned)(((unsigned)(u3) ^ (unsigned)(3026274815u))))) & 31u))));
      u4 = (unsigned)(((unsigned)(((unsigned)(640731528u) << ((unsigned)(((unsigned)(((unsigned)(u4) / ((unsigned)(4121222523u) | 1u))) <= ((unsigned)(((unsigned)(1245898640u) - (unsigned)((unsigned)(s2)))) ^ cs))) & 31u))) - (unsigned)(((unsigned)(((unsigned)(((unsigned)(1541195922u) % ((unsigned)(u3) | 1u))) >> ((unsigned)(((unsigned)(1561143686u) >> ((unsigned)(u3) & 31u))) & 31u))) / ((unsigned)(u3) | 1u))))) & 0xffffffffu;
      *p5 = (unsigned)(((unsigned)((*p8)) << ((unsigned)((((unsigned)(u4) & 1u) ? (unsigned)(((unsigned)(((unsigned)((unsigned)(s1)) % ((unsigned)(1603597006u) | 1u))) >> ((unsigned)((*p8)) & 31u))) : (unsigned)(u3))) & 31u)));
      cs = csmix(cs, *p7);
      *p7 = (unsigned)((unsigned)(s1));
      cs = csmix(cs, *p5);
      u4 = (unsigned)(((unsigned)(u3) + (unsigned)(3522660809u))) & 0xffffffffu;
      *p6 = (unsigned)(u3);
      cs = csmix(cs, *p7);
      *p7 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) / ((unsigned)(1152282702u) | 1u))) << ((unsigned)(((unsigned)((*p6)) - (unsigned)((unsigned)(s1)))) & 31u))) << ((unsigned)(((unsigned)((-((unsigned)(u3) | 0u))) / ((unsigned)(((unsigned)((*p6)) * (unsigned)(956694406u))) | 1u))) & 31u))) & (unsigned)(((unsigned)(2779395541u) >> ((unsigned)(4061612774u) & 31u)))));
      cs = csmix(cs, *p6);
      u3 = (unsigned)(((unsigned)(((unsigned)(3608456867u) + (unsigned)(u4))) % ((unsigned)(((unsigned)((((unsigned)(((unsigned)(1776699099u) >> ((unsigned)((*p7)) & 31u))) & 1u) ? (unsigned)(((unsigned)(u4) | (unsigned)(((unsigned)(u4) ^ cs)))) : (unsigned)(u3))) - (unsigned)(((unsigned)(((unsigned)((unsigned)(s1)) >> ((unsigned)(2470996770u) & 31u))) & (unsigned)(1363593268u))))) | 1u))) & 0xffffffffu;
    } else {
      u3 = (unsigned)(((unsigned)((-((unsigned)((-((unsigned)((unsigned)(s1)) | 0u))) | 0u))) * (unsigned)(((unsigned)(((unsigned)((unsigned)(s1)) % ((unsigned)(((unsigned)(u4) / ((unsigned)((*p8)) | 1u))) | 1u))) % ((unsigned)(((unsigned)(((unsigned)(u4) / ((unsigned)(1086898266u) | 1u))) | (unsigned)(u3))) | 1u))))) & 0xffffffffu;
      u4 = (unsigned)(u4) & 0xffffffffu;
      *p5 = (unsigned)(((unsigned)(((unsigned)((-((unsigned)((-((unsigned)((unsigned)(s2)) | 0u))) | 0u))) << ((unsigned)((((unsigned)(u4) & 1u) ? (unsigned)(((unsigned)((*p7)) & (unsigned)(u4))) : (unsigned)((~((unsigned)((unsigned)(s2)) | 0u))))) & 31u))) << ((unsigned)((~((unsigned)(((unsigned)(((unsigned)((*p7)) >> ((unsigned)(((unsigned)((*p7)) ^ cs)) & 31u))) << ((unsigned)(((unsigned)(1539449658u) - (unsigned)(u3))) & 31u))) | 0u))) & 31u)));
      cs = csmix(cs, *p8);
      *p8 = (unsigned)(621749826u);
      cs = csmix(cs, *p5);
    }
  } else {
    u3 = (unsigned)((-((unsigned)(((unsigned)((*p5)) & (unsigned)(((unsigned)(u3) * (unsigned)((((unsigned)(1759294459u) & 1u) ? (unsigned)(u3) : (unsigned)((*p6)))))))) | 0u))) & 0xffffffffu;
    cs = csmix(cs, (unsigned)(((unsigned)(1040352607u) * (unsigned)(u3))));
    for (unsigned g10 = 0u; g10 < 8u; g10++) {
      unsigned i9 = g10;
      cs = csmix(cs, i9);
      *p6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)((((unsigned)(3868166311u) & 1u) ? (unsigned)(i9) : (unsigned)((*p8)))) + (unsigned)((unsigned)(s2)))) + (unsigned)(((unsigned)(((unsigned)(u3) % ((unsigned)((unsigned)(s1)) | 1u))) ^ (unsigned)(((unsigned)(3534450958u) | (unsigned)((unsigned)(s1)))))))) + (unsigned)((unsigned)(s2))));
      cs = csmix(cs, *p8);
      *p8 = (unsigned)(((unsigned)((~((unsigned)(((unsigned)(((unsigned)(i9) % ((unsigned)(1711170115u) | 1u))) ^ (unsigned)(i9))) | 0u))) >> ((unsigned)((*p6)) & 31u)));
      cs = csmix(cs, *p6);
      *p5 = (unsigned)(u4);
      cs = csmix(cs, *p5);
      *p6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(1666914403u) | (unsigned)(u4))) | (unsigned)(((unsigned)(u4) | (unsigned)((*p8)))))) & (unsigned)(((unsigned)(((unsigned)((*p5)) + (unsigned)((unsigned)(s2)))) ^ (unsigned)(((unsigned)(1471418186u) + (unsigned)(u4))))))) * (unsigned)(((unsigned)(i9) >> ((unsigned)((((unsigned)(((unsigned)(u3) == ((unsigned)(4110938762u) ^ cs))) & 1u) ? (unsigned)((~((unsigned)(211981910u) | 0u))) : (unsigned)(((unsigned)(3454871441u) % ((unsigned)((unsigned)(s2)) | 1u))))) & 31u)))));
      cs = csmix(cs, *p5);
      *p5 = (unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) % ((unsigned)((unsigned)(s1)) | 1u))) >> ((unsigned)(3552412604u) & 31u))) >> ((unsigned)(u3) & 31u)));
      cs = csmix(cs, *p6);
      *p6 = (unsigned)(u3);
      cs = csmix(cs, *p8);
      *p8 = (unsigned)(((unsigned)(((unsigned)(((unsigned)((-((unsigned)((unsigned)(s1)) | 0u))) / ((unsigned)(((unsigned)(2527360363u) ^ (unsigned)(u4))) | 1u))) & (unsigned)(((unsigned)(((unsigned)(3358765818u) + (unsigned)((*p7)))) ^ (unsigned)(3282919492u))))) % ((unsigned)(((unsigned)((*p6)) ^ (unsigned)(2134119238u))) | 1u)));
      cs = csmix(cs, *p6);
    }
    for (unsigned g12 = 0u; g12 < 12u; g12++) {
      unsigned i11 = g12;
      cs = csmix(cs, i11);
      cs = csmix(cs, (unsigned)(((unsigned)(578309052u) * (unsigned)(((unsigned)(3526131994u) % ((unsigned)(((unsigned)(((unsigned)(328721495u) * (unsigned)(u3))) ^ (unsigned)(1924461704u))) | 1u))))));
      *p8 = (unsigned)(((unsigned)(i11) * (unsigned)(((unsigned)((*p5)) * (unsigned)(((unsigned)(i11) / ((unsigned)(((unsigned)((*p8)) & (unsigned)(u3))) | 1u)))))));
      cs = csmix(cs, *p8);
      *p6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)((((unsigned)(i11) & 1u) ? (unsigned)(u4) : (unsigned)(1428441779u))) == ((unsigned)(((unsigned)(2724088222u) < ((unsigned)((*p6)) ^ cs))) ^ cs))) * (unsigned)(((unsigned)(u4) <= ((unsigned)(3450224822u) ^ cs))))) ^ (unsigned)(3042373490u)));
      cs = csmix(cs, *p5);
      *p5 = (unsigned)(((unsigned)(1860417174u) + (unsigned)(u3)));
      cs = csmix(cs, *p6);
      u3 = (unsigned)(((unsigned)((*p5)) + (unsigned)(i11))) & 0xffffffffu;
      cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)((unsigned)(s1)) & 1u) ? (unsigned)(3965984511u) : (unsigned)(2634369975u))) & (unsigned)((-((unsigned)(2719654870u) | 0u))))));
    }
    *p8 = (unsigned)((unsigned)(s2));
    cs = csmix(cs, *p8);
    for (unsigned g14 = 0u; g14 < 10u; g14++) {
      unsigned i13 = g14;
      cs = csmix(cs, i13);
      i13 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(u4) > ((unsigned)((-((unsigned)(2086330058u) | 0u))) ^ cs))) / ((unsigned)(3999093648u) | 1u))) - (unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) & (unsigned)((*p7)))) <= ((unsigned)(((unsigned)(1113284984u) * (unsigned)(3222729191u))) ^ cs))) | (unsigned)(3438944692u))))) & 0xffffffffu;
      u4 = (unsigned)(((unsigned)(1086400078u) << ((unsigned)(((unsigned)((((unsigned)(((unsigned)(1523239089u) % ((unsigned)((unsigned)(s1)) | 1u))) & 1u) ? (unsigned)(i13) : (unsigned)((unsigned)(s2)))) ^ (unsigned)(((unsigned)(((unsigned)(953371218u) + (unsigned)((unsigned)(s1)))) % ((unsigned)(4252494105u) | 1u))))) & 31u))) & 0xffffffffu;
      cs = csmix(cs, (unsigned)((unsigned)(s2)));
      cs = csmix(cs, (unsigned)(i13));
      cs = csmix(cs, (unsigned)(u3));
      *p5 = (unsigned)((*p5));
      cs = csmix(cs, *p7);
      *p7 = (unsigned)((((unsigned)((~((unsigned)(((unsigned)(((unsigned)(3109403867u) == ((unsigned)(u4) ^ cs))) << ((unsigned)(((unsigned)(i13) & (unsigned)(1380583614u))) & 31u))) | 0u))) & 1u) ? (unsigned)((-((unsigned)((*p8)) | 0u))) : (unsigned)((*p7))));
      cs = csmix(cs, *p5);
    }
  }

  cs = csmix(cs, u3);
  cs = csmix(cs, u4);
  cs = csmix(cs, (unsigned)s1);
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, *p5);
  cs = csmix(cs, *p6);
  cs = csmix(cs, *p7);
  cs = csmix(cs, *p8);
  printf("checksum=%08x\n", cs);
  return 0;
}
