/* longlong fuzz seed 111125 (vs-gcc): opt_bitfield's masked-extract fold
 * treated a multi-def TEMP as single-assignment.  tcc_ir_find_defining_instruction
 * found only the nearest `T<-0` arm, so bf_possible_bits under-reported possible
 * bits and folded `(T | C) & 1` to `T`.
 *
 * Fixed by requiring exactly one TEMP definition before deriving possible bits.
 */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=111125
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(((unsigned)(pa) % ((unsigned)(1188232971u) | 1u))) & 1u) lr += (unsigned)(221276448u);
  if ((unsigned)(((unsigned)((((unsigned)(lr) & 1u) ? (unsigned)(lr) : (unsigned)(3771520027u))) << ((unsigned)(1353748446u) & 31u))) & 1u) lr += (unsigned)(pa);
  if ((unsigned)(((unsigned)((((unsigned)(3077251987u) & 1u) ? (unsigned)(pa) : (unsigned)(2090868137u))) % ((unsigned)(3814509996u) | 1u))) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(pa) * (unsigned)(3259417368u))) << ((unsigned)(((unsigned)(4154272647u) | (unsigned)(2158280949u))) & 31u)));
  return (unsigned)((((unsigned)(pb) & 1u) ? (unsigned)(((unsigned)(((unsigned)(lr) % ((unsigned)(pa) | 1u))) / ((unsigned)(((unsigned)(pb) ^ (unsigned)(3777816325u))) | 1u))) : (unsigned)(2459458455u))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(2425929199u) * (unsigned)(pb))) ^ (unsigned)(3900569496u))) - (unsigned)(4137136711u)));
  lr = (unsigned)(lr);
  lr = (unsigned)(pa);
  return (unsigned)(((unsigned)(3266645802u) << ((unsigned)(((unsigned)(lr) % ((unsigned)(884305343u) | 1u))) & 31u))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s3 = (char)(1361366444u & 0xff);
  unsigned u4 = 379862388u;
  unsigned u5 = 214438894u;
  unsigned u6 = 4224983793u;
  unsigned u7 = 3501249503u;
  unsigned long long q8 = (((unsigned long long)(u5)) << 32) | (unsigned long long)(u6);
  unsigned long long q9 = (((unsigned long long)(u7)) << 32) | (unsigned long long)(u6);
  unsigned long long q10 = (((unsigned long long)(u5)) << 32) | (unsigned long long)(u4);
  struct S st11 = { 1093818297u, 1856211891u, 318942648u };
  struct S st12 = { 598798571u, 583421978u, 2155638530u };

  cs = csmix(cs, (unsigned)(q10) ^ (unsigned)(q10 >> 32));
  cs = csmix(cs, (unsigned)(((unsigned)(st11.f1) - (unsigned)((unsigned)(s3)))));
  { unsigned g14 = 0u;
    while (g14 < 5u) {
      unsigned i13 = g14;
      cs = csmix(cs, i13);
      cs = csmix(cs, (unsigned)(q10) ^ (unsigned)(q10 >> 32));
      { unsigned g16 = 0u;
        while (g16 < 8u) {
          unsigned i15 = g16;
          cs = csmix(cs, i15);
          cs = csmix(cs, ((q9) <= (((q9) ^ (unsigned long long)(cs)))) ? 1u : 0u);
          cs = csmix(cs, (unsigned)((((unsigned)(((unsigned)((((unsigned)(helper2(u5, st11.f1)) & 1u) ? (unsigned)(((unsigned)((unsigned)(s3)) & (unsigned)(417196113u))) : (unsigned)(2615412422u))) | (unsigned)((~((unsigned)(u7) | 0u))))) & 1u) ? (unsigned)((unsigned)(s3)) : (unsigned)(st12.f1))));
          cs = csmix(cs, (unsigned)(q9) ^ (unsigned)(q9 >> 32));
          cs = csmix(cs, ((q9) == (q8)) ? 1u : 0u);
          cs = csmix(cs, (unsigned)(st12.f2));
          g16++;
        }
      }
      q9 = (((unsigned long long)(unsigned)(st12.f1))) ^ (((unsigned long long)(unsigned)(((unsigned)(1759680324u) * (unsigned)(helper2(2751660196u, 2059967881u))))));
      g14++;
    }
  }
  q10 = (3091755861268279748ull) >> ((unsigned)(3074193600u) & 63u);
  cs = csmix(cs, (unsigned)(((unsigned)(2898068913u) * (unsigned)(((unsigned)(((unsigned)(((unsigned)(2772412806u) + (unsigned)(1229413450u))) | (unsigned)(2902504136u))) >= ((unsigned)((~((unsigned)(2324529010u) | 0u))) ^ cs))))));
  for (unsigned g18 = 0u; g18 < 12u; g18++) {
    unsigned i17 = g18;
    cs = csmix(cs, i17);
    u4 = (unsigned)(((unsigned)((((unsigned)(((unsigned)((unsigned)(s3)) < ((unsigned)((((unsigned)(1778234531u) & 1u) ? (unsigned)(i17) : (unsigned)(u7))) ^ cs))) & 1u) ? (unsigned)(helper2(((unsigned)(u4) / ((unsigned)((unsigned)(s3)) | 1u)), ((unsigned)(u6) ^ (unsigned)(st11.f0)))) : (unsigned)(st11.f1))) ^ (unsigned)((((unsigned)(u4) & 1u) ? (unsigned)(helper2(((unsigned)(u5) >> ((unsigned)(st12.f1) & 31u)), u6)) : (unsigned)((unsigned)(s3)))))) & 0xffffffffu;
    q9 = (q10) * (q9);
    { unsigned g20 = 0u;
      while (g20 < 3u) {
        unsigned i19 = g20;
        cs = csmix(cs, i19);
        cs = csmix(cs, ((q10) == (q9)) ? 1u : 0u);
        st11.f1 = (unsigned)((~((unsigned)(((unsigned)(((unsigned)(((unsigned)(st12.f2) << ((unsigned)(1068895522u) & 31u))) * (unsigned)((unsigned)(s3)))) * (unsigned)(u7))) | 0u)));
        cs = csmix(cs, ((q9) > (((q9) ^ (unsigned long long)(cs)))) ? 1u : 0u);
        cs = csmix(cs, ((q8) <= (((q8) ^ (unsigned long long)(cs)))) ? 1u : 0u);
        g20++;
      }
    }
  }

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, (unsigned)(q8) ^ (unsigned)(q8 >> 32));
  cs = csmix(cs, (unsigned)(q9) ^ (unsigned)(q9 >> 32));
  cs = csmix(cs, (unsigned)(q10) ^ (unsigned)(q10 >> 32));
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, (unsigned)s3);
  cs = csmix(cs, st11.f0);
  cs = csmix(cs, st11.f1);
  cs = csmix(cs, st11.f2);
  cs = csmix(cs, st12.f0);
  cs = csmix(cs, st12.f1);
  cs = csmix(cs, st12.f2);
  printf("checksum=%08x\n", cs);
  return 0;
}
