/* Regression for fuzz varargs seed 142915: store-load forwarding must not
 * fold across va_list updates inside a variadic function body.
 *
 * AUTO-GENERATED by tests/fuzz/gen_c.py  seed=142915
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>
#include <stdarg.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

/* varargs profile: sum n int args (acc unsigned -> defined wraparound). */
static unsigned vsum(unsigned n, ...)
{
  va_list ap; unsigned acc = 0u; unsigned i;
  va_start(ap, n);
  for (i = 0u; i < n; i++) acc += (unsigned)va_arg(ap, int);
  va_end(ap);
  return acc;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(3936556597u) + (unsigned)(((unsigned)((((unsigned)(516584292u) & 1u) ? (unsigned)(lr) : (unsigned)(273409793u))) + (unsigned)(((unsigned)(pb) - (unsigned)(4275225463u)))))));
  lr = (unsigned)((-((unsigned)(((unsigned)(((unsigned)(lr) * (unsigned)(((unsigned)(lr) ^ lr)))) * (unsigned)(4082613370u))) | 0u)));
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(1206164863u) >> ((unsigned)(pb) & 31u))) % ((unsigned)(((unsigned)(pb) * (unsigned)(((unsigned)(pb) ^ lr)))) | 1u))) >> ((unsigned)(pa) & 31u)));
  lr = (unsigned)(pa);
  return (unsigned)(pa) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(lr);
  lr = (unsigned)(pa);
  lr = (unsigned)((-((unsigned)(3399903425u) | 0u)));
  return (unsigned)(3891705504u) ^ lr;
}

static unsigned helper3(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)((-((unsigned)(pa) | 0u)));
  if ((unsigned)(((unsigned)(pb) & (unsigned)((((unsigned)(690049830u) & 1u) ? (unsigned)(4237978307u) : (unsigned)(3295277598u))))) & 1u) lr += (unsigned)((~((unsigned)(((unsigned)(pb) >> ((unsigned)(pa) & 31u))) | 0u)));
  lr = (unsigned)(3030147890u);
  lr = (unsigned)(lr);
  if ((unsigned)(705039733u) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(lr) * (unsigned)(((unsigned)(lr) ^ lr)))) ^ (unsigned)(((unsigned)(lr) / ((unsigned)(((unsigned)(lr) ^ lr)) | 1u)))));
  return (unsigned)(((unsigned)(helper2(helper2(lr, pa), 3326492726u)) | (unsigned)(((unsigned)(pa) >> ((unsigned)(((unsigned)(1310956082u) <= ((unsigned)(708929567u) ^ lr))) & 31u))))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s4 = (char)(783636915u & 0xff);
  unsigned u5 = 3047807241u;
  unsigned u6 = 810666916u;
  unsigned u7 = 1552044509u;

  { unsigned g9 = 0u;
    while (g9 < 3u) {
      unsigned i8 = g9;
      cs = csmix(cs, i8);
      for (unsigned g11 = 0u; g11 < 4u; g11++) {
        unsigned i10 = g11;
        cs = csmix(cs, i10);
        cs = csmix(cs, (unsigned)(i10));
        cs = csmix(cs, (unsigned)(3078229198u));
        cs = csmix(cs, (unsigned)((unsigned)(s4)));
        cs = csmix(cs, vsum(1u, (int)(((unsigned)((~((unsigned)(((unsigned)(((unsigned)(681406666u) + (unsigned)(2609989866u))) / ((unsigned)(1542173673u) | 1u))) | 0u))) / ((unsigned)(((unsigned)((((unsigned)(helper3(i8, (unsigned)(s4))) & 1u) ? (unsigned)(((unsigned)(645381282u) << ((unsigned)((unsigned)(s4)) & 31u))) : (unsigned)((~((unsigned)(u7) | 0u))))) * (unsigned)(((unsigned)(((unsigned)(u7) <= ((unsigned)(i10) ^ cs))) >> ((unsigned)((unsigned)(s4)) & 31u))))) | 1u)))));
      }
      cs = csmix(cs, vsum(7u, (int)(2968406105u), (int)(u7), (int)(1455319221u), (int)(i8), (int)(u6), (int)(((unsigned)((unsigned)(s4)) ^ (unsigned)(((unsigned)(3640764432u) * (unsigned)(((unsigned)(u6) % ((unsigned)(((unsigned)(u7) << ((unsigned)(488746963u) & 31u))) | 1u))))))), (int)(((unsigned)(4089911176u) * (unsigned)(((unsigned)(i8) / ((unsigned)((~((unsigned)(((unsigned)(1667616864u) + (unsigned)(i8))) | 0u))) | 1u)))))));
      cs = csmix(cs, vsum(1u, (int)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(2644607003u) | (unsigned)(2662398291u))) <= ((unsigned)(((unsigned)(315266976u) - (unsigned)((unsigned)(s4)))) ^ cs))) % ((unsigned)(((unsigned)(((unsigned)(u5) << ((unsigned)((unsigned)(s4)) & 31u))) | (unsigned)(u5))) | 1u))) & (unsigned)(((unsigned)(3624496739u) == ((unsigned)(helper1(u6, ((unsigned)(699235538u) & (unsigned)(547820224u)))) ^ cs)))))));
      for (unsigned g13 = 0u; g13 < 1u; g13++) {
        unsigned i12 = g13;
        cs = csmix(cs, i12);
        u5 = (unsigned)(1223770065u) & 0xffffffffu;
        cs = csmix(cs, (unsigned)(u7));
        cs = csmix(cs, vsum(7u, (int)(((unsigned)(3553522500u) | (unsigned)((((unsigned)(((unsigned)(((unsigned)(1359970241u) & (unsigned)(u6))) & (unsigned)((~((unsigned)(u5) | 0u))))) & 1u) ? (unsigned)(64015644u) : (unsigned)(((unsigned)(((unsigned)(u5) & (unsigned)(i8))) > ((unsigned)(((unsigned)((unsigned)(s4)) + (unsigned)(((unsigned)((unsigned)(s4)) ^ cs)))) ^ cs))))))), (int)(((unsigned)(1537330966u) ^ (unsigned)(((unsigned)(4221387078u) % ((unsigned)(helper1(((unsigned)(i12) * (unsigned)(2754702761u)), ((unsigned)(u5) >> ((unsigned)(u7) & 31u)))) | 1u))))), (int)(((unsigned)((~((unsigned)(((unsigned)(((unsigned)(3412090573u) % ((unsigned)((unsigned)(s4)) | 1u))) | (unsigned)(((unsigned)(2954538318u) * (unsigned)(i8))))) | 0u))) - (unsigned)(((unsigned)(i8) ^ (unsigned)((-((unsigned)(266419502u) | 0u))))))), (int)(((unsigned)(2911433938u) << ((unsigned)(((unsigned)(3075843697u) * (unsigned)((-((unsigned)(u5) | 0u))))) & 31u))), (int)(u5), (int)(((unsigned)(((unsigned)(948993313u) << ((unsigned)(((unsigned)(i8) ^ (unsigned)(((unsigned)(192537706u) & (unsigned)((unsigned)(s4)))))) & 31u))) << ((unsigned)(u7) & 31u))), (int)(((unsigned)(4147097121u) ^ (unsigned)((((unsigned)(u6) & 1u) ? (unsigned)(i12) : (unsigned)(helper3(((unsigned)(3312260984u) << ((unsigned)(u6) & 31u)), (-((unsigned)(u7) | 0u))))))))));
        u5 = (unsigned)((((unsigned)((unsigned)(s4)) & 1u) ? (unsigned)((unsigned)(s4)) : (unsigned)(1003681446u))) & 0xffffffffu;
        u7 = (unsigned)(((unsigned)(((unsigned)(i12) / ((unsigned)(((unsigned)(u5) + (unsigned)(3848708223u))) | 1u))) ^ (unsigned)(3863838576u))) & 0xffffffffu;
        cs = csmix(cs, vsum(8u, (int)(u7), (int)(4293890497u), (int)(((unsigned)((-((unsigned)(u6) | 0u))) | (unsigned)(((unsigned)(helper1(((unsigned)(3283517020u) ^ (unsigned)((unsigned)(s4))), 1971053679u)) - (unsigned)(3044055606u))))), (int)((unsigned)(s4)), (int)(u7), (int)(242440894u), (int)(helper3((~((unsigned)(112957252u) | 0u)), 2247993516u)), (int)(i8)));
      }
      g9++;
    }
  }
  u6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u6) - (unsigned)(u5))) | (unsigned)(2428661431u))) & (unsigned)((((unsigned)(((unsigned)(u7) ^ (unsigned)(u5))) & 1u) ? (unsigned)(((unsigned)(3132932973u) / ((unsigned)(u7) | 1u))) : (unsigned)(helper1(u7, 248585504u)))))) > ((unsigned)((-((unsigned)((((unsigned)(u7) & 1u) ? (unsigned)(((unsigned)(1730418893u) & (unsigned)(3725119733u))) : (unsigned)(((unsigned)((unsigned)(s4)) / ((unsigned)(u6) | 1u))))) | 0u))) ^ cs))) & 0xffffffffu;
  cs = csmix(cs, vsum(7u, (int)(((unsigned)(((unsigned)((unsigned)(s4)) | (unsigned)(1111951544u))) ^ (unsigned)((~((unsigned)(((unsigned)(u5) & (unsigned)(2175752619u))) | 0u))))), (int)(((unsigned)(2369549334u) >> ((unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) << ((unsigned)(1074393181u) & 31u))) & (unsigned)((unsigned)(s4)))) != ((unsigned)((unsigned)(s4)) ^ cs))) & 31u))), (int)(u7), (int)(((unsigned)(((unsigned)(u7) >> ((unsigned)(((unsigned)(((unsigned)(3241702209u) * (unsigned)(u7))) * (unsigned)(((unsigned)((unsigned)(s4)) << ((unsigned)(u7) & 31u))))) & 31u))) & (unsigned)(((unsigned)((((unsigned)(((unsigned)((unsigned)(s4)) - (unsigned)(u7))) & 1u) ? (unsigned)(((unsigned)(4017107430u) == ((unsigned)(u5) ^ cs))) : (unsigned)(u5))) | (unsigned)(((unsigned)(u7) / ((unsigned)((((unsigned)((unsigned)(s4)) & 1u) ? (unsigned)(754367675u) : (unsigned)(u7))) | 1u))))))), (int)(((unsigned)((-((unsigned)(((unsigned)((~((unsigned)(3239041727u) | 0u))) != ((unsigned)(((unsigned)(u5) > ((unsigned)(u7) ^ cs))) ^ cs))) | 0u))) - (unsigned)((unsigned)(s4)))), (int)(((unsigned)(u6) | (unsigned)(80754664u))), (int)(((unsigned)(u6) * (unsigned)(4076313405u)))));
  cs = csmix(cs, vsum(0u));

  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, helper3(38177487u, cs));
  cs = csmix(cs, vsum(2u, 1, (int)cs));
  cs = csmix(cs, (unsigned)s4);
  printf("checksum=%08x\n", cs);
  return 0;
}
