/* switch fuzz seed 219754 (O2 HardFault): `A * *P` where src2 is a dereferenced
 * pointer.  arm-thumb-gen.c mach_regonly_binop_mop (MUL/DIV/UDIV) pre-excluded
 * src2 from src1's scratch pool with a guard `src2->kind==MACH_OP_REG &&
 * !src2->needs_deref` -- the `!needs_deref` clause dropped the DEREF case, so at
 * high register pressure mach_ensure_in_reg(src1) picked src2's pointer register
 * as scratch, clobbering &arr[i] before the step-3 `ldr rN,[ptr]` read it -> a
 * data word was dereferenced as an address -> precise bus fault.  Fixed by
 * dropping the `!src2->needs_deref` clause in mach_regonly_binop_mop and
 * mach_mod_mop, matching the correct data-processing guard.  tcc -O0 (== gcc
 * -m32 -funsigned-char) gives checksum=725e7e84; -O2 HardFaulted pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=219754
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s1 = (short)(1554236052u & 0xffff);
  char s2 = (char)(107417211u & 0xff);
  char s3 = (char)(1780595580u & 0xff);
  unsigned u4 = 212709863u;
  unsigned u5 = 4044466919u;
  unsigned u6 = 543381425u;
  unsigned u7 = 3629285939u;
  unsigned u8 = 2323641852u;
  unsigned u9 = 2899170364u;
  unsigned arr10[8] = { 1576156107u, 16601730u, 2904170973u, 2102238857u, 1064454657u, 3521915323u, 3240422464u, 1702158043u };

  u6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(u8) / ((unsigned)(2037840758u) | 1u))) <= ((unsigned)(u7) ^ cs))) ^ (unsigned)((~((unsigned)(3572962877u) | 0u))))) & 0xffffffffu;
  for (unsigned g12 = 0u; g12 < 5u; g12++) {
    unsigned i11 = g12;
    cs = csmix(cs, i11);
    if ((unsigned)((unsigned)(s3)) & 1u) {
      cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)(((unsigned)(arr10[((unsigned)(1460087415u) & 7u)]) & (unsigned)(((unsigned)(92717095u) * (unsigned)(u7))))) & 1u) ? (unsigned)((-((unsigned)(((unsigned)(arr10[((unsigned)(u9) & 7u)]) % ((unsigned)(393279825u) | 1u))) | 0u))) : (unsigned)(((unsigned)(((unsigned)((unsigned)(s1)) / ((unsigned)(u9) | 1u))) - (unsigned)(((unsigned)(arr10[((unsigned)(u6) & 7u)]) ^ (unsigned)(arr10[((unsigned)(3794893037u) & 7u)]))))))) ^ (unsigned)((-((unsigned)(((unsigned)(((unsigned)((unsigned)(s1)) > ((unsigned)((unsigned)(s3)) ^ cs))) << ((unsigned)(((unsigned)((unsigned)(s3)) + (unsigned)(u4))) & 31u))) | 0u))))));
      cs = csmix(cs, (unsigned)(1611043520u));
    } else {
      u5 = (unsigned)(u9) & 0xffffffffu;
    }
    u9 = (unsigned)((((unsigned)(1647866810u) & 1u) ? (unsigned)(u8) : (unsigned)(((unsigned)((-((unsigned)((~((unsigned)(arr10[((unsigned)(3979290186u) & 7u)]) | 0u))) | 0u))) & (unsigned)(u4))))) & 0xffffffffu;
  }
  if ((unsigned)(2346200958u) & 1u) {
    { unsigned g14 = 0u;
      while (g14 < 1u) {
        unsigned i13 = g14;
        cs = csmix(cs, i13);
        cs = csmix(cs, (unsigned)(((unsigned)(3647074668u) * (unsigned)(i13))));
        arr10[((unsigned)(i13) & 7u)] = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(u9))) | (unsigned)(u7))) ^ (unsigned)(u6))) ^ (unsigned)((((unsigned)(((unsigned)(i13) * (unsigned)(((unsigned)(u6) <= ((unsigned)((unsigned)(s3)) ^ cs))))) & 1u) ? (unsigned)(u7) : (unsigned)(544812334u)))));
        u6 = (unsigned)(arr10[((unsigned)(2832086013u) & 7u)]) & 0xffffffffu;
        g14++;
      }
    }
  }
  { unsigned g15 = (unsigned)(u4) & 1u;
    if (g15) goto L1;
    cs = csmix(cs, (unsigned)((unsigned)(s1)));
    cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(2681272961u) >> ((unsigned)(2268580407u) & 31u))) <= ((unsigned)(u8) ^ cs))) + (unsigned)((unsigned)(s1)))) & (unsigned)(u9))));
  L1:;
    cs = csmix(cs, 33u); }
  cs = csmix(cs, (unsigned)(u5));
  { unsigned g17 = 0u;
    while (g17 < 1u) {
      unsigned i16 = g17;
      cs = csmix(cs, i16);
      { unsigned g18 = (unsigned)((~((unsigned)(((unsigned)(arr10[((unsigned)(u7) & 7u)]) << ((unsigned)(((unsigned)((~((unsigned)(1041637454u) | 0u))) / ((unsigned)(((unsigned)(u6) ^ (unsigned)((unsigned)(s2)))) | 1u))) & 31u))) | 0u))) & 1u;
        if (g18) goto L2;
        cs = csmix(cs, (unsigned)(764496033u));
        cs = csmix(cs, (unsigned)(i16));
      L2:;
        cs = csmix(cs, 98u); }
      if ((unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u6) * (unsigned)(arr10[((unsigned)(u7) & 7u)]))) > ((unsigned)(arr10[((unsigned)(u6) & 7u)]) ^ cs))) >> ((unsigned)(((unsigned)(((unsigned)(u8) | (unsigned)(3051480135u))) >> ((unsigned)(((unsigned)(i16) | (unsigned)(arr10[((unsigned)(u6) & 7u)]))) & 31u))) & 31u))) ^ (unsigned)(2806844655u))) & 1u) {
        cs = csmix(cs, (unsigned)(arr10[((unsigned)(u7) & 7u)]));
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)((~((unsigned)((unsigned)(s3)) | 0u))) << ((unsigned)(u4) & 31u))) & (unsigned)(((unsigned)(((unsigned)(arr10[((unsigned)(u9) & 7u)]) / ((unsigned)(u6) | 1u))) <= ((unsigned)((((unsigned)((unsigned)(s2)) & 1u) ? (unsigned)(3004276076u) : (unsigned)(678001738u))) ^ cs))))) ^ (unsigned)(2293357330u))));
        u4 = (unsigned)(u9) & 0xffffffffu;
      }
      arr10[((unsigned)(u9) & 7u)] = (unsigned)(arr10[((unsigned)(1359414510u) & 7u)]);
      g17++;
    }
  }

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, u9);
  cs = csmix(cs, (unsigned)s1);
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr10[k]);
  printf("checksum=%08x\n", cs);
  return 0;
}
