/* ptr fuzz seed 291660 (O2 HardFault): same MUL-deref-src2 clobber as seed
 * 219754 (see 333_fuzz_mul_deref_src2_clobber.c), reached through the ptr
 * profile.  mach_regonly_binop_mop dereferenced src1's register instead of the
 * live src2 pointer register.  tcc -O0 (== gcc -m32 -funsigned-char) gives
 * checksum=3b6cb2db; -O2 HardFaulted pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=291660
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(lr);
  lr = (unsigned)(2961436512u);
  lr = (unsigned)(pb);
  lr = (unsigned)(((unsigned)((-((unsigned)(lr) | 0u))) % ((unsigned)((~((unsigned)(1769666500u) | 0u))) | 1u)));
  lr = (unsigned)(1285565425u);
  return (unsigned)(748549499u) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s2 = (short)(451177638u & 0xffff);
  int s3 = (int)(1308856002u & 0xffffffff);
  unsigned u4 = 3003308942u;
  unsigned u5 = 738284729u;
  unsigned u6 = 3690552168u;
  unsigned u7 = 4105741804u;
  unsigned u8 = 595920836u;
  unsigned arr9[8] = { 2211790856u, 1794844284u, 1222408913u, 2996887823u, 22523937u, 1120981960u, 1348847596u, 3550713015u };
  unsigned *p10 = &u4;
  unsigned *p11 = &u8;
  unsigned *p12 = &u4;
  struct S st13 = { 2170927311u, 2307472935u, 1184699006u };
  struct S st14 = { 2074093564u, 2897649896u, 365198131u };

  *p11 = (unsigned)((((unsigned)(((unsigned)(u5) | (unsigned)(((unsigned)(((unsigned)(2943853060u) - (unsigned)(3601478513u))) << ((unsigned)((~((unsigned)((unsigned)(s3)) | 0u))) & 31u))))) & 1u) ? (unsigned)(((unsigned)(((unsigned)((((unsigned)(u5) & 1u) ? (unsigned)((*p12)) : (unsigned)(u5))) % ((unsigned)(((unsigned)(arr9[((unsigned)(u7) & 7u)]) - (unsigned)(st14.f2))) | 1u))) * (unsigned)(((unsigned)((unsigned)(s3)) ^ (unsigned)(u6))))) : (unsigned)(((unsigned)(3029471283u) / ((unsigned)(((unsigned)(3730540403u) >> ((unsigned)(2150776772u) & 31u))) | 1u)))));
  cs = csmix(cs, *p12);
  *p12 = (unsigned)(((unsigned)(st14.f1) & (unsigned)((~((unsigned)(st13.f0) | 0u)))));
  cs = csmix(cs, *p11);
  { unsigned g16 = 0u;
    while (g16 < 1u) {
      unsigned i15 = g16;
      cs = csmix(cs, i15);
      cs = csmix(cs, (unsigned)((-((unsigned)((unsigned)(s2)) | 0u))));
      { unsigned g18 = 0u;
        while (g18 < 10u) {
          unsigned i17 = g18;
          cs = csmix(cs, i17);
          arr9[((unsigned)(4175774320u) & 7u)] = (unsigned)((~((unsigned)(3911971296u) | 0u)));
          st14.f1 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(arr9[((unsigned)(u8) & 7u)]) & (unsigned)((*p11)))) % ((unsigned)(((unsigned)(2157861229u) << ((unsigned)(2459290114u) & 31u))) | 1u))) * (unsigned)(helper1(((unsigned)((*p11)) * (unsigned)(arr9[((unsigned)(u4) & 7u)])), ((unsigned)(u6) | (unsigned)(2443493676u)))))) + (unsigned)(((unsigned)(((unsigned)((-((unsigned)(arr9[((unsigned)(u6) & 7u)]) | 0u))) * (unsigned)((-((unsigned)(arr9[((unsigned)(i17) & 7u)]) | 0u))))) == ((unsigned)(helper1((*p10), u8)) ^ cs)))));
          *p10 = (unsigned)(((unsigned)((~((unsigned)(u6) | 0u))) | (unsigned)((~((unsigned)(((unsigned)((unsigned)(s3)) | (unsigned)(((unsigned)(st13.f1) >> ((unsigned)(u8) & 31u))))) | 0u)))));
          cs = csmix(cs, *p10);
          u7 = (unsigned)(((unsigned)((-((unsigned)(((unsigned)(((unsigned)(235837805u) * (unsigned)(u5))) != ((unsigned)((((unsigned)(u4) & 1u) ? (unsigned)((*p10)) : (unsigned)(3562739174u))) ^ cs))) | 0u))) ^ (unsigned)(((unsigned)(((unsigned)(((unsigned)((*p12)) > ((unsigned)(4158320498u) ^ cs))) | (unsigned)(1133584078u))) + (unsigned)(st13.f0))))) & 0xffffffffu;
          cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(u6) >= ((unsigned)(arr9[((unsigned)(u4) & 7u)]) ^ cs))) ^ (unsigned)(((unsigned)((unsigned)(s3)) << ((unsigned)(((unsigned)(st14.f2) % ((unsigned)(u4) | 1u))) & 31u))))) >> ((unsigned)(arr9[((unsigned)(i17) & 7u)]) & 31u))));
          *p10 = (unsigned)(helper1(arr9[((unsigned)(u6) & 7u)], arr9[((unsigned)(3587418140u) & 7u)]));
          cs = csmix(cs, *p11);
          *p11 = (unsigned)((*p10));
          cs = csmix(cs, *p10);
          g18++;
        }
      }
      *p10 = (unsigned)(st13.f0);
      cs = csmix(cs, *p11);
      *p11 = (unsigned)(((unsigned)(st13.f1) ^ (unsigned)(helper1(i15, ((unsigned)(arr9[((unsigned)(i15) & 7u)]) * (unsigned)(u5))))));
      cs = csmix(cs, *p10);
      *p11 = (unsigned)(((unsigned)((~((unsigned)(((unsigned)((unsigned)(s2)) << ((unsigned)(1728920166u) & 31u))) | 0u))) / ((unsigned)((-((unsigned)((~((unsigned)(((unsigned)(2125425626u) % ((unsigned)(2078518722u) | 1u))) | 0u))) | 0u))) | 1u)));
      cs = csmix(cs, *p11);
      { unsigned g20 = 0u;
        while (g20 < 5u) {
          unsigned i19 = g20;
          cs = csmix(cs, i19);
          arr9[((unsigned)(i15) & 7u)] = (unsigned)(i19);
          u5 = (unsigned)(((unsigned)(((unsigned)((-((unsigned)(((unsigned)(u5) >> ((unsigned)(803274173u) & 31u))) | 0u))) >> ((unsigned)(st13.f0) & 31u))) & (unsigned)(((unsigned)(((unsigned)(((unsigned)(arr9[((unsigned)(u4) & 7u)]) >> ((unsigned)((unsigned)(s2)) & 31u))) >> ((unsigned)(1619898455u) & 31u))) & (unsigned)(((unsigned)(174856158u) * (unsigned)(((unsigned)((unsigned)(s2)) / ((unsigned)(st14.f0) | 1u))))))))) & 0xffffffffu;
          u6 = (unsigned)((*p11)) & 0xffffffffu;
          u8 = (unsigned)(((unsigned)(u7) * (unsigned)((*p11)))) & 0xffffffffu;
          i19 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(484326535u) % ((unsigned)(2365447724u) | 1u))) << ((unsigned)((~((unsigned)(u4) | 0u))) & 31u))) << ((unsigned)((unsigned)(s2)) & 31u))) * (unsigned)(i19))) & 0xffffffffu;
          g20++;
        }
      }
      g16++;
    }
  }
  *p10 = (unsigned)(((unsigned)(arr9[((unsigned)(u5) & 7u)]) | (unsigned)(((unsigned)(u5) << ((unsigned)((((unsigned)(((unsigned)(u7) != ((unsigned)(903598816u) ^ cs))) & 1u) ? (unsigned)((~((unsigned)(2589692733u) | 0u))) : (unsigned)(((unsigned)(st13.f1) + (unsigned)((unsigned)(s2)))))) & 31u)))));
  cs = csmix(cs, *p10);

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr9[k]);
  cs = csmix(cs, st13.f0);
  cs = csmix(cs, st13.f1);
  cs = csmix(cs, st13.f2);
  cs = csmix(cs, st14.f0);
  cs = csmix(cs, st14.f1);
  cs = csmix(cs, st14.f2);
  cs = csmix(cs, *p10);
  cs = csmix(cs, *p11);
  cs = csmix(cs, *p12);
  printf("checksum=%08x\n", cs);
  return 0;
}
