/* ptr fuzz seed 260222 (O2 wrong value): store-load-forwarding's LEA-map ADD
 * propagation (ir/opt_memory.c) turned `T = *P + C` (a deref VALUE plus a const)
 * into `lea_map[T] = lea_map[P].offset + C`, treating a loaded value as an
 * address.  A hash-mix `*p10 + 3459224220` inherited arr6's stack offset (-32),
 * producing the garbage "offset" -835743108; the `*p7 = 1783444611` store was
 * then tracked at that bogus offset and the later `*p9` read (&u5, where u5 is
 * BOTH address-taken and the array index) matched it -> u5 folded to arr6[7]'s
 * value.  Only manifests after link-time inlining of csmix into main.  Fixed by
 * requiring !is_lval on the LEA-carrying operand in BOTH the pre-scan and the
 * dynamic ADD-map updates (a deref value is not an address).  tcc -O0 (== gcc
 * -m32 -funsigned-char) gives checksum=b5dcec58; -O2 gave d9386398 pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=260222
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(pb) & 1u) lr += (unsigned)(261025570u);
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(pa) ^ (unsigned)(541563845u))) >> ((unsigned)(((unsigned)(pb) << ((unsigned)(548618702u) & 31u))) & 31u))) != ((unsigned)(((unsigned)((~((unsigned)(1171273975u) | 0u))) / ((unsigned)(((unsigned)(2296501071u) << ((unsigned)(3461476736u) & 31u))) | 1u))) ^ lr)));
  if ((unsigned)(((unsigned)(pa) | (unsigned)(((unsigned)(pb) - (unsigned)(2138534151u))))) & 1u) lr += (unsigned)(((unsigned)(pa) & (unsigned)(684736483u)));
  if ((unsigned)(((unsigned)(((unsigned)(1263391758u) != ((unsigned)(2914040408u) ^ lr))) * (unsigned)(pa))) & 1u) lr += (unsigned)(2206861032u);
  lr = (unsigned)(pa);
  return (unsigned)(((unsigned)(((unsigned)(((unsigned)(946490757u) ^ (unsigned)(lr))) ^ (unsigned)(pa))) / ((unsigned)(((unsigned)(3738343702u) ^ (unsigned)(pa))) | 1u))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s2 = (char)(673529530u & 0xff);
  short s3 = (short)(1130198030u & 0xffff);
  unsigned u4 = 3124958997u;
  unsigned u5 = 135160591u;
  unsigned arr6[8] = { 2012092403u, 3391555743u, 2164929287u, 3244560488u, 506972995u, 955287672u, 3787765038u, 409486444u };
  unsigned *p7 = &arr6[((unsigned)(u5) & 7u)];
  unsigned *p8 = &arr6[0u];
  unsigned *p9 = &u5;
  unsigned *p10 = &arr6[0u];

  *p8 = (unsigned)(((unsigned)(((unsigned)(u5) + (unsigned)(((unsigned)(((unsigned)(217549109u) % ((unsigned)(3810257765u) | 1u))) >> ((unsigned)(((unsigned)(4016028139u) - (unsigned)(617871023u))) & 31u))))) | (unsigned)(671379744u)));
  cs = csmix(cs, *p8);
  for (unsigned g12 = 0u; g12 < 4u; g12++) {
    unsigned i11 = g12;
    cs = csmix(cs, i11);
    cs = csmix(cs, (unsigned)((unsigned)(s2)));
    u4 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) >> ((unsigned)((*p9)) & 31u))) & (unsigned)(((unsigned)(3363682833u) ^ (unsigned)(arr6[((unsigned)(u4) & 7u)]))))) >> ((unsigned)((~((unsigned)(((unsigned)(1863552899u) ^ (unsigned)(4149378185u))) | 0u))) & 31u))) ^ (unsigned)(helper1(((unsigned)(helper1(3331613443u, arr6[((unsigned)(i11) & 7u)])) * (unsigned)(((unsigned)((unsigned)(s2)) + (unsigned)((*p10))))), ((unsigned)(((unsigned)(arr6[((unsigned)(3393637676u) & 7u)]) + (unsigned)(3645702520u))) | (unsigned)((-((unsigned)(i11) | 0u)))))))) & 0xffffffffu;
    for (unsigned g14 = 0u; g14 < 10u; g14++) {
      unsigned i13 = g14;
      cs = csmix(cs, i13);
      i13 = (unsigned)(i11) & 0xffffffffu;
    }
  }
  for (unsigned g16 = 0u; g16 < 9u; g16++) {
    unsigned i15 = g16;
    cs = csmix(cs, i15);
    i15 = (unsigned)(((unsigned)(((unsigned)((*p7)) ^ (unsigned)(((unsigned)(((unsigned)(arr6[((unsigned)(2509930700u) & 7u)]) / ((unsigned)((unsigned)(s3)) | 1u))) - (unsigned)((-((unsigned)((*p7)) | 0u))))))) & (unsigned)(((unsigned)(3740551790u) >> ((unsigned)((((unsigned)((unsigned)(s3)) & 1u) ? (unsigned)((-((unsigned)((unsigned)(s3)) | 0u))) : (unsigned)((-((unsigned)((*p7)) | 0u))))) & 31u))))) & 0xffffffffu;
    if ((unsigned)(((unsigned)((unsigned)(s2)) % ((unsigned)((~((unsigned)(helper1(((unsigned)(1526955317u) / ((unsigned)(arr6[((unsigned)(4256415121u) & 7u)]) | 1u)), 1139000358u)) | 0u))) | 1u))) & 1u) {
      cs = csmix(cs, (unsigned)(((unsigned)((*p7)) & (unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) >> ((unsigned)((*p8)) & 31u))) | (unsigned)(1125332005u))) >= ((unsigned)(((unsigned)(u4) > ((unsigned)(((unsigned)((unsigned)(s3)) % ((unsigned)(3534584023u) | 1u))) ^ cs))) ^ cs))))));
      *p7 = (unsigned)(((unsigned)((-((unsigned)(u5) | 0u))) ^ (unsigned)((unsigned)(s2))));
      cs = csmix(cs, *p7);
    } else {
      u5 = (unsigned)(4226300433u) & 0xffffffffu;
      u5 = (unsigned)(((unsigned)(u5) - (unsigned)((-((unsigned)((unsigned)(s3)) | 0u))))) & 0xffffffffu;
    }
    u4 = (unsigned)((*p9)) & 0xffffffffu;
    if ((unsigned)((*p8)) & 1u) {
      cs = csmix(cs, (unsigned)(((unsigned)(3943618747u) * (unsigned)(u5))));
      *p10 = (unsigned)(((unsigned)(3459224220u) + (unsigned)((*p10))));
      cs = csmix(cs, *p7);
      *p7 = (unsigned)(1783444611u);
      cs = csmix(cs, *p10);
      cs = csmix(cs, (unsigned)((unsigned)(s2)));
      *p9 = (unsigned)(helper1(((unsigned)(helper1(((unsigned)((*p9)) << ((unsigned)((unsigned)(s3)) & 31u)), ((unsigned)((unsigned)(s3)) + (unsigned)(2892712326u)))) | (unsigned)((((unsigned)((unsigned)(s3)) & 1u) ? (unsigned)((*p7)) : (unsigned)(i15)))), ((unsigned)(arr6[((unsigned)(u5) & 7u)]) < ((unsigned)(((unsigned)(((unsigned)(4236692509u) & (unsigned)(arr6[((unsigned)(353422527u) & 7u)]))) & (unsigned)(((unsigned)((unsigned)(s3)) >> ((unsigned)(4135021722u) & 31u))))) ^ cs))));
      cs = csmix(cs, *p9);
    }
  }
  cs = csmix(cs, (unsigned)((unsigned)(s3)));

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr6[k]);
  cs = csmix(cs, *p7);
  cs = csmix(cs, *p8);
  cs = csmix(cs, *p9);
  cs = csmix(cs, *p10);
  printf("checksum=%08x\n", cs);
  return 0;
}
