/* varargs fuzz seed 293237 (O1/O2 HardFault): ir/regalloc.c ra_build_assign_hints
 * coalesced a deref-load ASSIGN `T15 = *T2` by hinting dest T15 and source
 * pointer T2 onto the same register.  T2 (= &arr8[4]) had to stay live for a
 * DEFERRED variadic-call `PARAM *T2` deref materialized at the call (r0-r3 set
 * just before the branch), but T15's def overwrote it with the loaded value ->
 * the call dereferenced a data word as a pointer.  Fixed with
 * `if (d.is_lval || s.is_lval) continue;` -- a deref ASSIGN is not a register
 * copy.  tcc -O0 (== gcc -m32 -funsigned-char) gives checksum=50605a3a; -O1/-O2
 * HardFaulted pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=293237
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>
#include <stdarg.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

/* varargs profile: sum n int args (acc unsigned -> defined wraparound). */
static unsigned vsum(unsigned n, ...)
{
  va_list ap; unsigned acc = 0u; unsigned i;
  va_start(ap, n);
  for (i = 0u; i < n; i++) acc += (unsigned)va_arg(ap, int);
  va_end(ap);
  return acc;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(3407884974u) % ((unsigned)((~((unsigned)((((unsigned)(359280042u) & 1u) ? (unsigned)(pa) : (unsigned)(34451049u))) | 0u))) | 1u)));
  if ((unsigned)(pb) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(3977735397u) + (unsigned)(1498136193u))) & (unsigned)(((unsigned)(3462099013u) - (unsigned)(pb)))));
  return (unsigned)(pb) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  int s2 = (int)(1454711096u & 0xffffffff);
  long s3 = (long)(329393088u & 0xffffffff);
  char s4 = (char)(1621648704u & 0xff);
  unsigned u5 = 3916696333u;
  unsigned u6 = 4174515100u;
  unsigned u7 = 2250696305u;
  unsigned arr8[8] = { 1118103131u, 1449744921u, 3996406347u, 901619920u, 3847788483u, 2986874124u, 1555316482u, 683461718u };
  struct S st9 = { 1671935951u, 2053523396u, 2615311295u };

  cs = csmix(cs, vsum(8u, (int)(arr8[((unsigned)(u6) & 7u)]), (int)(((unsigned)(arr8[((unsigned)(u6) & 7u)]) / ((unsigned)(((unsigned)(((unsigned)(((unsigned)(u7) > ((unsigned)((unsigned)(s4)) ^ cs))) << ((unsigned)(st9.f2) & 31u))) << ((unsigned)((-((unsigned)(279725809u) | 0u))) & 31u))) | 1u))), (int)(1143616404u), (int)((~((unsigned)(((unsigned)((((unsigned)(((unsigned)(u5) << ((unsigned)(st9.f1) & 31u))) & 1u) ? (unsigned)(((unsigned)(arr8[((unsigned)(u6) & 7u)]) >> ((unsigned)(3103810062u) & 31u))) : (unsigned)(((unsigned)(4062864740u) - (unsigned)(u6))))) % ((unsigned)(arr8[((unsigned)(u5) & 7u)]) | 1u))) | 0u))), (int)((~((unsigned)(3151544979u) | 0u))), (int)(((unsigned)(((unsigned)(((unsigned)(helper1(u6, u6)) / ((unsigned)((-((unsigned)(1715591623u) | 0u))) | 1u))) * (unsigned)((-((unsigned)(((unsigned)(u6) << ((unsigned)(2965509577u) & 31u))) | 0u))))) >> ((unsigned)((unsigned)(s2)) & 31u))), (int)(((unsigned)(((unsigned)(u6) / ((unsigned)(((unsigned)(u6) ^ cs)) | 1u))) + (unsigned)(helper1(u6, 1084648646u)))), (int)(((unsigned)(((unsigned)(helper1(((unsigned)(1429200947u) >> ((unsigned)(arr8[((unsigned)(u6) & 7u)]) & 31u)), ((unsigned)(st9.f0) - (unsigned)((unsigned)(s4))))) | (unsigned)((unsigned)(s3)))) & (unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) << ((unsigned)(3082552481u) & 31u))) % ((unsigned)((((unsigned)(u7) & 1u) ? (unsigned)(u5) : (unsigned)(st9.f0))) | 1u))) * (unsigned)(((unsigned)(((unsigned)(u5) % ((unsigned)(arr8[((unsigned)(1523261858u) & 7u)]) | 1u))) | (unsigned)((-((unsigned)((unsigned)(s4)) | 0u)))))))))));
  cs = csmix(cs, vsum(0u));
  cs = csmix(cs, (unsigned)(((unsigned)(u7) == ((unsigned)(((unsigned)((((unsigned)(helper1(2653610178u, u7)) & 1u) ? (unsigned)(((unsigned)(st9.f0) >> ((unsigned)(st9.f1) & 31u))) : (unsigned)(2984543622u))) * (unsigned)(((unsigned)(((unsigned)(1158160524u) & (unsigned)(u7))) % ((unsigned)(arr8[((unsigned)(u6) & 7u)]) | 1u))))) ^ cs))));
  { unsigned g11 = 0u;
    while (g11 < 1u) {
      unsigned i10 = g11;
      cs = csmix(cs, i10);
      arr8[((unsigned)(u7) & 7u)] = (unsigned)(((unsigned)(((unsigned)(1974647226u) - (unsigned)(((unsigned)(helper1(1470493910u, 2308748634u)) << ((unsigned)(((unsigned)((unsigned)(s2)) * (unsigned)(((unsigned)((unsigned)(s2)) ^ cs)))) & 31u))))) / ((unsigned)(((unsigned)(u6) * (unsigned)(((unsigned)(((unsigned)(st9.f2) >> ((unsigned)(((unsigned)(st9.f2) ^ cs)) & 31u))) - (unsigned)(1817176480u))))) | 1u)));
      g11++;
    }
  }
  u7 = (unsigned)(st9.f1) & 0xffffffffu;
  u5 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u6) ^ (unsigned)(3213171015u))) + (unsigned)((~((unsigned)(1783817498u) | 0u))))) ^ (unsigned)(helper1(((unsigned)(arr8[((unsigned)(u7) & 7u)]) >> ((unsigned)(arr8[((unsigned)(1438105280u) & 7u)]) & 31u)), ((unsigned)(u5) << ((unsigned)(((unsigned)(u5) ^ cs)) & 31u)))))) / ((unsigned)(((unsigned)(((unsigned)(((unsigned)(2121627590u) ^ (unsigned)(arr8[((unsigned)(u6) & 7u)]))) == ((unsigned)((((unsigned)(u7) & 1u) ? (unsigned)(3269479809u) : (unsigned)((unsigned)(s2)))) ^ cs))) >> ((unsigned)(((unsigned)((~((unsigned)(arr8[((unsigned)(4047551276u) & 7u)]) | 0u))) >> ((unsigned)(2917142265u) & 31u))) & 31u))) | 1u))) & 0xffffffffu;

  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, vsum(2u, 1, (int)cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  cs = csmix(cs, (unsigned)s4);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr8[k]);
  cs = csmix(cs, st9.f0);
  cs = csmix(cs, st9.f1);
  cs = csmix(cs, st9.f2);
  printf("checksum=%08x\n", cs);
  return 0;
}
