/* float fuzz seed 206597 (vs-gcc; tcc was self-consistent across -O0/-O1/-O2):
 * a 1-ULP double-rounding bug in compile-time FP constant folding.  tccgen.c
 * gen_opif() computed VT_DOUBLE `+ - * /` folds in 80-bit `long double` then
 * narrowed to double at the store -- rounding twice (64-bit mantissa, then
 * 53-bit).  gcc and tcc's own runtime softfloat round once and are correct.
 * Fixed by folding VT_DOUBLE in double / VT_FLOAT in float (native precision;
 * the widen-back is exact, so the store is an identity round-trip).  Correct
 * (gcc-matching) checksum=346ddf59; tcc gave 1cb7fcc1 pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=206597
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>
#include <string.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

static unsigned fbits_d(double d){ unsigned u[2]; memcpy(u, &d, sizeof u); return csmix(u[0], u[1]); }
static unsigned fbits_f(float f){ unsigned u; memcpy(&u, &f, sizeof u); return u; }


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(pb) ^ (unsigned)(1880813446u))) << ((unsigned)(3512010928u) & 31u))) + (unsigned)((-((unsigned)((~((unsigned)(lr) | 0u))) | 0u)))));
  lr = (unsigned)(((unsigned)(pa) * (unsigned)(pb)));
  lr = (unsigned)(pa);
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(4290421569u) * (unsigned)(pa))) ^ (unsigned)(((unsigned)(pb) * (unsigned)(((unsigned)(pb) ^ lr)))))) >> ((unsigned)(pa) & 31u)));
  return (unsigned)(((unsigned)(((unsigned)(278547316u) ^ (unsigned)(((unsigned)(3730500561u) * (unsigned)(pb))))) - (unsigned)(((unsigned)((-((unsigned)(lr) | 0u))) * (unsigned)(2305963983u))))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(((unsigned)(4122029795u) % ((unsigned)(((unsigned)(lr) > ((unsigned)(pb) ^ lr))) | 1u))) & 1u) lr += (unsigned)(lr);
  if ((unsigned)(((unsigned)(7424401u) * (unsigned)((((unsigned)(916045379u) & 1u) ? (unsigned)(pa) : (unsigned)(lr))))) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(lr) * (unsigned)(pb))) + (unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(pa) : (unsigned)(1596906022u)))));
  lr = (unsigned)(((unsigned)(((unsigned)(pa) + (unsigned)((((unsigned)(pb) & 1u) ? (unsigned)(pb) : (unsigned)(3901107571u))))) & (unsigned)(((unsigned)(((unsigned)(pa) - (unsigned)(lr))) % ((unsigned)(((unsigned)(pb) / ((unsigned)(876554919u) | 1u))) | 1u)))));
  lr = (unsigned)(131894532u);
  lr = (unsigned)(((unsigned)(lr) / ((unsigned)(pb) | 1u)));
  return (unsigned)(((unsigned)(3220142103u) & (unsigned)(532823773u))) ^ lr;
}

static unsigned helper3(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(pb) & 1u) lr += (unsigned)(3296351868u);
  if ((unsigned)(((unsigned)(((unsigned)(lr) * (unsigned)(736482301u))) % ((unsigned)(((unsigned)(pa) == ((unsigned)(4005614544u) ^ lr))) | 1u))) & 1u) lr += (unsigned)(((unsigned)(pa) | (unsigned)(((unsigned)(lr) * (unsigned)(282920203u)))));
  lr = (unsigned)(((unsigned)((~((unsigned)(((unsigned)(pa) - (unsigned)(((unsigned)(pa) ^ lr)))) | 0u))) < ((unsigned)(((unsigned)(633708590u) + (unsigned)(((unsigned)(pa) * (unsigned)(lr))))) ^ lr)));
  lr = (unsigned)(((unsigned)(1082007637u) == ((unsigned)(pa) ^ lr)));
  lr = (unsigned)(((unsigned)((((unsigned)(((unsigned)(2746110140u) << ((unsigned)(1811809428u) & 31u))) & 1u) ? (unsigned)(pa) : (unsigned)(((unsigned)(pb) & (unsigned)(((unsigned)(pb) ^ lr)))))) ^ (unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(((unsigned)(pb) >> ((unsigned)(pa) & 31u))) : (unsigned)(((unsigned)(1835363342u) * (unsigned)(pb)))))));
  return (unsigned)(helper1(((unsigned)((((unsigned)(pa) & 1u) ? (unsigned)(2618844269u) : (unsigned)(pb))) | (unsigned)((((unsigned)(2884277729u) & 1u) ? (unsigned)(pb) : (unsigned)(((unsigned)(pb) ^ lr))))), 3014218710u)) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  long s4 = (long)(985445834u & 0xffffffff);
  unsigned u5 = 65715064u;
  unsigned u6 = 1245121834u;
  unsigned u7 = 1088075716u;
  unsigned u8 = 699200208u;
  unsigned arr9[8] = { 1276237473u, 1776128400u, 1387467432u, 1156846751u, 2842654417u, 3393527960u, 3852919967u, 1831152884u };
  unsigned arr10[8] = { 772209105u, 434583932u, 2905680261u, 1097084299u, 1318454986u, 1310017982u, 3616020604u, 3039290252u };
  struct S st11 = { 3017375218u, 150979695u, 2665832918u };
  struct S st12 = { 3683034094u, 2385267031u, 1244780432u };
  double f13 = 0x1.8f17bc0000000p+11;
  float f14 = -0x1.dae6440000000p+25f;
  double f15 = 0x1.8eb2d80000000p+23;

  u5 = (unsigned)((~((unsigned)(4059208950u) | 0u))) & 0xffffffffu;
  st12.f2 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(1770105686u) >> ((unsigned)(1809311404u) & 31u))) << ((unsigned)(((unsigned)(arr9[((unsigned)(1251993700u) & 7u)]) | (unsigned)(u5))) & 31u))) ^ (unsigned)(((unsigned)(((unsigned)(arr10[((unsigned)(u6) & 7u)]) << ((unsigned)(u5) & 31u))) > ((unsigned)((~((unsigned)(1438905410u) | 0u))) ^ cs))))) << ((unsigned)(661949167u) & 31u)));
  cs = csmix(cs, (unsigned)(((unsigned)(helper2(((unsigned)(((unsigned)(arr9[((unsigned)(1665097089u) & 7u)]) ^ (unsigned)(134626541u))) >> ((unsigned)(helper1(st11.f1, st11.f0)) & 31u)), ((unsigned)(((unsigned)(arr10[((unsigned)(u8) & 7u)]) | (unsigned)((unsigned)(s4)))) >> ((unsigned)(helper2(arr9[((unsigned)(u8) & 7u)], u8)) & 31u)))) * (unsigned)(st11.f2))));
  for (unsigned g17 = 0u; g17 < 1u; g17++) {
    unsigned i16 = g17;
    cs = csmix(cs, i16);
    u5 = (unsigned)(arr10[((unsigned)(u5) & 7u)]) & 0xffffffffu;
    cs = csmix(cs, ((-0x1.991c5e0000000p+27) <= ((double)((unsigned)(u8)))) ? 1u : 0u);
    st12.f1 = (unsigned)((((unsigned)(2651243824u) & 1u) ? (unsigned)(((unsigned)(u7) & (unsigned)(st12.f1))) : (unsigned)((~((unsigned)((~((unsigned)(((unsigned)(u6) & (unsigned)(4211739142u))) | 0u))) | 0u)))));
    if ((unsigned)(((unsigned)(helper3(((unsigned)((~((unsigned)(225576032u) | 0u))) << ((unsigned)(arr10[((unsigned)(7985427u) & 7u)]) & 31u)), ((unsigned)((unsigned)(s4)) > ((unsigned)(((unsigned)(st11.f1) >> ((unsigned)(2443517219u) & 31u))) ^ cs)))) % ((unsigned)(4034281722u) | 1u))) & 1u) {
      u8 = (unsigned)(arr9[((unsigned)(u6) & 7u)]) & 0xffffffffu;
      st11.f0 = (unsigned)(((unsigned)(((unsigned)(3381745172u) * (unsigned)(u7))) & (unsigned)(helper1(arr9[((unsigned)(744264929u) & 7u)], arr9[((unsigned)(2723345694u) & 7u)]))));
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)((~((unsigned)((unsigned)(s4)) | 0u))) ^ (unsigned)(584695503u))) & (unsigned)((unsigned)(s4)))));
      st12.f2 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(3173496518u) - (unsigned)(arr10[((unsigned)(952815091u) & 7u)]))) | (unsigned)(helper3(26606730u, u5)))) % ((unsigned)(((unsigned)((unsigned)(s4)) / ((unsigned)(((unsigned)(((unsigned)(u8) ^ (unsigned)((unsigned)(s4)))) ^ (unsigned)(((unsigned)(2842561083u) * (unsigned)(u7))))) | 1u))) | 1u)));
      st11.f0 = (unsigned)(st12.f2);
    }
    for (unsigned g19 = 0u; g19 < 1u; g19++) {
      unsigned i18 = g19;
      cs = csmix(cs, i18);
      cs = csmix(cs, (((double)(f15)) <= ((double)(f13))) ? 1u : 0u);
      arr10[((unsigned)(u5) & 7u)] = (unsigned)(479239522u);
      f13 = (-0x1.b1eedc0000000p+21) / (((0x1.86860e0000000p+39) == (double)0) ? (double)1 : (0x1.86860e0000000p+39));
      f13 = (f13 < -0x1p40 || f13 > 0x1p40) ? (double)1 : f13;
    }
  }
  if ((unsigned)(((unsigned)(2337949503u) % ((unsigned)(((unsigned)(arr9[((unsigned)(u8) & 7u)]) << ((unsigned)(((unsigned)(((unsigned)((unsigned)(s4)) % ((unsigned)(st12.f0) | 1u))) * (unsigned)(((unsigned)(u8) | (unsigned)(((unsigned)(u8) ^ cs)))))) & 31u))) | 1u))) & 1u) {
    cs = csmix(cs, (((double)(f15)) >= ((double)(f13))) ? 1u : 0u);
    cs = csmix(cs, ((0x1.f533d80000000p+37) > ((double)((unsigned)(u6)))) ? 1u : 0u);
  } else {
    u6 = (unsigned)((~((unsigned)((unsigned)(s4)) | 0u))) & 0xffffffffu;
    arr9[((unsigned)(u8) & 7u)] = (unsigned)(arr10[((unsigned)(u8) & 7u)]);
    f13 = (-0x1.646d640000000p+34) / ((((double)((unsigned)(u8))) == (double)0) ? (double)1 : ((double)((unsigned)(u8))));
    f13 = (f13 < -0x1p40 || f13 > 0x1p40) ? (double)1 : f13;
    u6 = (unsigned)((-((unsigned)(((unsigned)(((unsigned)((-((unsigned)(st11.f0) | 0u))) & (unsigned)(3327314833u))) + (unsigned)(((unsigned)(((unsigned)(arr10[((unsigned)(3277686835u) & 7u)]) + (unsigned)(3208815042u))) & (unsigned)(st11.f1))))) | 0u))) & 0xffffffffu;
    cs = csmix(cs, (((float)(f15)) > (0x1.d707820000000p+23f)) ? 1u : 0u);
  }
  { unsigned g21 = 0u;
    while (g21 < 7u) {
      unsigned i20 = g21;
      cs = csmix(cs, i20);
      { unsigned g23 = 0u;
        while (g23 < 3u) {
          unsigned i22 = g23;
          cs = csmix(cs, i22);
          cs = csmix(cs, (unsigned)((((unsigned)(2265783863u) & 1u) ? (unsigned)(((unsigned)(st12.f2) - (unsigned)(helper1(helper3(3957717340u, 4040348193u), 1919372905u)))) : (unsigned)(((unsigned)((unsigned)(s4)) | (unsigned)(((unsigned)(i22) > ((unsigned)(((unsigned)(u6) / ((unsigned)((unsigned)(s4)) | 1u))) ^ cs))))))));
          g23++;
        }
      }
      f15 = (-0x1.0edfec0000000p+18) + (0x1.ece4000000000p+14);
      f15 = (f15 < -0x1p40 || f15 > 0x1p40) ? (double)1 : f15;
      u5 = (unsigned)(u7) & 0xffffffffu;
      { unsigned g25 = 0u;
        while (g25 < 3u) {
          unsigned i24 = g25;
          cs = csmix(cs, i24);
          st12.f2 = (unsigned)(1228501382u);
          cs = csmix(cs, (unsigned)(st12.f1));
          cs = csmix(cs, (unsigned)(((unsigned)(arr10[((unsigned)(2409728441u) & 7u)]) ^ (unsigned)(((unsigned)(((unsigned)(((unsigned)(i24) & (unsigned)((unsigned)(s4)))) == ((unsigned)(1205481422u) ^ cs))) - (unsigned)((-((unsigned)(((unsigned)(st11.f1) + (unsigned)((unsigned)(s4)))) | 0u))))))));
          f13 = (-0x1.c4e6e40000000p+23) / (((-0x1.db21e00000000p+24) == (double)0) ? (double)1 : (-0x1.db21e00000000p+24));
          f13 = (f13 < -0x1p40 || f13 > 0x1p40) ? (double)1 : f13;
          cs = csmix(cs, (((double)(f14)) < (-0x1.6919820000000p+29)) ? 1u : 0u);
          i24 = (unsigned)(((unsigned)(arr9[((unsigned)(2003511740u) & 7u)]) ^ (unsigned)(2185448365u))) & 0xffffffffu;
          g25++;
        }
      }
      g21++;
    }
  }

  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, helper3(38177487u, cs));
  cs = csmix(cs, (unsigned)s4);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr9[k]);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr10[k]);
  cs = csmix(cs, st11.f0);
  cs = csmix(cs, st11.f1);
  cs = csmix(cs, st11.f2);
  cs = csmix(cs, st12.f0);
  cs = csmix(cs, st12.f1);
  cs = csmix(cs, st12.f2);
  cs = csmix(cs, fbits_d(f13));
  cs = csmix(cs, fbits_f(f14));
  cs = csmix(cs, fbits_d(f15));
  printf("checksum=%08x\n", cs);
  return 0;
}
