/* float fuzz seed 268558 (vs-gcc; tcc self-consistent): second constant-division
 * boundary hitting the same gen_opif double-rounding bug as 337 (see
 * 337_fuzz_genopif_double_round.c).  Correct (gcc-matching) checksum=7e2b5275;
 * tcc gave 13c52093 pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=268558
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>
#include <string.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

static unsigned fbits_d(double d){ unsigned u[2]; memcpy(u, &d, sizeof u); return csmix(u[0], u[1]); }
static unsigned fbits_f(float f){ unsigned u; memcpy(&u, &f, sizeof u); return u; }


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(lr) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(1000645852u) ^ (unsigned)(2667060597u))) % ((unsigned)(((unsigned)(945145378u) + (unsigned)(pa))) | 1u)));
  lr = (unsigned)(((unsigned)(((unsigned)(2207886291u) - (unsigned)(1177594342u))) <= ((unsigned)(pa) ^ lr)));
  lr = (unsigned)(((unsigned)(3041188029u) < ((unsigned)(((unsigned)(pa) | (unsigned)(lr))) ^ lr)));
  lr = (unsigned)(pa);
  if ((unsigned)((~((unsigned)(pa) | 0u))) & 1u) lr += (unsigned)(4022466542u);
  return (unsigned)(((unsigned)(pb) | (unsigned)(((unsigned)((~((unsigned)(pa) | 0u))) - (unsigned)(((unsigned)(pa) >> ((unsigned)(2036124115u) & 31u))))))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(((unsigned)((((unsigned)(203757956u) & 1u) ? (unsigned)(pa) : (unsigned)(lr))) * (unsigned)(pb))) | (unsigned)(pa)));
  if ((unsigned)(lr) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(2698078275u) + (unsigned)(2436272353u))) << ((unsigned)(((unsigned)(pb) % ((unsigned)(4175219407u) | 1u))) & 31u)));
  return (unsigned)(95274543u) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  long s3 = (long)(1919937190u & 0xffffffff);
  unsigned u4 = 214939215u;
  unsigned u5 = 2799975038u;
  unsigned arr6[8] = { 1370118703u, 3992994804u, 1670516260u, 1205491084u, 2135494638u, 3867859437u, 1336277849u, 4030777340u };
  struct S st7 = { 2417693866u, 1578532694u, 1205249918u };
  struct S st8 = { 1639374077u, 3474735457u, 2387390123u };
  double f9 = -0x1.2e4faa0000000p+34;
  float f10 = -0x1.fc15440000000p+20f;
  double f11 = -0x1.bf617c0000000p+12;

  { unsigned g13 = 0u;
    while (g13 < 12u) {
      unsigned i12 = g13;
      cs = csmix(cs, i12);
      i12 = (unsigned)(4259782161u) & 0xffffffffu;
      g13++;
    }
  }
  for (unsigned g15 = 0u; g15 < 6u; g15++) {
    unsigned i14 = g15;
    cs = csmix(cs, i14);
    for (unsigned g17 = 0u; g17 < 3u; g17++) {
      unsigned i16 = g17;
      cs = csmix(cs, i16);
      i16 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(i16) - (unsigned)(u4))) >> ((unsigned)(((unsigned)(i16) >> ((unsigned)(arr6[((unsigned)(i14) & 7u)]) & 31u))) & 31u))) ^ (unsigned)(u5))) <= ((unsigned)(((unsigned)(((unsigned)(((unsigned)(st8.f0) ^ (unsigned)(i14))) | (unsigned)(((unsigned)(u5) * (unsigned)(i16))))) >> ((unsigned)(((unsigned)(((unsigned)(486796129u) / ((unsigned)(arr6[((unsigned)(968893606u) & 7u)]) | 1u))) * (unsigned)((~((unsigned)(st8.f0) | 0u))))) & 31u))) ^ cs))) & 0xffffffffu;
      cs = csmix(cs, (unsigned)((~((unsigned)(((unsigned)(((unsigned)(((unsigned)(st8.f0) ^ (unsigned)(2195650820u))) % ((unsigned)((~((unsigned)(u4) | 0u))) | 1u))) / ((unsigned)((unsigned)(s3)) | 1u))) | 0u))));
      f10 = (-0x1.6c25a40000000p+11f) / ((((float)(f9)) == (float)0) ? (float)1 : ((float)(f9)));
      f10 = (f10 < -0x1p40f || f10 > 0x1p40f) ? (float)1 : f10;
    }
  }
  { unsigned g19 = 0u;
    while (g19 < 10u) {
      unsigned i18 = g19;
      cs = csmix(cs, i18);
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)((-((unsigned)(st7.f0) | 0u))) << ((unsigned)(((unsigned)(i18) - (unsigned)(2863090321u))) & 31u))) >> ((unsigned)(((unsigned)(((unsigned)(st8.f2) | (unsigned)(4137104376u))) * (unsigned)(((unsigned)(u5) - (unsigned)(u4))))) & 31u))) | (unsigned)((~((unsigned)(((unsigned)(st8.f0) - (unsigned)(i18))) | 0u))))));
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(st7.f1) ^ (unsigned)(((unsigned)((unsigned)(s3)) + (unsigned)(st8.f2))))) + (unsigned)(((unsigned)(helper2(856519915u, (unsigned)(s3))) % ((unsigned)(arr6[((unsigned)(u4) & 7u)]) | 1u))))) & (unsigned)((unsigned)(s3)))));
      for (unsigned g21 = 0u; g21 < 11u; g21++) {
        unsigned i20 = g21;
        cs = csmix(cs, i20);
        cs = csmix(cs, (unsigned)((unsigned)(s3)));
        cs = csmix(cs, (unsigned)(arr6[((unsigned)(u5) & 7u)]));
        u5 = (unsigned)(((unsigned)((unsigned)(s3)) + (unsigned)(((unsigned)((~((unsigned)((((unsigned)(4022155262u) & 1u) ? (unsigned)(arr6[((unsigned)(i18) & 7u)]) : (unsigned)(u5))) | 0u))) ^ (unsigned)(((unsigned)(((unsigned)(2188180750u) | (unsigned)(3370425046u))) & (unsigned)(((unsigned)(u5) % ((unsigned)(st7.f2) | 1u))))))))) & 0xffffffffu;
        f9 = ((double)(f11)) + ((double)(f10));
        f9 = (f9 < -0x1p40 || f9 > 0x1p40) ? (double)1 : f9;
      }
      cs = csmix(cs, (unsigned)((((unsigned)(((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(u5))) << ((unsigned)(((unsigned)((unsigned)(s3)) | (unsigned)(((unsigned)((unsigned)(s3)) ^ cs)))) & 31u))) >= ((unsigned)((((unsigned)(((unsigned)(st7.f2) & (unsigned)((unsigned)(s3)))) & 1u) ? (unsigned)(st7.f0) : (unsigned)(231937177u))) ^ cs))) & 1u) ? (unsigned)((~((unsigned)(((unsigned)(((unsigned)(2918977959u) * (unsigned)(i18))) == ((unsigned)(u5) ^ cs))) | 0u))) : (unsigned)(((unsigned)(((unsigned)((~((unsigned)(st7.f1) | 0u))) & (unsigned)((~((unsigned)(arr6[((unsigned)(4201213700u) & 7u)]) | 0u))))) | (unsigned)((-((unsigned)(((unsigned)(u4) - (unsigned)(687740771u))) | 0u))))))));
      g19++;
    }
  }
  for (unsigned g23 = 0u; g23 < 11u; g23++) {
    unsigned i22 = g23;
    cs = csmix(cs, i22);
    f9 = -((double)(f10));
    f9 = (f9 < -0x1p40 || f9 > 0x1p40) ? (double)1 : f9;
    u5 = (unsigned)(((unsigned)(u4) | (unsigned)(((unsigned)(u4) ^ cs)))) & 0xffffffffu;
    f9 = (-0x1.b26a380000000p+31) / (((-0x1.f271120000000p+39) == (double)0) ? (double)1 : (-0x1.f271120000000p+39));
    f9 = (f9 < -0x1p40 || f9 > 0x1p40) ? (double)1 : f9;
    cs = csmix(cs, (unsigned)(u4));
    cs = csmix(cs, (unsigned)(((unsigned)(3036381511u) ^ (unsigned)(((unsigned)((unsigned)(s3)) & (unsigned)(helper2(((unsigned)(st7.f0) + (unsigned)(((unsigned)(st7.f0) ^ cs))), ((unsigned)((unsigned)(s3)) - (unsigned)(i22)))))))));
  }
  cs = csmix(cs, (unsigned)(1313645464u));
  f10 = ((float)(f9)) * ((float)(f11));
  f10 = (f10 < -0x1p40f || f10 > 0x1p40f) ? (float)1 : f10;

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, (unsigned)s3);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr6[k]);
  cs = csmix(cs, st7.f0);
  cs = csmix(cs, st7.f1);
  cs = csmix(cs, st7.f2);
  cs = csmix(cs, st8.f0);
  cs = csmix(cs, st8.f1);
  cs = csmix(cs, st8.f2);
  cs = csmix(cs, fbits_d(f9));
  cs = csmix(cs, fbits_f(f10));
  cs = csmix(cs, fbits_d(f11));
  printf("checksum=%08x\n", cs);
  return 0;
}
