/* Differential-fuzz seed 320164 (O2 wrong; O0/O1 correct).  A single
 * store-load-forwarding bug that seed 320164 tripped structurally in EVERY
 * generator profile (int/ptr/float/switch/longlong/...): sl_forward
 * (ir/opt_memory.c) forwarded the value of a VAR through its home slot into
 * plain-copy readers (`Vb <- Va`) and then recorded Va's defining store as a
 * dead-store-elimination candidate -- but the post-pass "still read?" scan
 * only inspects is_local memory operands, so it missed Va's other readers that
 * consume it as a direct vreg arithmetic operand (`T <- Va MUL #3`,
 * `T <- Va XOR Vc`).  It deleted the still-live store, leaving those reads
 * dangling on an undefined register.  All three sibling recording sites carry a
 * `store dest vreg < 0` (anonymous stack slot only) guard; the STORE->STORE
 * forward site was missing it.  Fixed by adding the same guard.
 * Correct checksum=6d9b4dbb; tcc -O2 gave 93519d3f pre-fix. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=320164  (reduced)
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  return (unsigned)((~((unsigned)(pb) | 0u))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(((unsigned)(helper1(pb, pb)) ^ (unsigned)(helper1(lr, 2836482834u)))) & 1u) lr += (unsigned)(3639253254u);
  return (unsigned)(pb) ^ lr;
}


int main(void)
{
  unsigned cs = 0x12345678u;


  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  printf("checksum=%08x\n", cs);
  return 0;
}
