/* Fuzz seed ptr:1143 (-O2): ssa_opt_load_cse's store-forwarding substituted a
 * forwarded IMMEDIATE into a barrel-shift-annotated src2 (dest = src1 OP
 * (src2 SHIFT #n)) — folding/encoding the UN-shifted value.  Caught by the
 * tcc_ir_set_src2 tripwire (CONFIG_TCC_DEBUG abort -> COMPILE_FAIL); release
 * builds would miscompile.  Fix: both load_cse substitution sites bail on
 * (side==src2 && immediate && tcc_ir_barrel_shift_at), same as const_prop_tmp.
 *
 * AUTO-GENERATED by tests/fuzz/gen_c.py  seed=1143 (profile ptr). */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)((-((unsigned)(((unsigned)(2608391418u) | (unsigned)(1194649852u))) | 0u))) & 1u) lr += (unsigned)(pa);
  lr = (unsigned)(((unsigned)((-((unsigned)(((unsigned)(pb) * (unsigned)(lr))) | 0u))) * (unsigned)(pb)));
  if ((unsigned)(lr) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(2968547192u) - (unsigned)(763032749u))) / ((unsigned)(((unsigned)(lr) - (unsigned)(pb))) | 1u)));
  lr = (unsigned)((~((unsigned)(((unsigned)(((unsigned)(651458970u) < ((unsigned)(71344018u) ^ lr))) % ((unsigned)(((unsigned)(lr) ^ (unsigned)(3566732681u))) | 1u))) | 0u)));
  return (unsigned)(((unsigned)(lr) + (unsigned)(((unsigned)(lr) != ((unsigned)(49983908u) ^ lr))))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s2 = (short)(653882513u & 0xffff);
  int s3 = (int)(1908140492u & 0xffffffff);
  unsigned u4 = 85488627u;
  unsigned u5 = 2097668882u;
  unsigned *p6 = &u5;
  unsigned *p7 = &u5;

  u4 = (unsigned)(((unsigned)(2801186223u) & (unsigned)(((unsigned)(((unsigned)(1469528629u) ^ (unsigned)(2375551753u))) & (unsigned)(((unsigned)(u5) % ((unsigned)(((unsigned)(u5) ^ cs)) | 1u))))))) & 0xffffffffu;
  if ((unsigned)(431645886u) & 1u) {
    *p7 = (unsigned)(1133998581u);
    cs = csmix(cs, *p7);
  }
  *p7 = (unsigned)(((unsigned)((unsigned)(s2)) & (unsigned)(((unsigned)(2996587303u) == ((unsigned)(((unsigned)(4068296698u) - (unsigned)((unsigned)(s2)))) ^ cs)))));
  cs = csmix(cs, *p6);
  *p6 = (unsigned)((*p7));
  cs = csmix(cs, *p7);
  *p6 = (unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) ^ (unsigned)(((unsigned)(((unsigned)((*p7)) >> ((unsigned)(2780737705u) & 31u))) & (unsigned)(u5))))) / ((unsigned)(((unsigned)(u5) << ((unsigned)(1952697620u) & 31u))) | 1u)));
  cs = csmix(cs, *p7);
  *p7 = (unsigned)((*p7));
  cs = csmix(cs, *p6);
  if ((unsigned)(3356795455u) & 1u) {
    *p6 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(2622800218u) * (unsigned)(u5))) > ((unsigned)(1995677059u) ^ cs))) * (unsigned)((-((unsigned)((*p6)) | 0u))))) % ((unsigned)(((unsigned)((*p6)) ^ (unsigned)((*p7)))) | 1u)));
    cs = csmix(cs, *p6);
  }
  u4 = (unsigned)((((unsigned)((~((unsigned)((unsigned)(s2)) | 0u))) & 1u) ? (unsigned)((*p6)) : (unsigned)(1085653269u))) & 0xffffffffu;

  cs = csmix(cs, u4);
  cs = csmix(cs, u5);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  cs = csmix(cs, *p6);
  cs = csmix(cs, *p7);
  printf("checksum=%08x\n", cs);
  return 0;
}
