/* Fuzz seed float:8061 (-O1): tcc_gen_machine_cbz_forward_ok passed at
 * literal-pool pressure 1016 (< the 1020 flush trigger by 4 bytes); the real
 * pass drifted past the estimate and a 188-byte pool flush landed inside the
 * committed CBZ's range -> COMPILE_FAIL "CBZ/CBNZ target out of range:
 * offset=204" at th_patch_call (CBZ cannot be widened in place).  Fix: the
 * pressure bound now requires a 64-byte cushion. */
/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=8061
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>
#include <string.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

static unsigned fbits_d(double d){ unsigned u[2]; memcpy(u, &d, sizeof u); return csmix(u[0], u[1]); }
static unsigned fbits_f(float f){ unsigned u; memcpy(&u, &f, sizeof u); return u; }


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(3558257231u) + (unsigned)(3575289157u)));
  if ((unsigned)(1513741639u) & 1u) lr += (unsigned)(((unsigned)((~((unsigned)(pa) | 0u))) == ((unsigned)(3865651196u) ^ lr)));
  return (unsigned)(lr) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  char s2 = (char)(1229906602u & 0xff);
  long s3 = (long)(1057506971u & 0xffffffff);
  short s4 = (short)(1321607142u & 0xffff);
  unsigned u5 = 2094068182u;
  unsigned u6 = 2260843949u;
  unsigned arr7[8] = { 1549751340u, 689591690u, 1072913269u, 3950824432u, 1340281372u, 3430830845u, 1706708132u, 296453596u };
  struct S st8 = { 2201182324u, 2732739298u, 834339195u };
  struct S st9 = { 1808115652u, 2479273064u, 1528893568u };
  double f10 = -0x1.f5b3080000000p+30;
  float f11 = 0x1.42ef860000000p+22f;

  u5 = (unsigned)(st9.f1) & 0xffffffffu;
  for (unsigned g13 = 0u; g13 < 9u; g13++) {
    unsigned i12 = g13;
    cs = csmix(cs, i12);
    for (unsigned g15 = 0u; g15 < 1u; g15++) {
      unsigned i14 = g15;
      cs = csmix(cs, i14);
      i14 = (unsigned)(((unsigned)((~((unsigned)(((unsigned)(((unsigned)(1853799044u) * (unsigned)(68095416u))) & (unsigned)((unsigned)(s3)))) | 0u))) - (unsigned)(arr7[((unsigned)(i14) & 7u)]))) & 0xffffffffu;
    }
  }
  if ((unsigned)(((unsigned)(helper1(u5, ((unsigned)((-((unsigned)(u5) | 0u))) & (unsigned)(((unsigned)(u5) ^ (unsigned)(u6)))))) - (unsigned)(st9.f2))) & 1u) {
    f11 = ((float)(f11)) * (0x1.2ff0d00000000p+36f);
    f11 = (f11 < -0x1p40f || f11 > 0x1p40f) ? (float)1 : f11;
    cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)((~((unsigned)(helper1(arr7[((unsigned)(u6) & 7u)], 409281673u)) | 0u))) << ((unsigned)(((unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(794642737u))) - (unsigned)(arr7[((unsigned)(u5) & 7u)]))) & 31u))) == ((unsigned)(((unsigned)(((unsigned)((-((unsigned)(arr7[((unsigned)(u6) & 7u)]) | 0u))) + (unsigned)((((unsigned)(arr7[((unsigned)(u5) & 7u)]) & 1u) ? (unsigned)(st8.f1) : (unsigned)(arr7[((unsigned)(u5) & 7u)]))))) / ((unsigned)(arr7[((unsigned)(u5) & 7u)]) | 1u))) ^ cs))));
    { unsigned g17 = 0u;
      while (g17 < 1u) {
        unsigned i16 = g17;
        cs = csmix(cs, i16);
        st8.f0 = (unsigned)(i16);
        f10 = ((double)(f10)) + ((double)(f11));
        f10 = (f10 < -0x1p40 || f10 > 0x1p40) ? (double)1 : f10;
        cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)((~((unsigned)(((unsigned)(177087940u) - (unsigned)(603661782u))) | 0u))) >> ((unsigned)(((unsigned)(2567158968u) / ((unsigned)(((unsigned)((unsigned)(s2)) * (unsigned)(u5))) | 1u))) & 31u))) + (unsigned)(((unsigned)(u6) << ((unsigned)(2530216849u) & 31u))))));
        cs = csmix(cs, (unsigned)((((unsigned)(arr7[((unsigned)(2567739437u) & 7u)]) & 1u) ? (unsigned)(st9.f2) : (unsigned)(((unsigned)((-((unsigned)(i16) | 0u))) & (unsigned)(4229455222u))))));
        u5 = (unsigned)(((unsigned)(i16) % ((unsigned)(((unsigned)(i16) / ((unsigned)((~((unsigned)(((unsigned)(1726706720u) >> ((unsigned)(st9.f0) & 31u))) | 0u))) | 1u))) | 1u))) & 0xffffffffu;
        g17++;
      }
    }
    cs = csmix(cs, (unsigned)(((unsigned)((((unsigned)(((unsigned)(((unsigned)(st9.f0) & (unsigned)((unsigned)(s2)))) - (unsigned)(((unsigned)(u6) << ((unsigned)(1315367956u) & 31u))))) & 1u) ? (unsigned)(helper1(((unsigned)(404541430u) >> ((unsigned)(473516196u) & 31u)), ((unsigned)((unsigned)(s3)) + (unsigned)(u6)))) : (unsigned)(((unsigned)(((unsigned)(u6) & (unsigned)(51121381u))) >> ((unsigned)(((unsigned)(u5) << ((unsigned)(2370842709u) & 31u))) & 31u))))) & (unsigned)(((unsigned)(helper1(1953321813u, (-((unsigned)(st9.f1) | 0u)))) >> ((unsigned)(u6) & 31u))))));
    u5 = (unsigned)(((unsigned)((-((unsigned)(arr7[((unsigned)(u6) & 7u)]) | 0u))) ^ (unsigned)(((unsigned)(u6) / ((unsigned)(((unsigned)(((unsigned)(u5) / ((unsigned)(3961261388u) | 1u))) & (unsigned)(651802930u))) | 1u))))) & 0xffffffffu;
    f11 = ((float)(f11)) / ((((float)(f10)) == (float)0) ? (float)1 : ((float)(f10)));
    f11 = (f11 < -0x1p40f || f11 > 0x1p40f) ? (float)1 : f11;
  } else {
    arr7[((unsigned)(u6) & 7u)] = (unsigned)(((unsigned)(((unsigned)(arr7[((unsigned)(u5) & 7u)]) | (unsigned)(helper1(((unsigned)(3702572728u) | (unsigned)(arr7[((unsigned)(u5) & 7u)])), 1537872811u)))) - (unsigned)(((unsigned)(3346974770u) * (unsigned)(arr7[((unsigned)(u5) & 7u)])))));
    u5 = (unsigned)(2542074141u) & 0xffffffffu;
  }
  st9.f1 = (unsigned)(((unsigned)(((unsigned)((~((unsigned)(arr7[((unsigned)(3461131277u) & 7u)]) | 0u))) % ((unsigned)(((unsigned)((~((unsigned)(u5) | 0u))) ^ (unsigned)(((unsigned)(2372007418u) % ((unsigned)(4088462042u) | 1u))))) | 1u))) >> ((unsigned)(u6) & 31u)));
  arr7[((unsigned)(29308087u) & 7u)] = (unsigned)(((unsigned)(((unsigned)(((unsigned)(arr7[((unsigned)(u6) & 7u)]) / ((unsigned)(((unsigned)(3701460431u) / ((unsigned)(arr7[((unsigned)(u5) & 7u)]) | 1u))) | 1u))) ^ (unsigned)((((unsigned)(((unsigned)(arr7[((unsigned)(u6) & 7u)]) % ((unsigned)(1245995039u) | 1u))) & 1u) ? (unsigned)((((unsigned)(u6) & 1u) ? (unsigned)(1578692577u) : (unsigned)(u6))) : (unsigned)(((unsigned)(arr7[((unsigned)(3230986846u) & 7u)]) != ((unsigned)(u5) ^ cs))))))) - (unsigned)(((unsigned)(u5) != ((unsigned)(((unsigned)((~((unsigned)(4274690542u) | 0u))) << ((unsigned)(((unsigned)(3990973335u) % ((unsigned)(1769370404u) | 1u))) & 31u))) ^ cs)))));
  f11 = ((float)(f10)) - ((float)((unsigned)(u6)));
  f11 = (f11 < -0x1p40f || f11 > 0x1p40f) ? (float)1 : f11;

  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  cs = csmix(cs, (unsigned)s4);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr7[k]);
  cs = csmix(cs, st8.f0);
  cs = csmix(cs, st8.f1);
  cs = csmix(cs, st8.f2);
  cs = csmix(cs, st9.f0);
  cs = csmix(cs, st9.f1);
  cs = csmix(cs, st9.f2);
  cs = csmix(cs, fbits_d(f10));
  cs = csmix(cs, fbits_f(f11));
  printf("checksum=%08x\n", cs);
  return 0;
}
