/* 64-bit shift lowering: every constant amount, variable amounts, and the two
 * specializations that read fewer operands than the generic sequence.
 *
 * Three lowerings meet here, all in
 * source/backend/arch/arm/thumb/arm-thumb-gen.c:
 *
 *  - thumb_emit_shift64_mop, sh in 1..31.  The cross term is folded into the
 *    ORR as a shifted register operand (`orr rd, rd, src, LSR #(32-sh)`).  If
 *    the encoder ever picks the 16-bit ORR the shift field silently vanishes
 *    and the halves come out unmerged -- a wrong value, not a fault.
 *  - thumb_emit_shift64_reg_mop, the whole sequence for a variable count.  It
 *    leans on ARM reading only the bottom BYTE of the count, so the `32-n` and
 *    `n-32` cross terms self-disable; an amount of exactly 0 or exactly 32 is
 *    where that either works or does not.
 *  - the zero-high-word specialization of that sequence, which drops the terms
 *    reading the high half.  `(1ULL << n) - 1` and `(u64)u32 >> n` are its two
 *    shapes; the second collapses to a single shift plus a zero fill.
 *
 * Every case is FNV-hashed or printed so a wrong half shows up, and the
 * destination deliberately aliases the source in the last block -- the
 * ordering constraint the folded form has to respect.
 *
 * Expected output was generated by host gcc, so it is a real oracle rather
 * than a snapshot of tcc's own behaviour. */

extern int printf(const char *, ...);

typedef unsigned long long u64;
typedef long long s64;
typedef unsigned u32;

static u64 vals[] = {0ULL, 1ULL, 0x8000000000000000ULL, 0x0123456789ABCDEFULL,
                     0xFFFFFFFFFFFFFFFFULL, 0x00000000FFFFFFFFULL,
                     0xFFFFFFFF00000000ULL, 0x8000000000000001ULL};
volatile int vn;
volatile u32 vu = 0xDEADBEEFu;

#define C1(k)                                              \
  do {                                                     \
    u64 a = v << k;                                        \
    u64 b = v >> k;                                        \
    s64 c = ((s64)v) >> k;                                 \
    h = (h ^ a) * 1099511628211ULL;                        \
    h = (h ^ b) * 1099511628211ULL;                        \
    h = (h ^ (u64)c) * 1099511628211ULL;                   \
  } while (0)
#define C4(k) C1(k); C1(k + 1); C1(k + 2); C1(k + 3)
#define C16(k) C4(k); C4(k + 4); C4(k + 8); C4(k + 12)

int main(void)
{
  u64 h = 1469598103934665603ULL;
  unsigned i, n;

  for (i = 0; i < sizeof(vals) / sizeof(vals[0]); i++)
  {
    u64 v = vals[i];
    C16(0);
    C16(16);
    C16(32);
    C16(48);
    printf("const %u %08x%08x\n", i, (unsigned)(h >> 32), (unsigned)h);
  }

  for (n = 0; n < 64; n++)
  {
    vn = (int)n;
    u64 m = (1ULL << vn) - 1;
    u64 z = (u64)vu << vn;
    u64 y = (u64)vu >> vn;
    s64 sy = (s64)(u64)vu >> vn;
    printf("zh %u %08x%08x %08x%08x %08x%08x %08x%08x\n", n,
           (unsigned)(m >> 32), (unsigned)m, (unsigned)(z >> 32), (unsigned)z,
           (unsigned)(y >> 32), (unsigned)y,
           (unsigned)((u64)sy >> 32), (unsigned)sy);
  }

  for (i = 0; i < sizeof(vals) / sizeof(vals[0]); i++)
  {
    u64 a = vals[i], b = vals[i], c = vals[i];
    vn = (int)(i * 7 + 1);
    a <<= vn;
    b >>= vn;
    c <<= 3;
    c >>= 5;
    printf("alias %u %08x%08x %08x%08x %08x%08x\n", i,
           (unsigned)(a >> 32), (unsigned)a, (unsigned)(b >> 32), (unsigned)b,
           (unsigned)(c >> 32), (unsigned)c);
  }
  printf("H %08x%08x\n", (unsigned)(h >> 32), (unsigned)h);
  return 0;
}
