/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=233
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}

/* hazard profile: memory the hazards below change behind the optimizer. */
static unsigned hz_cell = 0x2468ace1u;
static void hz_set(unsigned *q, unsigned v) { *q = v ^ 0x5a5a5a5au; }
__attribute__((noinline, noipa)) static unsigned hz_apply(unsigned *p, unsigned v)
{
  void *args = __builtin_apply_args();
  unsigned a = *p;
  __builtin_apply((void (*)())hz_set, args, 16);
  unsigned b = *p;
  return a * 31u + b;
}
static void *hz_jb[5];
__attribute__((noinline, noipa)) static void hz_jump(void) { __builtin_longjmp(hz_jb, 1); }
__attribute__((noinline, noipa)) static unsigned hz_sj(unsigned x)
{
  static volatile unsigned n;
  n = 0u;
  __builtin_setjmp(hz_jb);
  if (++n < (x & 3u) + 1u)
    hz_jump();
  return n * 7u + x;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)(((unsigned)(2906232638u) / ((unsigned)(((unsigned)(pa) >> ((unsigned)(pb) & 31u))) | 1u))) * (unsigned)(pb)));
  if ((unsigned)(((unsigned)(((unsigned)(lr) & (unsigned)(pb))) > ((unsigned)((-((unsigned)(3279677994u) | 0u))) ^ lr))) & 1u) lr += (unsigned)(lr);
  if ((unsigned)(4041733541u) & 1u) lr += (unsigned)(3014333423u);
  return (unsigned)(((unsigned)((((unsigned)(((unsigned)(pb) * (unsigned)(pa))) & 1u) ? (unsigned)(lr) : (unsigned)(pb))) & (unsigned)((((unsigned)(((unsigned)(pa) == ((unsigned)(lr) ^ lr))) & 1u) ? (unsigned)(2889453955u) : (unsigned)(((unsigned)(455412769u) | (unsigned)(pb))))))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s2 = (short)(370329422u & 0xffff);
  int s3 = (int)(159149375u & 0xffffffff);
  short s4 = (short)(1785334346u & 0xffff);
  unsigned u5 = 437198595u;
  unsigned u6 = 3914040707u;
  unsigned u7 = 3371671700u;
  unsigned u8 = 4256075660u;
  unsigned u9 = 2828092757u;
  unsigned u10 = 3943615647u;
  unsigned arr11[8] = { 154595947u, 3638406850u, 1150717695u, 1292942592u, 3639617635u, 1816458477u, 443312498u, 4288351206u };
  unsigned arr12[8] = { 4097658421u, 3903136017u, 2575853415u, 749755044u, 3405491269u, 3035562265u, 2443711005u, 4173952077u };
  struct S st13 = { 839907947u, 1927456581u, 3305795454u };
  struct S st14 = { 2052763599u, 3982369820u, 2947374054u };

  { unsigned g16 = 0u;
    while (g16 < 10u) {
      unsigned i15 = g16;
      cs = csmix(cs, i15);
      cs = csmix(cs, (unsigned)((((unsigned)(((unsigned)(3387502464u) - (unsigned)(u9))) & 1u) ? (unsigned)(((unsigned)((((unsigned)(((unsigned)(505990284u) - (unsigned)(arr12[((unsigned)(3462401875u) & 7u)]))) & 1u) ? (unsigned)(arr12[((unsigned)(i15) & 7u)]) : (unsigned)(((unsigned)((unsigned)(s4)) / ((unsigned)(2521906466u) | 1u))))) / ((unsigned)(u5) | 1u))) : (unsigned)(((unsigned)(u8) > ((unsigned)(((unsigned)(st14.f1) - (unsigned)(((unsigned)(1727237981u) >> ((unsigned)(arr12[((unsigned)(2703491516u) & 7u)]) & 31u))))) ^ cs))))));
      {
        unsigned hzm17 = 0u;
        __asm__ volatile("str %1, %0" : "=m"(hzm17) : "r"((unsigned)(((unsigned)(((unsigned)((((unsigned)((unsigned)(s3)) & 1u) ? (unsigned)(u8) : (unsigned)(((unsigned)(2750393906u) % ((unsigned)(3667185091u) | 1u))))) * (unsigned)(u7))) + (unsigned)(((unsigned)(i15) * (unsigned)((unsigned)(s3))))))));
        cs = csmix(cs, hzm17);
      }
      {
        static void *const hzt18[2] = { &&hzLa19, &&hzLb20 };
        goto *hzt18[(unsigned)(u6) & 1u];
      hzLa19: u7 ^= 2707869127u; goto hzLc21;
      hzLb20: u7 += 2713498368u;
      hzLc21: cs = csmix(cs, u7);
      }
      { unsigned g23 = 0u;
        while (g23 < 11u) {
          unsigned i22 = g23;
          cs = csmix(cs, i22);
          {
            unsigned hzn24 = ((unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(u10) == ((unsigned)(u9) ^ cs))) - (unsigned)(((unsigned)(371673343u) | (unsigned)(4054923287u))))) + (unsigned)(u5))) << ((unsigned)(((unsigned)(((unsigned)(((unsigned)(u9) | (unsigned)(u6))) << ((unsigned)(st13.f2) & 31u))) % ((unsigned)(((unsigned)(3040820407u) | (unsigned)(u7))) | 1u))) & 31u))) & 7u) + 1u;
            unsigned hzv25[hzn24];
            for (unsigned hzk26 = 0u; hzk26 < hzn24; hzk26++) hzv25[hzk26] = u6 * (hzk26 + 3u);
            cs = csmix(cs, hzv25[(unsigned)(helper1((unsigned)(s3), helper1((((unsigned)(((unsigned)((unsigned)(s3)) % ((unsigned)(u5) | 1u))) & 1u) ? (unsigned)(((unsigned)(398532007u) - (unsigned)(u5))) : (unsigned)(((unsigned)(i22) / ((unsigned)(st14.f0) | 1u)))), u7))) % hzn24]);
          }
          {
            unsigned hzn27 = ((unsigned)((unsigned)(s4)) & 7u) + 1u;
            unsigned *hza28 = __builtin_alloca(hzn27 * sizeof(unsigned));
            for (unsigned hzk29 = 0u; hzk29 < hzn27; hzk29++) hza28[hzk29] = i22 ^ hzk29;
            cs = csmix(cs, hza28[hzn27 - 1u]);
          }
          {
            unsigned hzn30 = ((unsigned)(((unsigned)((~((unsigned)(((unsigned)(arr11[((unsigned)(u10) & 7u)]) % ((unsigned)(((unsigned)(3393165821u) / ((unsigned)(st13.f2) | 1u))) | 1u))) | 0u))) <= ((unsigned)(((unsigned)(3683091393u) % ((unsigned)(((unsigned)(((unsigned)(u7) + (unsigned)(st13.f0))) - (unsigned)(566932463u))) | 1u))) ^ cs))) & 7u) + 1u;
            unsigned *hza31 = __builtin_alloca(hzn30 * sizeof(unsigned));
            for (unsigned hzk32 = 0u; hzk32 < hzn30; hzk32++) hza31[hzk32] = u8 ^ hzk32;
            cs = csmix(cs, hza31[hzn30 - 1u]);
          }
          {
            unsigned hzn33 = ((unsigned)((unsigned)(s2)) & 7u) + 1u;
            unsigned *hza34 = __builtin_alloca(hzn33 * sizeof(unsigned));
            for (unsigned hzk35 = 0u; hzk35 < hzn33; hzk35++) hza34[hzk35] = i15 ^ hzk35;
            cs = csmix(cs, hza34[hzn33 - 1u]);
          }
          u10 = (unsigned)(((unsigned)((unsigned)(s3)) | (unsigned)((~((unsigned)(((unsigned)((-((unsigned)(u10) | 0u))) << ((unsigned)(((unsigned)(st14.f0) | (unsigned)(u9))) & 31u))) | 0u))))) & 0xffffffffu;
          g23++;
        }
      }
      g16++;
    }
  }
  if ((unsigned)(((unsigned)(((unsigned)((unsigned)(s2)) * (unsigned)(helper1((unsigned)(s2), ((unsigned)(st13.f1) >> ((unsigned)(2032621249u) & 31u)))))) | (unsigned)(((unsigned)(((unsigned)(u6) & (unsigned)((~((unsigned)(4267301234u) | 0u))))) - (unsigned)(((unsigned)((~((unsigned)(u7) | 0u))) | (unsigned)((-((unsigned)(arr11[((unsigned)(2028625009u) & 7u)]) | 0u))))))))) & 1u) {
    for (unsigned g37 = 0u; g37 < 12u; g37++) {
      unsigned i36 = g37;
      cs = csmix(cs, i36);
      cs = csmix(cs, hz_sj((unsigned)(((unsigned)((-((unsigned)(u10) | 0u))) + (unsigned)(((unsigned)(((unsigned)(((unsigned)(u5) - (unsigned)(i36))) > ((unsigned)(((unsigned)(arr11[((unsigned)(u9) & 7u)]) ^ (unsigned)((unsigned)(s3)))) ^ cs))) & (unsigned)(arr11[((unsigned)(1972170658u) & 7u)])))))));
      {
        unsigned hznf38(unsigned x) { i36 = i36 * 3u + x; return i36 ^ u8; }
        cs = csmix(cs, hznf38((unsigned)((-((unsigned)(((unsigned)(((unsigned)(i36) * (unsigned)(((unsigned)(i36) ^ cs)))) % ((unsigned)(2770110213u) | 1u))) | 0u)))));
        cs = csmix(cs, i36);
      }
      u6 = hz_cell;
      cs = csmix(cs, hz_apply(&hz_cell, (unsigned)(3843724762u)));
      cs = csmix(cs, hz_cell ^ u6);
      cs = csmix(cs, hz_apply(&u8, (unsigned)((-((unsigned)(((unsigned)(helper1(u5, (~((unsigned)(u6) | 0u)))) >> ((unsigned)(3250314121u) & 31u))) | 0u)))));
      cs = csmix(cs, u8);
    }
    cs = csmix(cs, (unsigned)(145202336u));
    {
      unsigned hznf39(unsigned x) { u7 = u7 * 3u + x; return u7 ^ u5; }
      cs = csmix(cs, hznf39((unsigned)(((unsigned)(((unsigned)(arr11[((unsigned)(2038476806u) & 7u)]) >> ((unsigned)(((unsigned)(u7) == ((unsigned)(((unsigned)((unsigned)(s3)) * (unsigned)(u8))) ^ cs))) & 31u))) == ((unsigned)(((unsigned)(((unsigned)(((unsigned)(st14.f2) << ((unsigned)(arr12[((unsigned)(u7) & 7u)]) & 31u))) + (unsigned)((~((unsigned)(arr12[((unsigned)(2639515126u) & 7u)]) | 0u))))) * (unsigned)(helper1(((unsigned)(3987448031u) + (unsigned)(1352942312u)), ((unsigned)(u6) + (unsigned)(((unsigned)(u6) ^ cs))))))) ^ cs)))));
      cs = csmix(cs, u7);
    }
    for (unsigned g41 = 0u; g41 < 6u; g41++) {
      unsigned i40 = g41;
      cs = csmix(cs, i40);
      arr12[((unsigned)(u8) & 7u)] = (unsigned)(arr12[((unsigned)(u6) & 7u)]);
      hz_cell = (unsigned)(((unsigned)(1886918695u) | (unsigned)(u10)));
      __asm__ volatile("" ::: "memory");
      u5 = hz_cell + u5;
      u5 = (unsigned)((unsigned)(s4)) & 0xffffffffu;
    }
    cs = csmix(cs, hz_sj((unsigned)(helper1((-((unsigned)(((unsigned)(((unsigned)(4203096928u) <= ((unsigned)(3950900143u) ^ cs))) * (unsigned)(((unsigned)(4232522814u) * (unsigned)(3528267261u))))) | 0u)), (~((unsigned)((unsigned)(s4)) | 0u))))));
  }
  __asm__("add %0, %0, #106" : "+r"(u8));
  cs = csmix(cs, u8);

  cs = csmix(cs, u5);
  cs = csmix(cs, u6);
  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, u9);
  cs = csmix(cs, u10);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, hz_apply(&hz_cell, cs));
  cs = csmix(cs, hz_sj(cs));
  cs = csmix(cs, hz_cell);
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, (unsigned)s3);
  cs = csmix(cs, (unsigned)s4);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr11[k]);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr12[k]);
  cs = csmix(cs, st13.f0);
  cs = csmix(cs, st13.f1);
  cs = csmix(cs, st13.f2);
  cs = csmix(cs, st14.f0);
  cs = csmix(cs, st14.f1);
  cs = csmix(cs, st14.f2);
  printf("checksum=%08x\n", cs);
  return 0;
}
