/* hazard sandwich: asm_goto -- a value read before the construct, memory
 * changed by it, the value read again after.  Generated by the hazard matrix (2026-10-06); the expected output is arm-none-eabi-gcc -O2's. */
#include <stdio.h>
int G, H;
__attribute__((noinline)) void set_pv(int *p, int v) { *p = v; }
__attribute__((noinline, pure)) int readG(void) { return G; }
__attribute__((noinline)) int s_load(int *p, int v) {  int a = *p; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; int b = *p; return a * 1000 + b; }
__attribute__((noinline)) int s_expr(int *p, int v) {  int a = *p * 3 + v; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; int b = *p * 3 + v; return a * 1000 + b; }
__attribute__((noinline)) int s_cmp(int *p, int v) {  int a = *p; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; int b = *p; return a == b; }
__attribute__((noinline)) int s_cmp2(int *p, int v) {  int a = *p + 1; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; if (a == *p + 1) return 7; return 9; }
__attribute__((noinline)) int s_glob(int *p, int v) {  int a = G + 1; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; return a * 1000 + G + 1; }
__attribute__((noinline)) int s_pure(int *p, int v) {  int a = readG(); __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; return a * 1000 + readG(); }
__attribute__((noinline)) int s_loop(int *p, int v) {  int s = 0; for (int i = 0; i < 3; i++) { s = s * 10 + readG(); __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; } return s; }
__attribute__((noinline)) int s_loopld(int *p, int v) {  int s = 0; for (int i = 0; i < 3; i++) { s = s * 10 + G; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; } return s; }
__attribute__((noinline)) int s_local(int *q, int v) { int x = 1; int *p = &x; *q = 0;  int a = x; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; return a * 1000 + x; }
__attribute__((noinline)) int s_xor(int *p, int v) {  int t = *p ^ H; __asm__ goto("str %1, [%0]\n\tcmp %1, #255\n\tbeq %l[out__]" :: "r"(p), "r"(v) : "memory", "cc" : out__); out__:; return (t ^ H) * 1000 + (t == *p); }
int main(void)
{
  G = 1; printf("load %d\n", s_load(&G, 5));
  G = 2; printf("expr %d\n", s_expr(&G, 6));
  G = 3; printf("cmp %d\n", s_cmp(&G, 7));
  G = 3; printf("cmp2 %d\n", s_cmp2(&G, 8));
  G = 4; printf("glob %d\n", s_glob(&G, 9));
  G = 5; printf("pure %d\n", s_pure(&G, 2));
  G = 6; printf("loop %d\n", s_loop(&G, 3));
  G = 7; printf("loopld %d\n", s_loopld(&G, 4));
  printf("local %d\n", s_local(&H, 6));
  G = 8; H = 2; printf("xor %d\n", s_xor(&G, 5));
  return 0;
}
