/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=22
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(3014869100u);
  if ((unsigned)((((unsigned)(2432295465u) & 1u) ? (unsigned)(((unsigned)(213293751u) * (unsigned)(3967901955u))) : (unsigned)(((unsigned)(2532122966u) - (unsigned)(pb))))) & 1u) lr += (unsigned)(((unsigned)(pb) <= ((unsigned)(((unsigned)(pb) | (unsigned)(1855038115u))) ^ lr)));
  if ((unsigned)((~((unsigned)(((unsigned)(pb) % ((unsigned)(1605366306u) | 1u))) | 0u))) & 1u) lr += (unsigned)(((unsigned)((~((unsigned)(pa) | 0u))) % ((unsigned)(pb) | 1u)));
  return (unsigned)(pa) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  short s2 = (short)(1720817577u & 0xffff);
  unsigned u3 = 414747138u;
  unsigned u4 = 3846144942u;
  unsigned *p5 = &u4;
  unsigned *p6 = &u4;
  struct S st7 = { 2703866056u, 1905182530u, 3174162897u };

  u3 = (unsigned)(3556665659u) & 0xffffffffu;
  *p6 = (unsigned)(st7.f2);
  cs = csmix(cs, *p5);
  *p5 = (unsigned)(st7.f1);
  cs = csmix(cs, *p6);
  u4 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(u3) + (unsigned)(((unsigned)(st7.f2) ^ (unsigned)(u3))))) / ((unsigned)(1094994029u) | 1u))) & (unsigned)(((unsigned)((*p5)) ^ (unsigned)(((unsigned)(((unsigned)(st7.f0) & (unsigned)(141615383u))) << ((unsigned)(u4) & 31u))))))) & 0xffffffffu;
  u4 = (unsigned)(((unsigned)(((unsigned)(2431279280u) & (unsigned)(st7.f0))) >> ((unsigned)(2592723829u) & 31u))) & 0xffffffffu;
  u4 = (unsigned)(((unsigned)(((unsigned)((*p6)) + (unsigned)(((unsigned)((~((unsigned)(1525477429u) | 0u))) >> ((unsigned)((*p5)) & 31u))))) / ((unsigned)(((unsigned)((*p6)) & (unsigned)(((unsigned)((*p6)) ^ cs)))) | 1u))) & 0xffffffffu;
  cs = csmix(cs, (unsigned)((unsigned)(s2)));

  cs = csmix(cs, u3);
  cs = csmix(cs, u4);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, (unsigned)s2);
  cs = csmix(cs, st7.f0);
  cs = csmix(cs, st7.f1);
  cs = csmix(cs, st7.f2);
  cs = csmix(cs, *p5);
  cs = csmix(cs, *p6);
  printf("checksum=%08x\n", cs);
  return 0;
}
