/* AUTO-GENERATED by tests/fuzz/gen_c.py  seed=24769
 * UB-free random C program for differential fuzzing (Tracks 2/3).
 * Prints a single line: "checksum=<hex>".  Do not edit by hand.
 */
#include <stdio.h>

/* Rolling checksum mix (all unsigned -> fully defined). */
static unsigned csmix(unsigned h, unsigned v)
{
  h ^= v + 0x9e3779b9u + (h << 6) + (h >> 2);
  h = (h << 13) | (h >> 19);
  return h * 2654435761u;
}


static unsigned helper1(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(((unsigned)((~((unsigned)(((unsigned)(2707191418u) | (unsigned)(1062863821u))) | 0u))) * (unsigned)(((unsigned)(((unsigned)(lr) | (unsigned)(pb))) >> ((unsigned)(((unsigned)(3106159339u) % ((unsigned)(705011412u) | 1u))) & 31u)))));
  if ((unsigned)(((unsigned)(((unsigned)(2488216943u) - (unsigned)(2860233126u))) | (unsigned)(((unsigned)(2225362769u) / ((unsigned)(pb) | 1u))))) & 1u) lr += (unsigned)(((unsigned)(pb) / ((unsigned)(((unsigned)(1171440547u) % ((unsigned)(pa) | 1u))) | 1u)));
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(pa) | (unsigned)(15415140u))) + (unsigned)(((unsigned)(2609730642u) / ((unsigned)(1162123149u) | 1u))))) ^ (unsigned)(((unsigned)(((unsigned)(pa) * (unsigned)(((unsigned)(pa) ^ lr)))) - (unsigned)(((unsigned)(lr) ^ (unsigned)(3956067848u)))))));
  if ((unsigned)(((unsigned)(((unsigned)(lr) << ((unsigned)(pb) & 31u))) * (unsigned)(((unsigned)(lr) & (unsigned)(((unsigned)(lr) ^ lr)))))) & 1u) lr += (unsigned)(lr);
  return (unsigned)(((unsigned)((-((unsigned)(((unsigned)(2013221088u) >= ((unsigned)(lr) ^ lr))) | 0u))) * (unsigned)(pa))) ^ lr;
}

static unsigned helper2(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  lr = (unsigned)(591107471u);
  lr = (unsigned)(1631435551u);
  return (unsigned)(1827955498u) ^ lr;
}

static unsigned helper3(unsigned pa, unsigned pb)
{
  unsigned lr = pa ^ (pb * 3u);
  if ((unsigned)(((unsigned)(((unsigned)(2910217959u) - (unsigned)(pa))) + (unsigned)(((unsigned)(1034946827u) & (unsigned)(2784150510u))))) & 1u) lr += (unsigned)(helper2((-((unsigned)(lr) | 0u)), ((unsigned)(pa) + (unsigned)(((unsigned)(pa) ^ lr)))));
  lr = (unsigned)(((unsigned)(pa) << ((unsigned)(lr) & 31u)));
  lr = (unsigned)(((unsigned)(((unsigned)(((unsigned)(2158959228u) - (unsigned)(927857055u))) >> ((unsigned)(((unsigned)(1247664937u) - (unsigned)(4182550497u))) & 31u))) ^ (unsigned)(((unsigned)(((unsigned)(pa) % ((unsigned)(884516103u) | 1u))) ^ (unsigned)(((unsigned)(2479061549u) / ((unsigned)(pa) | 1u)))))));
  if ((unsigned)((-((unsigned)(((unsigned)(pb) << ((unsigned)(pa) & 31u))) | 0u))) & 1u) lr += (unsigned)((-((unsigned)(1408586195u) | 0u)));
  if ((unsigned)(pa) & 1u) lr += (unsigned)(((unsigned)(((unsigned)(pa) % ((unsigned)(1575817169u) | 1u))) < ((unsigned)(pa) ^ lr)));
  return (unsigned)((-((unsigned)(((unsigned)(1665655750u) ^ (unsigned)(((unsigned)(pa) << ((unsigned)(3955765522u) & 31u))))) | 0u))) ^ lr;
}

struct S {
  unsigned f0;
  unsigned f1;
  unsigned f2;
};

int main(void)
{
  unsigned cs = 0x12345678u;
  int s4 = (int)(1669722848u & 0xffffffff);
  short s5 = (short)(552126973u & 0xffff);
  char s6 = (char)(762396820u & 0xff);
  unsigned u7 = 206258941u;
  unsigned u8 = 631225112u;
  unsigned u9 = 832232781u;
  unsigned u10 = 483378658u;
  unsigned arr11[8] = { 450717457u, 2446967634u, 4000477749u, 2829127934u, 4022114436u, 4153694485u, 3058029744u, 576551044u };

  for (unsigned g13 = 0u; g13 < 11u; g13++) {
    unsigned i12 = g13;
    cs = csmix(cs, i12);
    arr11[((unsigned)(i12) & 7u)] = (unsigned)(helper3(arr11[((unsigned)(4176508962u) & 7u)], 2715271470u));
  }
  if ((unsigned)((~((unsigned)(((unsigned)(((unsigned)((~((unsigned)(arr11[((unsigned)(u7) & 7u)]) | 0u))) | (unsigned)(((unsigned)(510393009u) ^ (unsigned)(arr11[((unsigned)(1701737476u) & 7u)]))))) * (unsigned)(((unsigned)(((unsigned)(u8) >> ((unsigned)(3760877025u) & 31u))) ^ (unsigned)(u8))))) | 0u))) & 1u) {
    cs = csmix(cs, (unsigned)(((unsigned)(498827525u) == ((unsigned)(((unsigned)(((unsigned)((~((unsigned)(2523953997u) | 0u))) / ((unsigned)(((unsigned)(1802221784u) - (unsigned)(u8))) | 1u))) & (unsigned)(3275616894u))) ^ cs))));
    for (unsigned g15 = 0u; g15 < 8u; g15++) {
      unsigned i14 = g15;
      cs = csmix(cs, i14);
      u8 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(1792634971u) << ((unsigned)(((unsigned)((unsigned)(s6)) + (unsigned)(arr11[((unsigned)(3806522971u) & 7u)]))) & 31u))) / ((unsigned)(((unsigned)(1357313662u) + (unsigned)(867431893u))) | 1u))) / ((unsigned)(((unsigned)(((unsigned)(helper1(u7, arr11[((unsigned)(u7) & 7u)])) % ((unsigned)((((unsigned)(arr11[((unsigned)(u10) & 7u)]) & 1u) ? (unsigned)((unsigned)(s4)) : (unsigned)(2028415757u))) | 1u))) + (unsigned)(((unsigned)(u7) % ((unsigned)((unsigned)(s4)) | 1u))))) | 1u))) & 0xffffffffu;
      arr11[((unsigned)(u7) & 7u)] = (unsigned)(u10);
      cs = csmix(cs, (unsigned)(((unsigned)(u8) % ((unsigned)(((unsigned)(773657430u) % ((unsigned)((-((unsigned)(u7) | 0u))) | 1u))) | 1u))));
      u10 = (unsigned)(u9) & 0xffffffffu;
      arr11[((unsigned)(632896597u) & 7u)] = (unsigned)(helper3((unsigned)(s6), 3529433203u));
      arr11[((unsigned)(u8) & 7u)] = (unsigned)(((unsigned)(1473648239u) & (unsigned)(((unsigned)(i14) << ((unsigned)(arr11[((unsigned)(u7) & 7u)]) & 31u)))));
    }
    for (unsigned g17 = 0u; g17 < 5u; g17++) {
      unsigned i16 = g17;
      cs = csmix(cs, i16);
      cs = csmix(cs, (unsigned)((unsigned)(s4)));
      u9 = (unsigned)(((unsigned)((-((unsigned)(775230455u) | 0u))) | (unsigned)(u9))) & 0xffffffffu;
    }
    if ((unsigned)(arr11[((unsigned)(3297877615u) & 7u)]) & 1u) {
      u9 = (unsigned)(914835850u) & 0xffffffffu;
    }
    u7 = (unsigned)(288360608u) & 0xffffffffu;
  }
  u8 = (unsigned)(((unsigned)(((unsigned)(((unsigned)(1133129481u) % ((unsigned)(u9) | 1u))) - (unsigned)(u7))) % ((unsigned)(arr11[((unsigned)(1143322017u) & 7u)]) | 1u))) & 0xffffffffu;
  if ((unsigned)(((unsigned)((((unsigned)((~((unsigned)(u7) | 0u))) & 1u) ? (unsigned)(((unsigned)((unsigned)(s5)) & (unsigned)(arr11[((unsigned)(71397334u) & 7u)]))) : (unsigned)(196312127u))) >= ((unsigned)(((unsigned)((((unsigned)(((unsigned)((unsigned)(s6)) % ((unsigned)(3170721986u) | 1u))) & 1u) ? (unsigned)(1078930223u) : (unsigned)(u10))) >> ((unsigned)(u8) & 31u))) ^ cs))) & 1u) {
    u8 = (unsigned)((((unsigned)(((unsigned)(((unsigned)((~((unsigned)(u8) | 0u))) + (unsigned)(((unsigned)((unsigned)(s6)) ^ (unsigned)(3525240574u))))) + (unsigned)((((unsigned)(u10) & 1u) ? (unsigned)((((unsigned)(arr11[((unsigned)(397706671u) & 7u)]) & 1u) ? (unsigned)(arr11[((unsigned)(1058573174u) & 7u)]) : (unsigned)(u10))) : (unsigned)(u8))))) & 1u) ? (unsigned)(u9) : (unsigned)((-((unsigned)(1554389536u) | 0u))))) & 0xffffffffu;
    for (unsigned g19 = 0u; g19 < 3u; g19++) {
      unsigned i18 = g19;
      cs = csmix(cs, i18);
      u10 = (unsigned)(helper3((((unsigned)(((unsigned)(u10) & (unsigned)(((unsigned)(u8) + (unsigned)((unsigned)(s4)))))) & 1u) ? (unsigned)((((unsigned)((-((unsigned)((unsigned)(s5)) | 0u))) & 1u) ? (unsigned)((unsigned)(s4)) : (unsigned)((((unsigned)(u8) & 1u) ? (unsigned)((unsigned)(s5)) : (unsigned)(arr11[((unsigned)(u8) & 7u)]))))) : (unsigned)(u9)), ((unsigned)((-((unsigned)(3143898688u) | 0u))) % ((unsigned)(((unsigned)(((unsigned)(u9) & (unsigned)(1930429413u))) % ((unsigned)(((unsigned)(i18) / ((unsigned)(3438936076u) | 1u))) | 1u))) | 1u)))) & 0xffffffffu;
      i18 = (unsigned)(i18) & 0xffffffffu;
      u9 = (unsigned)(helper2(u7, ((unsigned)(((unsigned)(i18) > ((unsigned)(arr11[((unsigned)(u8) & 7u)]) ^ cs))) + (unsigned)((unsigned)(s6))))) & 0xffffffffu;
      cs = csmix(cs, (unsigned)(((unsigned)(u7) + (unsigned)(((unsigned)(u7) ^ cs)))));
    }
    cs = csmix(cs, (unsigned)((unsigned)(s6)));
    arr11[((unsigned)(u10) & 7u)] = (unsigned)(((unsigned)(((unsigned)(((unsigned)((~((unsigned)(u9) | 0u))) ^ (unsigned)(((unsigned)(4201228256u) << ((unsigned)(982152008u) & 31u))))) - (unsigned)((~((unsigned)(((unsigned)(u8) == ((unsigned)(((unsigned)(u8) ^ cs)) ^ cs))) | 0u))))) >> ((unsigned)(((unsigned)(((unsigned)(2977094215u) ^ (unsigned)((unsigned)(s5)))) | (unsigned)(((unsigned)(((unsigned)(u8) * (unsigned)((unsigned)(s4)))) <= ((unsigned)(((unsigned)(u10) * (unsigned)(u9))) ^ cs))))) & 31u)));
    if ((unsigned)(((unsigned)(((unsigned)(u7) + (unsigned)(arr11[((unsigned)(u9) & 7u)]))) | (unsigned)((unsigned)(s5)))) & 1u) {
      cs = csmix(cs, (unsigned)((unsigned)(s5)));
      u9 = (unsigned)(((unsigned)((~((unsigned)(((unsigned)(((unsigned)(u7) / ((unsigned)(u8) | 1u))) % ((unsigned)(((unsigned)(arr11[((unsigned)(u7) & 7u)]) + (unsigned)(arr11[((unsigned)(3233034889u) & 7u)]))) | 1u))) | 0u))) >> ((unsigned)((unsigned)(s5)) & 31u))) & 0xffffffffu;
      u10 = (unsigned)(u7) & 0xffffffffu;
      cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(699526540u) <= ((unsigned)((unsigned)(s5)) ^ cs))) >> ((unsigned)(((unsigned)(u8) << ((unsigned)(u9) & 31u))) & 31u))) >> ((unsigned)(((unsigned)(((unsigned)((unsigned)(s6)) * (unsigned)(arr11[((unsigned)(u10) & 7u)]))) | (unsigned)((~((unsigned)(arr11[((unsigned)(u8) & 7u)]) | 0u))))) & 31u))) ^ (unsigned)(((unsigned)(((unsigned)(((unsigned)(arr11[((unsigned)(u8) & 7u)]) & (unsigned)(391080879u))) << ((unsigned)((unsigned)(s6)) & 31u))) % ((unsigned)(((unsigned)(((unsigned)(3182269420u) >> ((unsigned)(u10) & 31u))) < ((unsigned)(helper3(arr11[((unsigned)(u10) & 7u)], 2310328037u)) ^ cs))) | 1u))))));
    }
    if ((unsigned)(arr11[((unsigned)(u7) & 7u)]) & 1u) {
      cs = csmix(cs, (unsigned)(((unsigned)((unsigned)(s4)) * (unsigned)((unsigned)(s6)))));
      u10 = (unsigned)(((unsigned)(1615521583u) / ((unsigned)(((unsigned)((~((unsigned)((-((unsigned)(u9) | 0u))) | 0u))) << ((unsigned)(((unsigned)(((unsigned)(u9) ^ (unsigned)(arr11[((unsigned)(u8) & 7u)]))) * (unsigned)(1873043581u))) & 31u))) | 1u))) & 0xffffffffu;
      u9 = (unsigned)((unsigned)(s6)) & 0xffffffffu;
    }
  }
  cs = csmix(cs, (unsigned)(((unsigned)(((unsigned)(((unsigned)(((unsigned)(1458627470u) & (unsigned)((unsigned)(s5)))) < ((unsigned)(((unsigned)(3731073929u) <= ((unsigned)(u8) ^ cs))) ^ cs))) < ((unsigned)((-((unsigned)((-((unsigned)(arr11[((unsigned)(680855830u) & 7u)]) | 0u))) | 0u))) ^ cs))) + (unsigned)(1635541675u))));

  cs = csmix(cs, u7);
  cs = csmix(cs, u8);
  cs = csmix(cs, u9);
  cs = csmix(cs, u10);
  cs = csmix(cs, helper1(1u, cs));
  cs = csmix(cs, helper2(19088744u, cs));
  cs = csmix(cs, helper3(38177487u, cs));
  cs = csmix(cs, (unsigned)s4);
  cs = csmix(cs, (unsigned)s5);
  cs = csmix(cs, (unsigned)s6);
  for (unsigned k = 0u; k < 8u; k++) cs = csmix(cs, arr11[k]);
  printf("checksum=%08x\n", cs);
  return 0;
}
