/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../backend/arch/arm/thumb/arm-thumb-call.c"
#undef COPY_STUB_MAX_WORDS
#include "../backend/arch/arm/thumb/arm-thumb-callsite.c"
#undef USING_GLOBALS
