/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/tccasm.c"
#undef ASM_MACRO_MAX_ARGS
#undef USING_GLOBALS
#include "../frontend/gen/builtin/call.c"
#undef CONST_LOOP_INLINE_BUDGET
#include "../frontend/gen/builtin/chk.c"
#undef FIND_LOCAL_OBJSIZE
#include "../frontend/gen/builtin/fp2.c"
#include "../frontend/gen/core/predicates.c"
#undef TCC_IS_NATIVE_387
