/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/decl/struct.c"
#include "../frontend/gen/expr/cond.c"
#include "../frontend/gen/expr/indir.c"
#include "../frontend/gen/expr/infix.c"
#undef precedence
#include "../frontend/gen/expr/primary.c"
#include "../frontend/gen/expr/unary.c"
#include "../frontend/gen/init/alloc.c"
#include "../frontend/gen/op/float.c"
#undef gen_negf
#include "../frontend/gen/sym/elfsym.c"
