/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/inline/analysis.c"
#undef AUTO_INLINE_NONSTATIC_STRUCT_MAX_TOKENS
#include "../frontend/gen/inline/const_eval.c"
#include "../frontend/gen/inline/emit.c"
#undef CALLED_ONCE_LARGE_BODY
#undef GC_MARK
#include "../frontend/gen/nested/nested.c"
#include "../frontend/gen/op/complex.c"
#undef PUSH_COMP
#undef PUSH_FCOMP
#undef STORE_COMP
#undef STORE_FCOMP
#include "../frontend/gen/op/fold_math.c"
#undef NUM_FOLDABLE_MATH_FUNCS
