/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/inline/analysis.c"
#undef AUTO_INLINE_NONSTATIC_STRUCT_MAX_TOKENS
#include "../frontend/gen/inline/const_eval.c"
#include "../frontend/gen/inline/emit.c"
#undef CALLED_ONCE_LARGE_BODY
#undef GC_MARK
