/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/store/struct_copy.c"
#include "../frontend/gen/store/vstore.c"
#undef IS_GLOBAL_LVAL
#undef IS_LOCAL_LVAL
#undef IS_REG_DEREF_LVAL
