/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/op/int.c"
#include "../frontend/gen/op/op.c"
#include "../frontend/gen/op/vector.c"
#undef VEC_EMIT_RANGE_MAX
#undef VEC_RECIPE_MAX
#include "../frontend/gen/stmt/block.c"
#include "../frontend/gen/stmt/cleanup.c"
#include "../frontend/gen/stmt/ret.c"
#include "../frontend/gen/stmt/switch.c"
#include "../frontend/gen/store/struct_copy.c"
#include "../frontend/gen/store/vstore.c"
#undef IS_GLOBAL_LVAL
#undef IS_LOCAL_LVAL
#undef IS_REG_DEREF_LVAL
#include "../frontend/gen/sym/attr_merge.c"
