/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/core/predicates.c"
#undef TCC_IS_NATIVE_387
#include "../frontend/gen/core/state.c"
#include "../frontend/gen/core/suppress.c"
