/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../frontend/gen/type/assign_check.c"
#include "../frontend/gen/type/cast.c"
#undef ALLOW_SUBTYPE_ACCESS
#undef gen_cvt_itof1
#include "../frontend/gen/type/size.c"
