/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../ir/cross_jump.c"
#undef CJ_MAX_TAIL
#undef RM_BUCKET_TRIES
#undef RM_MAX_LEN
#undef RM_MAX_PARAMS
#undef RM_MIN_LEN
#undef RM_MULTI
#undef RM_NOCASE
#include "../ir/frame.c"
#undef FRAME_LIVE_MAX_WORDS
#undef FRAME_OBJ_ARG_COPY
#undef FRAME_OBJ_RET_TEMP
#undef TAINT_MULTI
#undef TAINT_NONE
#undef USING_GLOBALS
