/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../ir/regalloc.c"
#undef ASSIGN_VREG_IDX
#undef BFI_VREG_IDX
#undef LOAD_VREG_IDX
#undef OPH_VREG_IDX
#undef PHI_VREG_IDX
#undef RA_EXTEND_BACKEDGE
#undef RA_VREG_HAS_ASSIGN_IN_RANGE
#undef VREG_IDX
#include "../ir/regalloc_post.c"
#include "../ir/regalloc_scan.c"
#undef AVIDX
#undef AV_FOR_PARAM_USES
#undef HINT_IDX
#undef RA_EXITPHI_PUSH
#undef RA_WIDEN_MAX_WORDS
#undef W_ROW
