/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../machine/tccls.c"
#undef LS_DBG
#undef LS_LIVE_INTERVAL_INIT_SIZE
#undef SLOT_HASH
#undef STACK_ALLOC_LOG
#include "../machine/tccmachine.c"
