/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../obj/tccelf.c"
#include "../obj/tccelf_layout.c"
#include "../obj/tccelf_ld.c"
#undef DEBUG_VERSION
#undef LD_TOK_EOF
#undef LD_TOK_NAME
#include "../obj/tccelf_load.c"
#include "../obj/tccelf_output.c"
#include "../obj/tccelf_reloc.c"
#include "../obj/tccelf_sym.c"
#undef ELFCLASS_BITS
