/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../obj/tccelf_load.c"
#include "../obj/tccelf_ld.c"
#undef DEBUG_VERSION
#undef LD_TOK_EOF
#undef LD_TOK_NAME
#include "../obj/tccld.c"
#undef LDTOK_EOF
#undef LDTOK_NAME
#undef LDTOK_NUM
#undef LDTOK_STRING
