/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../obj/tccelf.c"
#include "../obj/tccelf_sym.c"
#undef ELFCLASS_BITS
#include "../obj/tccelf_reloc.c"
#include "../obj/tccelf_layout.c"
#include "../obj/tccelf_output.c"
