/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../opt/ra/branch_thread.c"
#undef BT_MAP
#undef BT_MAX_COPIES
#undef BT_MAX_WALK
#undef BT_PAD
#undef USING_GLOBALS
#include "../opt/ra/const_branch_fold.c"
#undef USING_GLOBALS
#include "../opt/ra/exit_sink.c"
#undef RA_EXIT_SINK_MAX_PASSES
#undef USING_GLOBALS
#include "../opt/ra/incomplete_calls.c"
#undef USING_GLOBALS
#include "../opt/ra/phi_const_chain.c"
#undef USING_GLOBALS
#include "../opt/ra/umaal_fusion.c"
#undef USING_GLOBALS
