/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../opt/ra/const_branch_fold.c"
#undef USING_GLOBALS
#include "../opt/ra/incomplete_calls.c"
#undef USING_GLOBALS
#include "../opt/ra/phi_const_chain.c"
#undef USING_GLOBALS
#include "../opt/ra/umaal_fusion.c"
#undef USING_GLOBALS
