/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../opt/flat/ipa/func_write_summary.c"
#undef USING_GLOBALS
#undef VR_BIT
#include "../opt/flat/ipa/pure_via_sret.c"
#undef SRET_MARK
#undef SRET_TEST
#undef SRET_VR_TO_BIT
#undef USING_GLOBALS
#include "../opt/flat/ipa/tu_dead_statics.c"
#undef USING_GLOBALS
#include "../opt/flat/ipa/tu_func_summary.c"
#undef TU_MODREF_MAX_VISIT
#undef TU_VREG_MAP_MAX
#undef TU_VREG_MAP_OVERFLOW
#undef USING_GLOBALS
#include "../opt/flat/ipa/tu_noreturn.c"
#undef USING_GLOBALS
