/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../opt/analysis/alias.c"
#undef USING_GLOBALS
#include "../opt/analysis/du_chains.c"
#undef USING_GLOBALS
#include "../opt/analysis/mem_ssa.c"
#undef USING_GLOBALS
#include "../opt/analysis/memref.c"
#undef USING_GLOBALS
