/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../opt/ssa/engine/driver.c"
#undef SSA_RUN
#undef USING_GLOBALS
#include "../opt/ssa/engine/rewrite.c"
#undef USING_GLOBALS
#include "../opt/ssa/engine/stack_resolve.c"
#undef USING_GLOBALS
#include "../opt/ssa/engine/use_def.c"
#undef USING_GLOBALS
