/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../opt/ssa/scalar/cprop.c"
#undef USING_GLOBALS
#undef VARF_BIT
#undef VARF_SET
#include "../opt/ssa/scalar/sccp.c"
#undef USING_GLOBALS
