/* Generated by scripts/gen_unity.py -- do not edit; rerun it instead. */
#include "../backend/arch/arm/thumb/arm-thumb-mem.c"
#include "../backend/arch/arm/thumb/arm-thumb-fp.c"
#include "../backend/arch/arm/thumb/arm-thumb-frame.c"
#include "../backend/arch/arm/thumb/thumb-outline.c"
#undef OUTLINE_MAX_OPS
#undef OUTLINE_MIN_BYTES
#undef R_IS_SP_LR_PC
#undef USING_GLOBALS
#undef WINDOW_EXTEND
#undef WINDOW_SIZE
