# Generated by scripts/gen_unity.py -- do not edit; rerun it instead.
# Unity-build groups: see the "Unity build" block in the Makefile.
# Membership comes from source/unity/groups.txt.
# own TU: source/backend/generators/regalloc.c (expands differently inside a group)
# own TU: source/driver/libtcc.c (redefines header macros WARN_ON _tcc_error free gnu_ext realloc tcc_malloc tcc_mallocz tcc_realloc)
# own TU: source/frontend/gen/decl/decl.c (redefines header macros gjmp gjmp_addr)
# own TU: source/frontend/gen/init/initializer.c (redefines header macros DIF_CLEAR DIF_FIRST DIF_HAVE_ELEM DIF_SIZE_ONLY EXPR_ANY EXPR_CONST)
# own TU: source/frontend/gen/type/compare.c (redefines header macros CMP_OP SHIFT_OP)
# own TU: source/frontend/tccpp.c (redefines header macros DEF)
# own TU: source/ir/stack.c (redefines header macros INT32_MIN)
# own TU: source/ir/tccir_operand.c (redefines header macros INT32_MAX INT32_MIN UINT32_MAX)
# own TU: source/opt/ssa/cfg/cmp_eq.c (redefines header macros TOK_EQ TOK_NE)

UNITY_GROUPS_arm = arm arm_s1
UNITY_MEMBERS_arm = \
	source/backend/arch/arm/arm.c \
	source/backend/arch/arm/ssa_opt_arm.c
UNITY_MEMBERS_arm_s1 = \
	source/backend/arch/arm/arm-link.c \
	source/backend/arch/arm/arm_aapcs.c \
	source/backend/arch/arm/arm_regalloc.c

UNITY_GROUPS_thumb = arm_thumb arm_thumb_call arm_thumb_emit arm_thumb_gen arm_thumb_s1
UNITY_MEMBERS_arm_thumb = \
	source/backend/arch/arm/thumb/thop_bitfield.c \
	source/backend/arch/arm/thumb/thop_mem_imm.c \
	source/backend/arch/arm/thumb/thop_mem_reg.c \
	source/backend/arch/arm/thumb/thop_mov.c \
	source/backend/arch/arm/thumb/thumb-outline.c \
	source/backend/arch/arm/thumb/thumb.c
UNITY_MEMBERS_arm_thumb_call = \
	source/backend/arch/arm/thumb/arm-thumb-call.c \
	source/backend/arch/arm/thumb/arm-thumb-callsite.c
UNITY_MEMBERS_arm_thumb_emit = \
	source/backend/arch/arm/thumb/arm-thumb-emit.c \
	source/backend/arch/arm/thumb/arm-thumb-fp.c \
	source/backend/arch/arm/thumb/arm-thumb-frame.c \
	source/backend/arch/arm/thumb/arm-thumb-mem.c
UNITY_MEMBERS_arm_thumb_gen = \
	source/backend/arch/arm/thumb/arm-thumb-alu.c \
	source/backend/arch/arm/thumb/arm-thumb-gen.c
UNITY_MEMBERS_arm_thumb_s1 = \
	source/backend/arch/arm/thumb/thop_adr.c \
	source/backend/arch/arm/thumb/thop_alu_imm.c \
	source/backend/arch/arm/thumb/thop_alu_reg.c \
	source/backend/arch/arm/thumb/thop_block.c \
	source/backend/arch/arm/thumb/thop_branch.c \
	source/backend/arch/arm/thumb/thop_cmp.c \
	source/backend/arch/arm/thumb/thop_coproc.c \
	source/backend/arch/arm/thumb/thop_dsp.c \
	source/backend/arch/arm/thumb/thop_extend.c \
	source/backend/arch/arm/thumb/thop_ldaex.c \
	source/backend/arch/arm/thumb/thop_ldr_literal.c \
	source/backend/arch/arm/thumb/thop_ldrd.c \
	source/backend/arch/arm/thumb/thop_ldrex.c \
	source/backend/arch/arm/thumb/thop_mem_exclusive.c \
	source/backend/arch/arm/thumb/thop_mem_unpriv.c \
	source/backend/arch/arm/thumb/thop_mrs.c \
	source/backend/arch/arm/thumb/thop_mul.c \
	source/backend/arch/arm/thumb/thop_mvn.c \
	source/backend/arch/arm/thumb/thop_pld.c \
	source/backend/arch/arm/thumb/thop_rev.c \
	source/backend/arch/arm/thumb/thop_shift_imm.c \
	source/backend/arch/arm/thumb/thop_shift_reg.c \
	source/backend/arch/arm/thumb/thop_system.c \
	source/backend/arch/arm/thumb/thop_tbb.c \
	source/backend/arch/arm/thumb/thop_vfp.c

UNITY_GROUPS_frontend = frontend_gen_builtin frontend_gen_core frontend_gen_decl frontend_gen_expr frontend_gen_inline frontend_gen_op frontend_gen_stmt frontend_gen_store frontend_gen_sym frontend_gen_type frontend_gen_value
UNITY_MEMBERS_frontend_gen_builtin = \
	source/frontend/gen/builtin/call.c \
	source/frontend/gen/builtin/chk.c \
	source/frontend/gen/builtin/fp.c \
	source/frontend/gen/builtin/fp2.c \
	source/frontend/gen/builtin/misc.c \
	source/frontend/gen/builtin/overflow.c \
	source/frontend/gen/builtin/simd.c \
	source/frontend/gen/builtin/string.c
UNITY_MEMBERS_frontend_gen_core = \
	source/frontend/gen/core/predicates.c \
	source/frontend/gen/core/state.c \
	source/frontend/gen/core/suppress.c
UNITY_MEMBERS_frontend_gen_decl = \
	source/frontend/gen/decl/attribute.c \
	source/frontend/gen/decl/btype.c \
	source/frontend/gen/decl/declarator.c \
	source/frontend/gen/decl/predef_protos.c \
	source/frontend/gen/decl/struct.c
UNITY_MEMBERS_frontend_gen_expr = \
	source/frontend/gen/expr/atomic.c \
	source/frontend/gen/expr/cond.c \
	source/frontend/gen/expr/indir.c \
	source/frontend/gen/expr/infix.c \
	source/frontend/gen/expr/primary.c \
	source/frontend/gen/expr/unary.c
UNITY_MEMBERS_frontend_gen_inline = \
	source/frontend/gen/inline/analysis.c \
	source/frontend/gen/inline/const_eval.c \
	source/frontend/gen/inline/emit.c
UNITY_MEMBERS_frontend_gen_op = \
	source/frontend/gen/op/complex.c \
	source/frontend/gen/op/float.c \
	source/frontend/gen/op/fold_math.c \
	source/frontend/gen/op/int.c \
	source/frontend/gen/op/op.c \
	source/frontend/gen/op/vector.c
UNITY_MEMBERS_frontend_gen_stmt = \
	source/frontend/gen/stmt/block.c \
	source/frontend/gen/stmt/cleanup.c \
	source/frontend/gen/stmt/ret.c \
	source/frontend/gen/stmt/switch.c
UNITY_MEMBERS_frontend_gen_store = \
	source/frontend/gen/store/struct_copy.c \
	source/frontend/gen/store/vstore.c
UNITY_MEMBERS_frontend_gen_sym = \
	source/frontend/gen/sym/attr_merge.c \
	source/frontend/gen/sym/elfsym.c \
	source/frontend/gen/sym/symtab.c
UNITY_MEMBERS_frontend_gen_type = \
	source/frontend/gen/type/assign_check.c \
	source/frontend/gen/type/cast.c \
	source/frontend/gen/type/size.c
UNITY_MEMBERS_frontend_gen_value = \
	source/frontend/gen/value/load.c \
	source/frontend/gen/value/longlong.c \
	source/frontend/gen/value/rodata_rel.c \
	source/frontend/gen/value/strlit_pool.c \
	source/frontend/gen/value/vstack.c

UNITY_GROUPS_ir = ir ir_frame ir_gen ir_regalloc ir_regalloc_ssa
UNITY_MEMBERS_ir = \
	source/ir/cfg.c \
	source/ir/dead_def.c \
	source/ir/dump.c \
	source/ir/known_ext.c \
	source/ir/machine_op.c \
	source/ir/op_props.c \
	source/ir/pool.c \
	source/ir/self_store.c \
	source/ir/ssa.c \
	source/ir/type.c \
	source/ir/vreg.c
UNITY_MEMBERS_ir_frame = \
	source/ir/cross_jump.c \
	source/ir/frame.c \
	source/ir/frame_dfe.c
UNITY_MEMBERS_ir_gen = \
	source/ir/gen/arith.c \
	source/ir/gen/asm.c \
	source/ir/gen/config.c \
	source/ir/gen/control.c \
	source/ir/gen/float.c \
	source/ir/gen/jump.c \
	source/ir/gen/live.c \
	source/ir/gen/params.c \
	source/ir/gen/put.c \
	source/ir/gen/softfloat.c \
	source/ir/gen/state.c \
	source/ir/gen/util.c \
	source/ir/gen/vla.c
UNITY_MEMBERS_ir_regalloc = \
	source/ir/regalloc.c \
	source/ir/regalloc_post.c \
	source/ir/regalloc_scan.c
UNITY_MEMBERS_ir_regalloc_ssa = \
	source/ir/regalloc_entry.c \
	source/ir/regalloc_phi.c

UNITY_GROUPS_machine = machine_s1
UNITY_MEMBERS_machine_s1 = \
	source/machine/tccls.c \
	source/machine/tccmachine.c

UNITY_GROUPS_memory = memory_s1
UNITY_MEMBERS_memory_s1 = \
	source/memory/sort.c \
	source/memory/unique_ptr.c \
	source/memory/vector.c

UNITY_GROUPS_obj = obj_elf_s1 obj_s1
UNITY_MEMBERS_obj_elf_s1 = \
	source/obj/tccelf.c \
	source/obj/tccelf_layout.c \
	source/obj/tccelf_ld.c \
	source/obj/tccelf_load.c \
	source/obj/tccelf_output.c \
	source/obj/tccelf_reloc.c \
	source/obj/tccelf_sym.c
UNITY_MEMBERS_obj_s1 = \
	source/obj/tccdbg.c \
	source/obj/tccld.c \
	source/obj/tccyaff.c

UNITY_GROUPS_opt = opt_analysis opt_engine opt_flat_cfg opt_flat_dce opt_flat_fusion opt_flat_ipa opt_flat_loop opt_flat_loop_iv opt_flat_memory opt_flat_memory_cse opt_flat_memory_dse opt_flat_memory_fwd opt_flat_scalar opt_flat_scalar_const opt_flat_scalar_known opt_ra opt_ssa_cfg opt_ssa_dce opt_ssa_engine opt_ssa_loop opt_ssa_memory opt_ssa_scalar opt_ssa_scalar_prop opt_ssa_string opt_util
UNITY_MEMBERS_opt_analysis = \
	source/opt/analysis/alias.c \
	source/opt/analysis/du_chains.c \
	source/opt/analysis/mem_ssa.c \
	source/opt/analysis/memref.c
UNITY_MEMBERS_opt_engine = \
	source/opt/engine/ctx.c \
	source/opt/engine/fp_cache_shim.c \
	source/opt/engine/fp_mat_cache.c \
	source/opt/engine/gen_adapters.c \
	source/opt/engine/pass_timing.c \
	source/opt/engine/pipeline_run.c \
	source/opt/engine/pipeline_table.c \
	source/opt/engine/run_gens.c
UNITY_MEMBERS_opt_flat_cfg = \
	source/opt/flat/cfg/abort_tail_merge.c \
	source/opt/flat/cfg/bool_diamond_branch.c \
	source/opt/flat/cfg/if_convert.c \
	source/opt/flat/cfg/jump_thread.c \
	source/opt/flat/cfg/jumpif_invert.c \
	source/opt/flat/cfg/returnvalue_merge.c \
	source/opt/flat/cfg/switch_head.c \
	source/opt/flat/cfg/switch_to_data.c
UNITY_MEMBERS_opt_flat_dce = \
	source/opt/flat/dce/body_essential.c \
	source/opt/flat/dce/compact_nops.c \
	source/opt/flat/dce/const_return_uninit_elide.c \
	source/opt/flat/dce/dce.c \
	source/opt/flat/dce/dead_addrvar_elim.c \
	source/opt/flat/dce/dead_trailing_addrvar_store.c \
	source/opt/flat/dce/dead_vla.c \
	source/opt/flat/dce/infinite_loop_simplify.c \
	source/opt/flat/dce/infinite_self_recursion.c \
	source/opt/flat/dce/noreturn_call_epilogue.c \
	source/opt/flat/dce/noreturn_collapse.c \
	source/opt/flat/dce/null_store_dom_return.c \
	source/opt/flat/dce/orphan_cmp_elim.c \
	source/opt/flat/dce/redundant_cmp.c \
	source/opt/flat/dce/trap_only_body_suppress.c \
	source/opt/flat/dce/ub_only_body_elide.c \
	source/opt/flat/dce/uninit_ub.c \
	source/opt/flat/dce/zero_vla_elim.c
UNITY_MEMBERS_opt_flat_fusion = \
	source/opt/flat/fusion/add_deref_fold.c \
	source/opt/flat/fusion/and64_narrow.c \
	source/opt/flat/fusion/assign_fuse.c \
	source/opt/flat/fusion/barrel_shift.c \
	source/opt/flat/fusion/call_chain_rename.c \
	source/opt/flat/fusion/cmp_hi_only.c \
	source/opt/flat/fusion/cmp_imm_swap.c \
	source/opt/flat/fusion/cmp_narrow_64.c \
	source/opt/flat/fusion/disp.c \
	source/opt/flat/fusion/gens_fusion.c \
	source/opt/flat/fusion/indexed_chain.c \
	source/opt/flat/fusion/lea_fold.c \
	source/opt/flat/fusion/lea_rmw_fold.c \
	source/opt/flat/fusion/pack64.c \
	source/opt/flat/fusion/pack64_tautology.c \
	source/opt/flat/fusion/pair_reorder.c \
	source/opt/flat/fusion/shift64_dead_half.c \
	source/opt/flat/fusion/shift64_extract_ubfx.c \
	source/opt/flat/fusion/shift_pair_ubfx.c \
	source/opt/flat/fusion/shl32_or_chain.c \
	source/opt/flat/fusion/stackoff_addr_cse.c \
	source/opt/flat/fusion/zero_half64.c
UNITY_MEMBERS_opt_flat_ipa = \
	source/opt/flat/ipa/func_write_summary.c \
	source/opt/flat/ipa/pure_via_sret.c \
	source/opt/flat/ipa/tu_dead_statics.c \
	source/opt/flat/ipa/tu_func_summary.c \
	source/opt/flat/ipa/tu_noreturn.c
UNITY_MEMBERS_opt_flat_loop = \
	source/opt/flat/loop/const_sim.c \
	source/opt/flat/loop/decrement_carry.c \
	source/opt/flat/loop/func_purity.c \
	source/opt/flat/loop/loop_detect.c \
	source/opt/flat/loop/loop_eliminate.c \
	source/opt/flat/loop/loop_exit_analysis.c \
	source/opt/flat/loop/loop_ir_mutate.c \
	source/opt/flat/loop/loop_relayout.c \
	source/opt/flat/loop/loop_rotate.c \
	source/opt/flat/loop/loop_unroll.c \
	source/opt/flat/loop/reroll.c \
	source/opt/flat/loop/seq_guard_elim.c
UNITY_MEMBERS_opt_flat_loop_iv = \
	source/opt/flat/loop/backedge_phi_hoist.c \
	source/opt/flat/loop/decrement_to_zero.c \
	source/opt/flat/loop/iv_analysis.c \
	source/opt/flat/loop/iv_strength_reduction.c \
	source/opt/flat/loop/licm.c \
	source/opt/flat/loop/stack_param_promote.c
UNITY_MEMBERS_opt_flat_memory = \
	source/opt/flat/memory/block_copy_init.c \
	source/opt/flat/memory/const_local_table.c \
	source/opt/flat/memory/escape_copy_call.c \
	source/opt/flat/memory/mem_init.c \
	source/opt/flat/memory/mem_inline.c \
	source/opt/flat/memory/memmove_to_indexed_stores.c \
	source/opt/flat/memory/small_global_memset_to_store.c \
	source/opt/flat/memory/small_memset_to_store.c \
	source/opt/flat/memory/sra.c \
	source/opt/flat/memory/sret_nrvo.c \
	source/opt/flat/memory/struct_arg_split.c \
	source/opt/flat/memory/struct_copy_roundtrip_elim.c
UNITY_MEMBERS_opt_flat_memory_cse = \
	source/opt/flat/memory/deref_operand_cse.c \
	source/opt/flat/memory/global_base_share.c \
	source/opt/flat/memory/global_deref_cse.c \
	source/opt/flat/memory/invariant_global_load_hoist.c \
	source/opt/flat/memory/stack_addr_cse.c \
	source/opt/flat/memory/symaddr_cse.c
UNITY_MEMBERS_opt_flat_memory_dse = \
	source/opt/flat/memory/bitfield_unit_narrow.c \
	source/opt/flat/memory/byte_store_merge.c \
	source/opt/flat/memory/dead_init_via_call.c \
	source/opt/flat/memory/dead_lea_store.c \
	source/opt/flat/memory/dead_local_slot.c \
	source/opt/flat/memory/dead_static_store.c \
	source/opt/flat/memory/dead_temp_local.c \
	source/opt/flat/memory/dse.c \
	source/opt/flat/memory/rmw_byte_clear.c \
	source/opt/flat/memory/slot_const_store_fold.c \
	source/opt/flat/memory/store_inplace_arith.c \
	source/opt/flat/memory/var_store_elim.c
UNITY_MEMBERS_opt_flat_memory_fwd = \
	source/opt/flat/memory/addrof_var_fwd.c \
	source/opt/flat/memory/copy_source_load_fwd.c \
	source/opt/flat/memory/entry_store_prop.c \
	source/opt/flat/memory/param_copy_alias.c \
	source/opt/flat/memory/ptr_local_fwd.c \
	source/opt/flat/memory/sl_forward.c
UNITY_MEMBERS_opt_flat_scalar = \
	source/opt/flat/scalar/add_reassoc.c \
	source/opt/flat/scalar/bitfield.c \
	source/opt/flat/scalar/bool.c \
	source/opt/flat/scalar/call_result.c \
	source/opt/flat/scalar/cmp_field_fuse.c \
	source/opt/flat/scalar/inline_param_copy.c \
	source/opt/flat/scalar/narrow_store.c \
	source/opt/flat/scalar/sdiv_pow2.c \
	source/opt/flat/scalar/self_arith.c \
	source/opt/flat/scalar/self_copy.c \
	source/opt/flat/scalar/stack_bool_diamond.c \
	source/opt/flat/scalar/var_tmp_fwd.c \
	source/opt/flat/scalar/var_to_tmp.c
UNITY_MEMBERS_opt_flat_scalar_const = \
	source/opt/flat/scalar/addrof_const_fold.c \
	source/opt/flat/scalar/cmp_expr_fold.c \
	source/opt/flat/scalar/const_aggregate.c \
	source/opt/flat/scalar/const_call_fold.c \
	source/opt/flat/scalar/const_prop_tmp.c \
	source/opt/flat/scalar/const_string_calls.c \
	source/opt/flat/scalar/const_var_prop.c \
	source/opt/flat/scalar/global_init_prop.c \
	source/opt/flat/scalar/stack_addr_fold.c \
	source/opt/flat/scalar/switch_collapse.c \
	source/opt/flat/scalar/symref_const_prop.c
UNITY_MEMBERS_opt_flat_scalar_known = \
	source/opt/flat/scalar/branch.c \
	source/opt/flat/scalar/known_bits.c \
	source/opt/flat/scalar/redundant_loop_check.c \
	source/opt/flat/scalar/value_tracking.c
UNITY_MEMBERS_opt_ra = \
	source/opt/ra/branch_thread.c \
	source/opt/ra/const_branch_fold.c \
	source/opt/ra/exit_sink.c \
	source/opt/ra/incomplete_calls.c \
	source/opt/ra/phi_const_chain.c \
	source/opt/ra/umaal_fusion.c
UNITY_MEMBERS_opt_ssa_cfg = \
	source/opt/ssa/cfg/branch.c \
	source/opt/ssa/cfg/guard_collapse.c \
	source/opt/ssa/cfg/phi.c \
	source/opt/ssa/cfg/switch_fold.c \
	source/opt/ssa/cfg/vrp.c
UNITY_MEMBERS_opt_ssa_dce = \
	source/opt/ssa/dce/dce.c \
	source/opt/ssa/dce/dce_common.c \
	source/opt/ssa/dce/dead_global_stores.c \
	source/opt/ssa/dce/dead_overwrite_stores.c \
	source/opt/ssa/dce/dead_phi_cycles.c \
	source/opt/ssa/dce/dead_var_stores.c \
	source/opt/ssa/dce/orphan_params.c \
	source/opt/ssa/dce/ret_path_frame_store.c \
	source/opt/ssa/dce/stackloc_stores.c \
	source/opt/ssa/dce/temp_worklist.c \
	source/opt/ssa/dce/unreachable.c \
	source/opt/ssa/dce/var_liveness.c
UNITY_MEMBERS_opt_ssa_engine = \
	source/opt/ssa/engine/driver.c \
	source/opt/ssa/engine/rewrite.c \
	source/opt/ssa/engine/stack_resolve.c \
	source/opt/ssa/engine/use_def.c
UNITY_MEMBERS_opt_ssa_loop = \
	source/opt/ssa/loop/dead_loop.c \
	source/opt/ssa/loop/decrement_carry.c \
	source/opt/ssa/loop/decrement_to_zero.c \
	source/opt/ssa/loop/first_iter_exit.c \
	source/opt/ssa/loop/iv_strength_reduction.c \
	source/opt/ssa/loop/loop_bottom_test.c \
	source/opt/ssa/loop/loop_cand.c \
	source/opt/ssa/loop/loop_const_sim.c \
	source/opt/ssa/loop/loop_rotate.c \
	source/opt/ssa/loop/loop_unroll.c \
	source/opt/ssa/loop/ptr_iv_exit_subst.c
UNITY_MEMBERS_opt_ssa_memory = \
	source/opt/ssa/memory/copy_fwd.c \
	source/opt/ssa/memory/diamond_store_fwd.c \
	source/opt/ssa/memory/global_addr_hoist.c \
	source/opt/ssa/memory/global_store_dse.c \
	source/opt/ssa/memory/load_combine.c \
	source/opt/ssa/memory/load_cse.c \
	source/opt/ssa/memory/ptr_store_dse.c
UNITY_MEMBERS_opt_ssa_scalar = \
	source/opt/ssa/scalar/bitop_const_fold.c \
	source/opt/ssa/scalar/bool_norm.c \
	source/opt/ssa/scalar/cmp_offset_fold.c \
	source/opt/ssa/scalar/fold.c \
	source/opt/ssa/scalar/gvn.c \
	source/opt/ssa/scalar/narrow.c \
	source/opt/ssa/scalar/reassoc.c \
	source/opt/ssa/scalar/setif_or_taut.c \
	source/opt/ssa/scalar/strength.c \
	source/opt/ssa/scalar/tmp_block_const.c \
	source/opt/ssa/scalar/var_imm_prop.c
UNITY_MEMBERS_opt_ssa_scalar_prop = \
	source/opt/ssa/scalar/cprop.c \
	source/opt/ssa/scalar/sccp.c
UNITY_MEMBERS_opt_ssa_string = \
	source/opt/ssa/string/const_string_fold.c \
	source/opt/ssa/string/str_memchr.c \
	source/opt/ssa/string/str_strchr.c \
	source/opt/ssa/string/str_strcmp.c \
	source/opt/ssa/string/str_strcpy.c \
	source/opt/ssa/string/str_strlen.c \
	source/opt/ssa/string/str_strspn.c \
	source/opt/ssa/string/str_strstr.c
UNITY_MEMBERS_opt_util = \
	source/opt/util/block_scan.c \
	source/opt/util/call_params.c \
	source/opt/util/cond_util.c \
	source/opt/util/const_eval.c \
	source/opt/util/const_string_eval.c \
	source/opt/util/expr_equal.c \
	source/opt/util/ir_insert.c \
	source/opt/util/pass_disable.c \
	source/opt/util/purity.c \
	source/opt/util/range.c \
	source/opt/util/volatile_access.c \
	source/opt/util/vreg_def_use.c \
	source/opt/util/vreg_query.c \
	source/opt/util/xform.c
